syntax = "proto3";
package Cratis.Chronicle.Contracts.EventSequences;
import "protobuf-net/bcl.proto"; // schema for protobuf-net's handling of core .NET types

message IsStreamCompletedRequest {
   string EventSequenceId = 1;
   string EventStore = 2;
   string Namespace = 3;
   string EventStreamType = 4;
   string EventStreamId = 5;
}
message QueryResult_Boolean {
   .bcl.Guid CorrelationId = 1; // default value could not be applied: 00000000-0000-0000-0000-000000000000
   bool IsAuthorized = 2; // default value could not be applied: True
   repeated ValidationResult ValidationResults = 3;
   repeated string ExceptionMessages = 4;
   string ExceptionStackTrace = 5;
   bool Data = 6;
}
message ValidationResult {
   ValidationResultSeverity Severity = 1; // default value could not be applied: Error
   string Message = 2;
   repeated string Members = 3;
}
enum ValidationResultSeverity {
   Unknown = 0;
   Information = 1;
   Warning = 2;
   Error = 3;
}
service EventSequenceQueries {
   rpc IsStreamCompleted (IsStreamCompletedRequest) returns (QueryResult_Boolean);
}
