// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Observation.Webhooks;
using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.Observation.Webhooks;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Observation.Webhooks.IWebhooks"/>.
/// </summary>
internal sealed class Webhooks(
    global::Cratis.Arc.Commands.ICommandPipeline commandPipeline,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Observation.Webhooks.Webhooks> logger) : global::Cratis.Chronicle.Contracts.Observation.Webhooks.IWebhooks
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AddWebhook(global::Cratis.Chronicle.Contracts.Observation.Webhooks.AddWebhookRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Observation.Webhooks.AddWebhook((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.Observation.Webhooks.WebhookId)request.Name, request.Url, request.EventSequenceId, request.EventTypes, request.AuthorizationType, request.BasicUsername, request.BasicPassword, request.BearerToken, request.OAuthAuthority, request.OAuthClientId, request.OAuthClientSecret, request.Headers, request.IsReplayable, request.IsActive));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AddWebhooks(global::Cratis.Chronicle.Contracts.Observation.Webhooks.AddWebhooksRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Observation.Webhooks.AddWebhooks((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, request.Webhooks));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RemoveWebhook(global::Cratis.Chronicle.Contracts.Observation.Webhooks.RemoveWebhookRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Observation.Webhooks.RemoveWebhook((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.Observation.Webhooks.WebhookId)request.WebhookId));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RemoveWebhooks(global::Cratis.Chronicle.Contracts.Observation.Webhooks.RemoveWebhooksRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Observation.Webhooks.RemoveWebhooks((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, request.Webhooks.Select(x => (global::Cratis.Chronicle.Concepts.Observation.Webhooks.WebhookId)x)));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Observation.Webhooks.WebhookDetailsResponse>>> GetWebhooks(global::Cratis.Chronicle.Contracts.Observation.Webhooks.GetWebhooksRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Observation.Webhooks.WebhookDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Observation.Webhooks.WebhookDetails.GetWebhooks((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, storage);
                return result.Select(ToWebhookDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Webhooks", "GetWebhooks"));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Observation.Webhooks.WebhookDetailsResponse>>> ObserveWebhooks(global::Cratis.Chronicle.Contracts.Observation.Webhooks.ObserveWebhooksRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Observation.Webhooks.WebhookDetailsResponse>>(
            () => global::Cratis.Chronicle.Observation.Webhooks.WebhookDetails.ObserveWebhooks((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.Observation.Webhooks.WebhookDetailsResponse>)_.Select(ToWebhookDetailsResponse).ToList()),
            exception => logger.QueryFailed(exception, "Webhooks", "ObserveWebhooks"));

    static global::Cratis.Chronicle.Contracts.Observation.Webhooks.WebhookDetailsResponse ToWebhookDetailsResponse(global::Cratis.Chronicle.Observation.Webhooks.WebhookDetails source) =>
        new()
        {
            Id = source.Id,
            Identifier = source.Identifier,
            Url = source.Url,
            EventSequenceId = source.EventSequenceId,
            EventTypes = source.EventTypes,
            AuthorizationType = source.AuthorizationType,
            Headers = source.Headers,
            IsReplayable = source.IsReplayable,
            IsActive = source.IsActive
        };
}
