// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.EventStores;
/// <summary>
/// Defines the gRPC service contract for EventStores.
/// </summary>
[Service]
public interface IEventStores
{
    /// <summary>
    /// Executes the EnsureEventStore command.
    /// </summary>
    /// <param name = "request">The EnsureEventStore request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task EnsureEventStore(EnsureEventStoreRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllEventStores query.
    /// </summary>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<IEnumerable<string>> AllEventStores(CallContext callContext = default);
}

/// <summary>
/// Represents the EnsureEventStoreRequest message.
/// </summary>
[ProtoContract]
public class EnsureEventStoreRequest
{
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(1)]
    public string Name { get; set; }
}