import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';
import eslint from '@eslint/js';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import header from '@tony.ganchev/eslint-plugin-header';
import noNull from 'eslint-plugin-no-null';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactlint from 'eslint-plugin-react';

header.rules.header.meta.schema = false;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all,
});

// Generated proxies declare themselves on their first line, and that line is not decoration: it carries the hash
// the Cratis proxy generator reads to decide whether the file it is about to write already matches. The header
// rule below wants the license header at line 1 instead, and `yarn lint` runs with --fix, so linting these files
// rewrites that line away across the whole tree - silently, and in a way no build catches.
//
// They cannot be excluded by path. Generated proxies now land in Features/ next to hand-written components -
// Features/Security holds Login.tsx and AllUsers.ts side by side - so the only thing that reliably identifies one
// is the file saying so. Find them the same way the generator marks them.
//
// The barrel the generator writes beside them is the exception: it is generated too, but it carries no marker to
// find it by - the generator has never written a header of any kind into an index.ts, on this branch or before it.
// An index.ts sitting in a directory that holds generated files is one of those barrels, so it is excluded with
// them rather than being asked for a license header the generator will never write.
const generatedMarker = '// @generated by Cratis';

const findGenerated = directory => {
    const found = [];
    const walk = current => {
        let holdsGenerated = false;
        for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
            const full = path.join(current, entry.name);
            if (entry.isDirectory()) {
                if (entry.name !== 'node_modules') {
                    walk(full);
                }
            } else if (entry.name.endsWith('.ts') || entry.name.endsWith('.tsx')) {
                const handle = fs.openSync(full, 'r');
                const buffer = Buffer.alloc(generatedMarker.length);
                fs.readSync(handle, buffer, 0, buffer.length, 0);
                fs.closeSync(handle);
                if (buffer.toString('utf8') === generatedMarker) {
                    found.push(path.relative(__dirname, full));
                    holdsGenerated = true;
                }
            }
        }

        const barrel = path.join(current, 'index.ts');
        if (holdsGenerated && fs.existsSync(barrel)) {
            found.push(path.relative(__dirname, barrel));
        }
    };

    if (fs.existsSync(directory)) {
        walk(directory);
    }

    return found;
};

const generatedSources = findGenerated(path.join(__dirname, 'Features'))
    .concat(findGenerated(path.join(__dirname, 'Api')));

const getRules = configArray => {
    let rules = {};

    const addRulesFromObject = config => {
        if (config.hasOwnProperty('rules')) {
            rules = {
                ...rules,
                ...config.rules,
            };
        }
    };

    if (Array.isArray(configArray)) {
        for (const config of configArray) {
            addRulesFromObject(config);
        }
    } else {
        addRulesFromObject(configArray);
    }

    return rules;
};

const rules = {
    ...getRules(eslint.configs.recommended),
    ...getRules(tseslint.configs.recommended),
    ...getRules(reactlint.configs.recommended),
    ...{
        'no-irregular-whitespace': 0,
        semi: [2, 'always'],
        'react/display-name': 0,
        'react/react-in-jsx-scope': 0,
        'no-prototype-builtins': 0,

        '@typescript-eslint/no-unused-vars': [
            'error',
            {
                ignoreRestSiblings: true,
            },
        ],

        '@typescript-eslint/no-explicit-any': 'error',
        '@typescript-eslint/explicit-module-boundary-types': 0,
        '@typescript-eslint/no-non-null-assertion': 0,
        '@typescript-eslint/no-empty-function': 'error',
        '@typescript-eslint/no-var-requires': 'error',
        '@typescript-eslint/ban-ts-comment': 0,
        "@typescript-eslint/no-empty-interface": 0,

        '@tony.ganchev/header': [
            2,
            'line',
            [
                ' Copyright (c) Cratis. All rights reserved.',
                ' Licensed under the MIT license. See LICENSE file in the project root for full license information.'
            ],
            1
        ],
    },
};

const defaultConfig = [
    {
        ignores: [
            '**/*.d.ts',
            '**/*.scss.d.ts',
            '**/tsconfig.*',
            '**/wallaby.js',
            '**/*.js',
            '**/dist/**',
            '**/node_modules/**',
            '**/wwwroot/**',
            '**/templates/**',
            '**/Api/**',
            ...generatedSources,
            '**/rollup.config.mjs',
            '**/vite.config.ts',
            '**/link-eslint-typescript.cjs'
        ],
    },
    {
        files: ['**/*.ts', '**/*.tsx'],

        plugins: {
            '@typescript-eslint': typescriptEslint,
            react: reactlint,
            '@tony.ganchev': header,
            'no-null': noNull
        },

        rules: rules,

        languageOptions: {
            globals: {
                ...globals.browser,
            },
            parser: tsParser,
            sourceType: 'module',
        },

        settings: {
            react: {
                version: '19.2',
            },
        },
    },
    {
        files: ['**/for_*/**/*.ts'],
        rules: {
            '@typescript-eslint/naming-convention': 0,
            '@typescript-eslint/no-unused-expressions': 0,
            "@typescript-eslint/no-empty-function": "off",
            'no-restricted-globals': 0,
        },
    },
];

const config = tseslint.config(...defaultConfig);
export default config;
