// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Statistics;

namespace Cratis.Chronicle.Services.Statistics;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Statistics.IStatistics"/>.
/// </summary>
internal sealed class Statistics(
    global::Cratis.Chronicle.Statistics.IStatisticsReader statisticsReader,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Statistics.Statistics> logger) : global::Cratis.Chronicle.Contracts.Statistics.IStatistics
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Statistics.EventStatisticsResponse>> StatisticsForEventStore(global::Cratis.Chronicle.Contracts.Statistics.StatisticsForEventStoreRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Statistics.EventStatisticsResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Statistics.EventStatistics.StatisticsForEventStore(statisticsReader, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore);
                return ToEventStatisticsResponse(result);
            },
            exception => logger.QueryFailed(exception, "Statistics", "StatisticsForEventStore"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Statistics.EventStatisticsResponse>> StatisticsForNamespace(global::Cratis.Chronicle.Contracts.Statistics.StatisticsForNamespaceRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Statistics.EventStatisticsResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Statistics.EventStatistics.StatisticsForNamespace(statisticsReader, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace);
                return ToEventStatisticsResponse(result);
            },
            exception => logger.QueryFailed(exception, "Statistics", "StatisticsForNamespace"));

    static global::Cratis.Chronicle.Contracts.Statistics.EventStatisticsResponse ToEventStatisticsResponse(global::Cratis.Chronicle.Statistics.EventStatistics source) =>
        new()
        {
            TotalEvents = source.TotalEvents,
            EventTypes = source.EventTypes,
            Namespaces = source.Namespaces,
            PerEventType = source.PerEventType.Select(element0 => element0.ToContract()).ToList()
        };
}
