// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Reflection;
using Cratis.Chronicle.SharedTypeCatalog;
using Cratis.Chronicle.Tools.GrpcCodeGenerator.for_SharedTypeRegistry;
using Microsoft.CodeAnalysis;

namespace Cratis.Chronicle.Tools.GrpcCodeGenerator.for_ServiceInterfaceGenerator.when_generating_a_shared_type;

/// <summary>
/// The composite-type path is the one shared-type generation had no coverage for at all until this spec - only
/// the enum path had a real caller (<c>JobStatus</c>). Proves the generated class actually compiles as a
/// <c>[ProtoContract]</c> message, not just that it produces syntactically plausible-looking text.
/// </summary>
[Collection(SharedTypeRegistryCollection.Name)]
public class and_the_type_is_a_composite_record : given.a_shared_type_generator
{
    string _code = null!;
    IReadOnlyList<Diagnostic> _errors = null!;
    Assembly? _assembly;

    void Because()
    {
        _code = _generator.GenerateSharedType(typeof(CoreOwnedValue), _outputDir);
        (_errors, _assembly) = for_ServiceImplementationGenerator.given.GeneratedSourceCompiler.Compile(_code);
    }

    [Fact] void should_compile_without_errors() => _errors.ShouldBeEmpty();
    [Fact] void should_mark_it_as_a_proto_contract() => _code.ShouldContain("[ProtoContract]");
    [Fact] void should_number_the_property_as_the_first_proto_member() => _code.ShouldContain("[ProtoMember(1)]");
    [Fact] void should_write_it_under_the_mapped_namespace_folder() =>
        Path.GetFileName(Path.GetDirectoryName(FindGeneratedFilePath())).ShouldEqual("SharedTypeCatalog");
    [Fact] void should_mark_the_file_as_generated() => _code.ShouldContain("// <auto-generated />");

    string FindGeneratedFilePath() =>
        Directory.GetFiles(_outputDir, "CoreOwnedValue.cs", SearchOption.AllDirectories).Single();
}
