// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Sequences;

namespace Cratis.Chronicle.Services.Sequences;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Sequences.IEventSequences"/>.
/// </summary>
internal sealed class EventSequences(
    global::Orleans.IGrainFactory grainFactory,
    global::Cratis.Chronicle.Sequences.RequestCausation requestCausation,
    global::Cratis.Arc.Authorization.ICurrentPrincipalAccessor currentPrincipalAccessor,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Cratis.Chronicle.Events.IEventCompliance eventCompliance,
    global::Cratis.Arc.Queries.IQueryContextManager queryContextManager,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Sequences.EventSequences> logger) : global::Cratis.Chronicle.Contracts.Sequences.IEventSequences
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> Append(global::Cratis.Chronicle.Contracts.Sequences.AppendRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Sequences.Append(request.EventStore, request.Namespace, request.EventSequenceId, request.EventSourceId, request.EventSourceType, request.EventStreamType, request.EventStreamId, request.EventType.ToApi(), request.Content),
            command => command.Handle(grainFactory, requestCausation, currentPrincipalAccessor));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AppendMany(global::Cratis.Chronicle.Contracts.Sequences.AppendManyRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Sequences.AppendMany(request.EventStore, request.Namespace, request.EventSequenceId, request.EventSourceId, request.Events.Select(x => x.ToApi())),
            command => command.Handle(grainFactory, requestCausation, currentPrincipalAccessor));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> Redact(global::Cratis.Chronicle.Contracts.Sequences.RedactRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Sequences.Redact(request.EventStore, request.Namespace, request.EventSequenceId, request.SequenceNumber, request.Reason),
            command => command.Handle(grainFactory, requestCausation, currentPrincipalAccessor));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RedactForEventSource(global::Cratis.Chronicle.Contracts.Sequences.RedactForEventSourceRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Sequences.RedactForEventSource(request.EventStore, request.Namespace, request.EventSequenceId, request.EventSourceId, request.Reason, request.EventTypes),
            command => command.Handle(grainFactory, requestCausation, currentPrincipalAccessor));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> Revise(global::Cratis.Chronicle.Contracts.Sequences.ReviseRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Sequences.Revise(request.EventStore, request.Namespace, request.EventSequenceId, request.SequenceNumber, request.EventType.ToApi(), request.Content),
            command => command.Handle(grainFactory, requestCausation, currentPrincipalAccessor));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>> AppendedEvents(global::Cratis.Chronicle.Contracts.Sequences.AppendedEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.AppendedEvent.AppendedEvents(storage, eventCompliance, request.JsonSerializerOptions, queryContextManager, request.EventStore, request.Namespace, request.EventSequenceId, request.EventSourceId);
                return result.Select(ToAppendedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "AppendedEvents"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>> QueryEvents(global::Cratis.Chronicle.Contracts.Sequences.QueryEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.AppendedEvent.QueryEvents(storage, eventCompliance, request.JsonSerializerOptions, queryContextManager, request.EventStore, request.Namespace, request.EventSequenceId, request.EventSourceId, request.EventSourceType, request.EventStreamType, request.CorrelationId, request.EventTypeIds, request.Tags, request.OccurredFrom, request.OccurredTo);
                return result.Select(ToAppendedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "QueryEvents"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventSequenceNamesResponse>>> AllEventSequences(global::Cratis.Chronicle.Contracts.Sequences.AllEventSequencesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventSequenceNamesResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.EventSequenceNames.AllEventSequences(grainFactory, request.EventStore, request.Namespace);
                return result.Select(ToEventSequenceNamesResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "AllEventSequences"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.ExportedEventResponse>>> ExportEvents(global::Cratis.Chronicle.Contracts.Sequences.ExportEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.ExportedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.ExportedEvent.ExportEvents(storage, eventCompliance, request.JsonSerializerOptions, queryContextManager, request.EventStore, request.Namespace, request.EventSequenceId, request.EventSourceId, request.EventSourceType, request.EventStreamType, request.CorrelationId, request.EventTypeIds, request.Tags, request.OccurredFrom, request.OccurredTo);
                return result.Select(ToExportedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "ExportEvents"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset>> EndOf(global::Cratis.Chronicle.Contracts.Sequences.EndOfRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset>(
            () =>
            {
                var result = global::Cratis.Chronicle.Sequences.SequenceHistogramBucket.EndOf(request.Start, (global::Cratis.Chronicle.Storage.EventSequences.HistogramResolution)request.Resolution);
                return Task.FromResult<global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset>((global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)result);
            },
            exception => logger.QueryFailed(exception, "EventSequences", "EndOf"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution>> ParseResolution(global::Cratis.Chronicle.Contracts.Sequences.ParseResolutionRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution>(
            () =>
            {
                var result = global::Cratis.Chronicle.Sequences.SequenceHistogramBucket.ParseResolution(request.Resolution);
                return Task.FromResult<global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution>((global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution)result);
            },
            exception => logger.QueryFailed(exception, "EventSequences", "ParseResolution"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramBucketResponse>>> SequenceHistogram(global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramBucketResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.SequenceHistogramBucket.SequenceHistogram(storage, request.EventStore, request.Namespace, request.EventSequenceId, request.Resolution, request.EventSourceId, request.EventSourceType, request.EventStreamType, request.CorrelationId, request.EventTypeIds, request.Tags, request.OccurredFrom, request.OccurredTo);
                return result.Select(ToSequenceHistogramBucketResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "SequenceHistogram"));

    static global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse ToAppendedEventResponse(global::Cratis.Chronicle.Sequences.AppendedEvent source) =>
        new()
        {
            Id = source.Id,
            Context = source.Context.ToContract(),
            Content = source.Content,
            OriginalContent = source.OriginalContent,
            Revisions = source.Revisions is null ? null : source.Revisions.Select(element0 => element0.ToContract()).ToList(),
            GenerationalContent = source.GenerationalContent
        };

    static global::Cratis.Chronicle.Contracts.Sequences.EventSequenceNamesResponse ToEventSequenceNamesResponse(global::Cratis.Chronicle.Sequences.EventSequenceNames source) =>
        new()
        {
            Id = source.Id,
            Name = source.Name
        };

    static global::Cratis.Chronicle.Contracts.Sequences.ExportedEventResponse ToExportedEventResponse(global::Cratis.Chronicle.Sequences.ExportedEvent source) =>
        new()
        {
            SequenceNumber = source.SequenceNumber,
            EventType = source.EventType,
            EventSourceType = source.EventSourceType,
            EventSourceId = source.EventSourceId,
            EventStreamType = source.EventStreamType,
            CorrelationId = source.CorrelationId,
            Occurred = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.Occurred,
            Tags = source.Tags,
            Content = source.Content
        };

    static global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramBucketResponse ToSequenceHistogramBucketResponse(global::Cratis.Chronicle.Sequences.SequenceHistogramBucket source) =>
        new()
        {
            From = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.From,
            To = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.To,
            Count = source.Count
        };
}
