// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Sequences;

namespace Cratis.Chronicle.Services.Sequences;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Sequences.IEventSequences"/>.
/// </summary>
internal sealed class EventSequences(
    global::Cratis.Arc.Commands.ICommandPipeline commandPipeline,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Cratis.Chronicle.Events.IEventCompliance eventCompliance,
    global::System.Text.Json.JsonSerializerOptions jsonSerializerOptions,
    global::Cratis.Arc.Queries.IQueryContextManager queryContextManager,
    global::Orleans.IGrainFactory grainFactory,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Sequences.EventSequences> logger) : global::Cratis.Chronicle.Contracts.Sequences.IEventSequences
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.Sequences.AppendResponse>> Append(global::Cratis.Chronicle.Contracts.Sequences.AppendRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.EventSequences.AppendResult, global::Cratis.Chronicle.Contracts.Sequences.AppendResponse>(
            commandPipeline,
            new global::Cratis.Chronicle.Sequences.Append((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId, (global::Cratis.Chronicle.Concepts.Events.EventSourceType)request.EventSourceType, (global::Cratis.Chronicle.Concepts.Events.EventStreamType)request.EventStreamType, (global::Cratis.Chronicle.Concepts.Events.EventStreamId)request.EventStreamId, request.EventType.ToApi(), request.Content, request.CorrelationId, request.Tags, request.Occurred, request.Subject, request.Causation?.Select(x => x.ToApi()), request.CausedBy?.ToApi(), request.ConcurrencyScope?.ToApi()),
            response => ToAppendResponse(response));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.Sequences.AppendManyResponse>> AppendMany(global::Cratis.Chronicle.Contracts.Sequences.AppendManyRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.EventSequences.AppendManyResult, global::Cratis.Chronicle.Contracts.Sequences.AppendManyResponse>(
            commandPipeline,
            new global::Cratis.Chronicle.Sequences.AppendMany((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId, request.Events.Select(x => x.ToApi()), request.CorrelationId, request.Tags, request.Occurred, request.Causation?.Select(x => x.ToApi()), request.CausedBy?.ToApi(), request.ConcurrencyScope?.ToApi()),
            response => ToAppendManyResponse(response));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.Sequences.AppendManyResponse>> AppendManyForEventSources(global::Cratis.Chronicle.Contracts.Sequences.AppendManyForEventSourcesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.EventSequences.AppendManyResult, global::Cratis.Chronicle.Contracts.Sequences.AppendManyResponse>(
            commandPipeline,
            new global::Cratis.Chronicle.Sequences.AppendManyForEventSources((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, request.Events.Select(x => x.ToApi()), request.CorrelationId, request.Tags, request.Causation?.Select(x => x.ToApi()), request.CausedBy?.ToApi(), request.ConcurrencyScopes?.Select(x => x.ToApi())),
            response => ToAppendManyResponse(response));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.Sequences.CompleteStreamResponse>> CompleteStream(global::Cratis.Chronicle.Contracts.Sequences.CompleteStreamRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.Sequences.CompleteStreamOutcome, global::Cratis.Chronicle.Contracts.Sequences.CompleteStreamResponse>(
            commandPipeline,
            new global::Cratis.Chronicle.Sequences.CompleteStream((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (global::Cratis.Chronicle.Concepts.Events.EventStreamType)request.EventStreamType, (global::Cratis.Chronicle.Concepts.Events.EventStreamId)request.EventStreamId),
            response => ToCompleteStreamResponse(response));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> Redact(global::Cratis.Chronicle.Contracts.Sequences.RedactRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Sequences.Redact((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, request.SequenceNumber, request.Reason, request.Causation?.Select(x => x.ToApi()), request.CausedBy?.ToApi()));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RedactForEventSource(global::Cratis.Chronicle.Contracts.Sequences.RedactForEventSourceRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Sequences.RedactForEventSource((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId, request.Reason, request.EventTypes, request.Causation?.Select(x => x.ToApi()), request.CausedBy?.ToApi()));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> Revise(global::Cratis.Chronicle.Contracts.Sequences.ReviseRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Sequences.Revise((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, request.SequenceNumber, request.EventType.ToApi(), request.Content, request.Causation?.Select(x => x.ToApi()), request.CausedBy?.ToApi()));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>> AppendedEvents(global::Cratis.Chronicle.Contracts.Sequences.AppendedEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.AppendedEvent.AppendedEvents(storage, eventCompliance, jsonSerializerOptions, queryContextManager, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (request.EventSourceId is null ? null : (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId));
                return result.Select(ToAppendedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "AppendedEvents"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>> ForEventSourceIdAndEventTypes(global::Cratis.Chronicle.Contracts.Sequences.ForEventSourceIdAndEventTypesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.AppendedEvent.ForEventSourceIdAndEventTypes(storage, eventCompliance, jsonSerializerOptions, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, request.EventSourceId, request.EventTypeIds, request.EventStreamType, request.EventStreamId);
                return result.Select(ToAppendedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "ForEventSourceIdAndEventTypes"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>> FromSequenceNumber(global::Cratis.Chronicle.Contracts.Sequences.FromSequenceNumberRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.AppendedEvent.FromSequenceNumber(storage, eventCompliance, jsonSerializerOptions, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, request.FromEventSequenceNumber, (request.EventSourceId is null ? null : (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId), request.EventTypeIds);
                return result.Select(ToAppendedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "FromSequenceNumber"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>> QueryEvents(global::Cratis.Chronicle.Contracts.Sequences.QueryEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.AppendedEvent.QueryEvents(storage, eventCompliance, jsonSerializerOptions, queryContextManager, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (request.EventSourceId is null ? null : (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId), request.EventSourceType, request.EventStreamType, request.CorrelationId, request.EventTypeIds, request.Tags, request.OccurredFrom, request.OccurredTo);
                return result.Select(ToAppendedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "QueryEvents"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventSequenceNamesResponse>>> AllEventSequences(global::Cratis.Chronicle.Contracts.Sequences.AllEventSequencesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventSequenceNamesResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.EventSequenceNames.AllEventSequences(grainFactory, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (request.Namespace is null ? null : (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace));
                return result.Select(ToEventSequenceNamesResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "AllEventSequences"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Sequences.EventSequenceTailResponse>> TailSequenceNumber(global::Cratis.Chronicle.Contracts.Sequences.TailSequenceNumberRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Sequences.EventSequenceTailResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.EventSequenceTail.TailSequenceNumber(storage, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, request.EventTypeIds, request.EventSourceId, request.EventSourceType, request.EventStreamId, request.EventStreamType);
                return ToEventSequenceTailResponse(result);
            },
            exception => logger.QueryFailed(exception, "EventSequences", "TailSequenceNumber"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Sequences.EventSourceEventsResponse>> HasEventsForEventSourceId(global::Cratis.Chronicle.Contracts.Sequences.HasEventsForEventSourceIdRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Sequences.EventSourceEventsResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.EventSourceEvents.HasEventsForEventSourceId(storage, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId);
                return ToEventSourceEventsResponse(result);
            },
            exception => logger.QueryFailed(exception, "EventSequences", "HasEventsForEventSourceId"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.ExportedEventResponse>>> ExportEvents(global::Cratis.Chronicle.Contracts.Sequences.ExportEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.ExportedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.ExportedEvent.ExportEvents(storage, eventCompliance, jsonSerializerOptions, queryContextManager, request.EventStore, request.Namespace, request.EventSequenceId, request.EventSourceId, request.EventSourceType, request.EventStreamType, request.CorrelationId, request.EventTypeIds, request.Tags, request.OccurredFrom, request.OccurredTo);
                return result.Select(ToExportedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "ExportEvents"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset>> EndOf(global::Cratis.Chronicle.Contracts.Sequences.EndOfRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset>(
            () =>
            {
                var result = global::Cratis.Chronicle.Sequences.SequenceHistogramBucket.EndOf(request.Start, (global::Cratis.Chronicle.Storage.EventSequences.HistogramResolution)request.Resolution);
                return Task.FromResult<global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset>((global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)result);
            },
            exception => logger.QueryFailed(exception, "EventSequences", "EndOf"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution>> ParseResolution(global::Cratis.Chronicle.Contracts.Sequences.ParseResolutionRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution>(
            () =>
            {
                var result = global::Cratis.Chronicle.Sequences.SequenceHistogramBucket.ParseResolution(request.Resolution);
                return Task.FromResult<global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution>((global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution)result);
            },
            exception => logger.QueryFailed(exception, "EventSequences", "ParseResolution"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramBucketResponse>>> SequenceHistogram(global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramBucketResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Sequences.SequenceHistogramBucket.SequenceHistogram(storage, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, request.Resolution, request.EventSourceId, request.EventSourceType, request.EventStreamType, request.CorrelationId, request.EventTypeIds, request.Tags, request.OccurredFrom, request.OccurredTo);
                return result.Select(ToSequenceHistogramBucketResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSequences", "SequenceHistogram"));

    static global::Cratis.Chronicle.Contracts.Sequences.AppendResponse ToAppendResponse(global::Cratis.Chronicle.EventSequences.AppendResult source) =>
        new()
        {
            CorrelationId = (global::System.Guid)source.CorrelationId,
            SequenceNumber = (ulong)source.SequenceNumber,
            IsSuccess = source.IsSuccess,
            HasConstraintViolations = source.HasConstraintViolations,
            HasConcurrencyViolations = source.HasConcurrencyViolations,
            HasErrors = source.HasErrors,
            ConcurrencyCheckPerformed = source.ConcurrencyCheckPerformed,
            ConstraintViolations = source.ConstraintViolations.Select(element0 => element0.ToContract()).ToList(),
            Errors = source.Errors.Select(element0 => (string)element0).ToList(),
            ConcurrencyViolation = source.ConcurrencyViolation is null ? null : source.ConcurrencyViolation.ToContract()
        };

    static global::Cratis.Chronicle.Contracts.Sequences.AppendManyResponse ToAppendManyResponse(global::Cratis.Chronicle.EventSequences.AppendManyResult source) =>
        new()
        {
            CorrelationId = (global::System.Guid)source.CorrelationId,
            SequenceNumbers = source.SequenceNumbers.Select(element0 => (ulong)element0).ToList(),
            IsSuccess = source.IsSuccess,
            HasConstraintViolations = source.HasConstraintViolations,
            HasConcurrencyViolations = source.HasConcurrencyViolations,
            HasErrors = source.HasErrors,
            ConcurrencyCheckPerformed = source.ConcurrencyCheckPerformed,
            ConstraintViolations = source.ConstraintViolations.Select(element0 => element0.ToContract()).ToList(),
            Errors = source.Errors.Select(element0 => (string)element0).ToList(),
            ConcurrencyViolations = source.ConcurrencyViolations.Select(element0 => element0.ToContract()).ToList()
        };

    static global::Cratis.Chronicle.Contracts.Sequences.CompleteStreamResponse ToCompleteStreamResponse(global::Cratis.Chronicle.Sequences.CompleteStreamOutcome source) =>
        new()
        {
            IsSuccess = source.IsSuccess,
            SequenceNumber = (ulong)source.SequenceNumber,
            Error = (global::Cratis.Chronicle.Contracts.Sequences.CompleteStreamError)source.Error
        };

    static global::Cratis.Chronicle.Contracts.Sequences.AppendedEventResponse ToAppendedEventResponse(global::Cratis.Chronicle.Sequences.AppendedEvent source) =>
        new()
        {
            Id = source.Id,
            Context = source.Context.ToContract(),
            Content = source.Content,
            OriginalContent = source.OriginalContent,
            Revisions = source.Revisions is null ? null : source.Revisions.Select(element0 => element0.ToContract()).ToList(),
            GenerationalContent = source.GenerationalContent
        };

    static global::Cratis.Chronicle.Contracts.Sequences.EventSequenceNamesResponse ToEventSequenceNamesResponse(global::Cratis.Chronicle.Sequences.EventSequenceNames source) =>
        new()
        {
            Id = source.Id,
            Name = source.Name
        };

    static global::Cratis.Chronicle.Contracts.Sequences.EventSequenceTailResponse ToEventSequenceTailResponse(global::Cratis.Chronicle.Sequences.EventSequenceTail source) =>
        new()
        {
            SequenceNumber = (ulong)source.SequenceNumber
        };

    static global::Cratis.Chronicle.Contracts.Sequences.EventSourceEventsResponse ToEventSourceEventsResponse(global::Cratis.Chronicle.Sequences.EventSourceEvents source) =>
        new()
        {
            HasEvents = source.HasEvents
        };

    static global::Cratis.Chronicle.Contracts.Sequences.ExportedEventResponse ToExportedEventResponse(global::Cratis.Chronicle.Sequences.ExportedEvent source) =>
        new()
        {
            SequenceNumber = source.SequenceNumber,
            EventType = source.EventType,
            EventSourceType = source.EventSourceType,
            EventSourceId = source.EventSourceId,
            EventStreamType = source.EventStreamType,
            CorrelationId = source.CorrelationId,
            Occurred = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.Occurred,
            Tags = source.Tags,
            Content = source.Content
        };

    static global::Cratis.Chronicle.Contracts.Sequences.SequenceHistogramBucketResponse ToSequenceHistogramBucketResponse(global::Cratis.Chronicle.Sequences.SequenceHistogramBucket source) =>
        new()
        {
            From = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.From,
            To = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.To,
            Count = source.Count
        };
}
