// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.EventSources;
using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.EventSources;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.EventSources.IEventSources"/>.
/// </summary>
internal sealed class EventSources(
    global::Cratis.Arc.Commands.ICommandPipeline commandPipeline,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.EventSources.EventSources> logger) : global::Cratis.Chronicle.Contracts.EventSources.IEventSources
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RegisterEventSources(global::Cratis.Chronicle.Contracts.EventSources.RegisterEventSourcesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.EventSources.RegisterEventSources((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, request.Sources));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.EventSources.EventSourceDetailsResponse>>> AllEventSources(global::Cratis.Chronicle.Contracts.EventSources.AllEventSourcesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.EventSources.EventSourceDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.EventSources.EventSourceDetails.AllEventSources((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, storage);
                return result.Select(ToEventSourceDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventSources", "AllEventSources"));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.EventSources.EventSourceDetailsResponse>>> ObserveEventSources(global::Cratis.Chronicle.Contracts.EventSources.ObserveEventSourcesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.EventSources.EventSourceDetailsResponse>>(
            () => global::Cratis.Chronicle.EventSources.EventSourceDetails.ObserveEventSources((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.EventSources.EventSourceDetailsResponse>)_.Select(ToEventSourceDetailsResponse).ToList()),
            exception => logger.QueryFailed(exception, "EventSources", "ObserveEventSources"));

    static global::Cratis.Chronicle.Contracts.EventSources.EventSourceDetailsResponse ToEventSourceDetailsResponse(global::Cratis.Chronicle.EventSources.EventSourceDetails source) =>
        new()
        {
            Id = source.Id,
            Name = source.Name,
            Description = source.Description,
            Owner = source.Owner,
            Concurrency = source.Concurrency,
            Streams = source.Streams
        };
}
