<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Cratis.Chronicle.Api.Specs</AssemblyName>
        <RootNamespace>Cratis.Chronicle.Api</RootNamespace>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Api/Api.csproj" />
    </ItemGroup>
</Project>
