// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.ProjectionEditor;

namespace Cratis.Chronicle.Services.ProjectionEditor;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.ProjectionEditor.IProjectionEditor"/>.
/// </summary>
internal sealed class ProjectionEditor(
    global::Cratis.Arc.Commands.ICommandPipeline commandPipeline) : global::Cratis.Chronicle.Contracts.ProjectionEditor.IProjectionEditor
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.ProjectionEditor.GenerateDeclarativeCodeResponse>> GenerateDeclarativeCode(global::Cratis.Chronicle.Contracts.ProjectionEditor.GenerateDeclarativeCodeRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.ProjectionEditor.GeneratedCodeResult, global::Cratis.Chronicle.Contracts.ProjectionEditor.GenerateDeclarativeCodeResponse>(
            commandPipeline,
            new global::Cratis.Chronicle.ProjectionEditor.GenerateDeclarativeCode((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, request.Declaration, request.DraftReadModel?.ToApi(), request.Language),
            response => ToGenerateDeclarativeCodeResponse(response));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.ProjectionEditor.GenerateDeclarativeCodeResponse>> GenerateModelBoundCode(global::Cratis.Chronicle.Contracts.ProjectionEditor.GenerateModelBoundCodeRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.ProjectionEditor.GeneratedCodeResult, global::Cratis.Chronicle.Contracts.ProjectionEditor.GenerateDeclarativeCodeResponse>(
            commandPipeline,
            new global::Cratis.Chronicle.ProjectionEditor.GenerateModelBoundCode((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, request.Declaration, request.DraftReadModel?.ToApi(), request.Language),
            response => ToGenerateDeclarativeCodeResponse(response));

    static global::Cratis.Chronicle.Contracts.ProjectionEditor.GenerateDeclarativeCodeResponse ToGenerateDeclarativeCodeResponse(global::Cratis.Chronicle.ProjectionEditor.GeneratedCodeResult source) =>
        new()
        {
            Code = source.Code,
            Errors = source.Errors.Select(element0 => element0.ToContract()).ToList()
        };
}
