version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
  labels: []
  ignore:
    - dependency-name: Microsoft.Extensions.Configuration.FileExtensions
      versions:
        - ">=8.0.1"
        - "<9.0.0"
        - ">=9.0.0"
    - dependency-name: Microsoft.Extensions.Hosting
      versions:
        - ">=8.0.1"
        - "<9.0.0"
        - ">=9.0.0"
    - dependency-name: Microsoft.Extensions.Logging
      versions:
        - ">=8.0.1"
        - "<9.0.0"
        - ">=9.0.0"
    - dependency-name: Microsoft.Extensions.DependencyModel
      versions:
        - ">=8.0.1"
        - "<9.0.0"
        - ">=9.0.0"
    - dependency-name: System.Reflection.MetadataLogContext
      versions:
        - ">=8.0.1"
        - "<9.0.0"
        - ">=9.0.0"
    - dependency-name: System.Text.Json
      versions:
        - ">=8.0.1"
        - "<9.0.0"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
  labels: []
