// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Observation;
/// <summary>
/// Represents the FailureKind value.
/// </summary>
public enum FailureKind
{
    /// <summary>
    /// Represents the Unknown value.
    /// </summary>
    Unknown = 0,
    /// <summary>
    /// Represents the Handling value.
    /// </summary>
    Handling = 1,
    /// <summary>
    /// Represents the Timeout value.
    /// </summary>
    Timeout = 2,
    /// <summary>
    /// Represents the Disconnected value.
    /// </summary>
    Disconnected = 3
}