// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Observation;
/// <summary>
/// Defines the gRPC service contract for Observers.
/// </summary>
[Service]
public interface IObservers
{
    /// <summary>
    /// Executes the ReplayObserver command.
    /// </summary>
    /// <param name = "request">The ReplayObserver request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task ReplayObserver(ReplayObserverRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ReplayPartition command.
    /// </summary>
    /// <param name = "request">The ReplayPartition request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task ReplayPartition(ReplayPartitionRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RetryPartition command.
    /// </summary>
    /// <param name = "request">The RetryPartition request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task RetryPartition(RetryPartitionRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllObservers query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<IEnumerable<ObserverInformationResponse>> AllObservers(AllObserversRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ObserveObservers query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<IEnumerable<ObserverInformationResponse>> ObserveObservers(ObserveObserversRequest request, CallContext callContext = default);

    /// <summary>
    /// Clear quarantine for an observer.
    /// </summary>
    /// <param name="command">The clear quarantine command.</param>
    /// <param name="context">gRPC call context.</param>
    /// <returns>Awaitable task.</returns>
    [Operation]
    Task ClearObserverQuarantine(ClearObserverQuarantine command, CallContext context = default);

    /// <summary>
    /// Get the current details of an observer.
    /// </summary>
    /// <param name="request">The <see cref="GetObserverInformationRequest"/>.</param>
    /// <param name="context">gRPC call context.</param>
    /// <returns>The <see cref="ObserverInformation"/>.</returns>
    Task<ObserverInformation> GetObserverInformation(GetObserverInformationRequest request, CallContext context = default);

    /// <summary>
    /// Get all observers.
    /// </summary>
    /// <param name="request">The <see cref="AllObserversRequest"/>.</param>
    /// <param name="context">gRPC call context.</param>
    /// <returns>A collection of <see cref="ObserverInformation"/>.</returns>
    [Operation]
    Task<IEnumerable<ObserverInformation>> GetObservers(AllObserversRequest request, CallContext context = default);

    /// <summary>
    /// Waits for all affected observers to complete for a specific append tail sequence number.
    /// </summary>
    /// <param name="request">The <see cref="WaitForObserverCompletionRequest"/>.</param>
    /// <param name="context">gRPC call context.</param>
    /// <returns>A <see cref="WaitForObserverCompletionResponse"/> describing completion and failures.</returns>
    /// <remarks>
    /// The wait is bounded by the cancellation token on <paramref name="context"/>.
    /// </remarks>
    Task<WaitForObserverCompletionResponse> WaitForCompletion(WaitForObserverCompletionRequest request, CallContext context = default);

    /// <summary>
    /// Get all replayable observers for specific event types.
    /// </summary>
    /// <param name="request">The <see cref="GetReplayableObserversForEventTypesRequest"/>.</param>
    /// <param name="context">gRPC call context.</param>
    /// <returns>A collection of <see cref="ObserverInformation"/> for observers that support replay and observe the given event types.</returns>
    [Operation]
    Task<IEnumerable<ObserverInformation>> GetReplayableObserversForEventTypes(GetReplayableObserversForEventTypesRequest request, CallContext context = default);
}

/// <summary>
/// Represents the ReplayObserverRequest message.
/// </summary>
[ProtoContract]
public class ReplayObserverRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the ObserverId.
    /// </summary>
    [ProtoMember(3)]
    public string ObserverId { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }
}

/// <summary>
/// Represents the ReplayPartitionRequest message.
/// </summary>
[ProtoContract]
public class ReplayPartitionRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the ObserverId.
    /// </summary>
    [ProtoMember(3)]
    public string ObserverId { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the Partition.
    /// </summary>
    [ProtoMember(5)]
    public string Partition { get; set; }
}

/// <summary>
/// Represents the RetryPartitionRequest message.
/// </summary>
[ProtoContract]
public class RetryPartitionRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the ObserverId.
    /// </summary>
    [ProtoMember(3)]
    public string ObserverId { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the Partition.
    /// </summary>
    [ProtoMember(5)]
    public string Partition { get; set; }
}

/// <summary>
/// Represents the ObserverInformationResponse message.
/// </summary>
[ProtoContract]
public class ObserverInformationResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(2)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the Type.
    /// </summary>
    [ProtoMember(3)]
    public ObserverType Type { get; set; }

    /// <summary>
    /// Gets or sets the Owner.
    /// </summary>
    [ProtoMember(4)]
    public ObserverOwner Owner { get; set; }

    /// <summary>
    /// Gets or sets the EventTypes.
    /// </summary>
    [ProtoMember(5)]
    public IEnumerable<string> EventTypes { get; set; }

    /// <summary>
    /// Gets or sets the NextEventSequenceNumber.
    /// </summary>
    [ProtoMember(6)]
    public UInt64 NextEventSequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the LastHandledEventSequenceNumber.
    /// </summary>
    [ProtoMember(7)]
    public UInt64 LastHandledEventSequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the TailEventSequenceNumber.
    /// </summary>
    [ProtoMember(11)]
    public UInt64 TailEventSequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the HandledEventCount.
    /// </summary>
    [ProtoMember(12)]
    public UInt64 HandledEventCount { get; set; }

    /// <summary>
    /// Gets or sets the RunningState.
    /// </summary>
    [ProtoMember(8)]
    public ObserverRunningState RunningState { get; set; }

    /// <summary>
    /// Gets or sets the IsSubscribed.
    /// </summary>
    [ProtoMember(9)]
    public bool IsSubscribed { get; set; }

    /// <summary>
    /// Gets or sets the IsReplayable.
    /// </summary>
    [ProtoMember(10)]
    public bool IsReplayable { get; set; }
}

/// <summary>
/// Represents the AllObserversRequest message.
/// </summary>
[ProtoContract]
public class AllObserversRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}

/// <summary>
/// Represents the ObserveObserversRequest message.
/// </summary>
[ProtoContract]
public class ObserveObserversRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}