checksumBehavior: update

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 20913236-9B84-494C-82CF-0FCC3E4A07EE
    npmRegistryServer: "https://npm.fontawesome.com/"

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.4.1.cjs
