checksumBehavior: update

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

pnpMode: loose

enableImmutableInstalls: false

yarnPath: .yarn/releases/yarn-3.4.1.cjs
