checksumBehavior: update

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

pnpMode: loose

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

yarnPath: .yarn/releases/yarn-4.5.3.cjs
