// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Statistics;
/// <summary>
/// Represents the EventTypeCount message.
/// </summary>
[ProtoContract]
public class EventTypeCount
{
    /// <summary>
    /// Gets or sets the EventType.
    /// </summary>
    [ProtoMember(1)]
    public string EventType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Count.
    /// </summary>
    [ProtoMember(2)]
    public long Count { get; set; }
}