// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Statistics;
/// <summary>
/// Defines the gRPC service contract for Statistics.
/// </summary>
[Service]
public interface IStatistics
{
    /// <summary>
    /// Executes the StatisticsForEventStore query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<EventStatisticsResponse>> StatisticsForEventStore(StatisticsForEventStoreRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the StatisticsForNamespace query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<EventStatisticsResponse>> StatisticsForNamespace(StatisticsForNamespaceRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the EventStatisticsResponse message.
/// </summary>
[ProtoContract]
public class EventStatisticsResponse
{
    /// <summary>
    /// Gets or sets the TotalEvents.
    /// </summary>
    [ProtoMember(1)]
    public long TotalEvents { get; set; }

    /// <summary>
    /// Gets or sets the EventTypes.
    /// </summary>
    [ProtoMember(2)]
    public int EventTypes { get; set; }

    /// <summary>
    /// Gets or sets the Namespaces.
    /// </summary>
    [ProtoMember(3)]
    public int Namespaces { get; set; }

    /// <summary>
    /// Gets or sets the PerEventType.
    /// </summary>
    [ProtoMember(4)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Statistics.EventTypeCount> PerEventType { get; set; } = new List<global::Cratis.Chronicle.Contracts.Statistics.EventTypeCount>();
}

/// <summary>
/// Represents the StatisticsForEventStoreRequest message.
/// </summary>
[ProtoContract]
public class StatisticsForEventStoreRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;
}

/// <summary>
/// Represents the StatisticsForNamespaceRequest message.
/// </summary>
[ProtoContract]
public class StatisticsForNamespaceRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; } = string.Empty;
}