// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.Captures;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Captures.ICaptures"/>.
/// </summary>
internal sealed class Captures(
    global::Orleans.IGrainFactory grainFactory,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Cratis.Chronicle.Captures.Engine.DeclarationLanguage.ILanguageService languageService,
    global::Cratis.Chronicle.Captures.Engine.ICaptureValidator captureValidator,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Captures.Captures> logger) : global::Cratis.Chronicle.Contracts.Captures.ICaptures
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> DeleteCapture(global::Cratis.Chronicle.Contracts.Captures.DeleteCaptureRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Captures.DeleteCapture(request.EventStore, request.CaptureId),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.Captures.SaveCaptureResponse>> SaveCapture(global::Cratis.Chronicle.Contracts.Captures.SaveCaptureRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.Captures.SaveCapture, global::Cratis.Chronicle.Contracts.Captures.SaveCaptureResponse>(
            new global::Cratis.Chronicle.Captures.SaveCapture(request.EventStore, request.Id, request.Declaration),
            async command => ToSaveCaptureResponse((await command.Handle(storage, languageService, captureValidator))));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.Captures.StartCaptureResponse>> StartCapture(global::Cratis.Chronicle.Contracts.Captures.StartCaptureRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.Captures.StartCapture, global::Cratis.Chronicle.Contracts.Captures.StartCaptureResponse>(
            new global::Cratis.Chronicle.Captures.StartCapture(request.EventStore, request.CaptureId),
            async command => ToStartCaptureResponse((await command.Handle(grainFactory))));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> StopCapture(global::Cratis.Chronicle.Contracts.Captures.StopCaptureRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Captures.StopCapture(request.EventStore, request.CaptureId),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult<global::Cratis.Chronicle.Contracts.Captures.ValidateCaptureDeclarationResponse>> ValidateCaptureDeclaration(global::Cratis.Chronicle.Contracts.Captures.ValidateCaptureDeclarationRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute<global::Cratis.Chronicle.Captures.ValidateCaptureDeclaration, global::Cratis.Chronicle.Contracts.Captures.ValidateCaptureDeclarationResponse>(
            new global::Cratis.Chronicle.Captures.ValidateCaptureDeclaration(request.EventStore, request.Declaration),
            async command => ToValidateCaptureDeclarationResponse((await command.Handle(languageService, captureValidator))));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Captures.CaptureDetailsResponse>>> GetCaptures(global::Cratis.Chronicle.Contracts.Captures.GetCapturesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Captures.CaptureDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Captures.CaptureDetails.GetCaptures(request.EventStore, storage);
                return result.Select(ToCaptureDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Captures", "GetCaptures"));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Captures.CaptureDetailsResponse>>> ObserveCaptures(global::Cratis.Chronicle.Contracts.Captures.ObserveCapturesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Captures.CaptureDetailsResponse>>(
            () => global::Cratis.Chronicle.Captures.CaptureDetails.ObserveCaptures(request.EventStore, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.Captures.CaptureDetailsResponse>)_.Select(ToCaptureDetailsResponse).ToList()),
            exception => logger.QueryFailed(exception, "Captures", "ObserveCaptures"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Captures.CapturedEventResponse>>> CapturedEvents(global::Cratis.Chronicle.Contracts.Captures.CapturedEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Captures.CapturedEventResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Captures.CapturedEvent.CapturedEvents(request.EventStore, request.CaptureName, request.Namespace, request.MaxEvents, storage, request.JsonSerializerOptions);
                return result.Select(ToCapturedEventResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Captures", "CapturedEvents"));

    static global::Cratis.Chronicle.Contracts.Captures.SaveCaptureResponse ToSaveCaptureResponse(global::Cratis.Chronicle.Captures.SaveCaptureResult source) =>
        new()
        {
            Capture = source.Capture is null ? null : ToCaptureDetailsResponse(source.Capture),
            Messages = source.Messages
        };

    static global::Cratis.Chronicle.Contracts.Captures.StartCaptureResponse ToStartCaptureResponse(global::Cratis.Chronicle.Captures.StartCaptureResult source) =>
        new()
        {
            Messages = source.Messages
        };

    static global::Cratis.Chronicle.Contracts.Captures.ValidateCaptureDeclarationResponse ToValidateCaptureDeclarationResponse(global::Cratis.Chronicle.Captures.ValidateCaptureDeclarationResult source) =>
        new()
        {
            Messages = source.Messages
        };

    static global::Cratis.Chronicle.Contracts.Captures.CaptureDetailsResponse ToCaptureDetailsResponse(global::Cratis.Chronicle.Captures.CaptureDetails source) =>
        new()
        {
            Id = source.Id,
            Name = source.Name,
            Declaration = source.Declaration,
            Status = source.Status
        };

    static global::Cratis.Chronicle.Contracts.Captures.CapturedEventResponse ToCapturedEventResponse(global::Cratis.Chronicle.Captures.CapturedEvent source) =>
        new()
        {
            Id = source.Id,
            Context = source.Context,
            Content = source.Content
        };
}
