/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

export enum AddressFamily {
    unknown = -1,
    unspecified = 0,
    unix = 1,
    interNetwork = 2,
    impLink = 3,
    pup = 4,
    chaos = 5,
    ipx = 6,
    nS = 6,
    iso = 7,
    osi = 7,
    ecma = 8,
    dataKit = 9,
    ccitt = 10,
    sna = 11,
    decNet = 12,
    dataLink = 13,
    lat = 14,
    hyperChannel = 15,
    appleTalk = 16,
    netBios = 17,
    voiceView = 18,
    fireFox = 19,
    banyan = 21,
    atm = 22,
    interNetworkV6 = 23,
    cluster = 24,
    ieee12844 = 25,
    irda = 26,
    networkDesigners = 28,
    max = 29,
    packet = 65536,
    controllerAreaNetwork = 65537,
}
