// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.ExternalServices;
/// <summary>
/// Defines the gRPC service contract for ExternalServices.
/// </summary>
[Service]
public interface IExternalServices
{
    /// <summary>
    /// Executes the AddExternalService command.
    /// </summary>
    /// <param name = "request">The AddExternalService request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> AddExternalService(AddExternalServiceRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AddExternalServices command.
    /// </summary>
    /// <param name = "request">The AddExternalServices request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> AddExternalServices(AddExternalServicesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RemoveExternalService command.
    /// </summary>
    /// <param name = "request">The RemoveExternalService request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RemoveExternalService(RemoveExternalServiceRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RemoveExternalServices command.
    /// </summary>
    /// <param name = "request">The RemoveExternalServices request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RemoveExternalServices(RemoveExternalServicesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GetExternalServices query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<ExternalServiceResponse>>> GetExternalServices(GetExternalServicesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ObserveExternalServices query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<QueryResult<IEnumerable<ExternalServiceResponse>>> ObserveExternalServices(ObserveExternalServicesRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the AddExternalServiceRequest message.
/// </summary>
[ProtoContract]
public class AddExternalServiceRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(2)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(3)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the EndpointType.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType EndpointType { get; set; }

    /// <summary>
    /// Gets or sets the Url.
    /// </summary>
    [ProtoMember(5)]
    public string Url { get; set; }

    /// <summary>
    /// Gets or sets the AuthorizationType.
    /// </summary>
    [ProtoMember(6)]
    public global::Cratis.Chronicle.Contracts.Security.AuthorizationType AuthorizationType { get; set; }

    /// <summary>
    /// Gets or sets the BasicUsername.
    /// </summary>
    [ProtoMember(7)]
    public string BasicUsername { get; set; }

    /// <summary>
    /// Gets or sets the BasicPassword.
    /// </summary>
    [ProtoMember(8)]
    public string BasicPassword { get; set; }

    /// <summary>
    /// Gets or sets the BearerToken.
    /// </summary>
    [ProtoMember(9)]
    public string BearerToken { get; set; }

    /// <summary>
    /// Gets or sets the OAuthAuthority.
    /// </summary>
    [ProtoMember(10)]
    public string OAuthAuthority { get; set; }

    /// <summary>
    /// Gets or sets the OAuthClientId.
    /// </summary>
    [ProtoMember(11)]
    public string OAuthClientId { get; set; }

    /// <summary>
    /// Gets or sets the OAuthClientSecret.
    /// </summary>
    [ProtoMember(12)]
    public string OAuthClientSecret { get; set; }

    /// <summary>
    /// Gets or sets the Headers.
    /// </summary>
    [ProtoMember(13)]
    public global::System.Collections.Generic.IDictionary<string, string> Headers { get; set; }

    /// <summary>
    /// Gets or sets the Host.
    /// </summary>
    [ProtoMember(14)]
    public string Host { get; set; }

    /// <summary>
    /// Gets or sets the Port.
    /// </summary>
    [ProtoMember(15)]
    public int Port { get; set; }

    /// <summary>
    /// Gets or sets the Database.
    /// </summary>
    [ProtoMember(16)]
    public string Database { get; set; }

    /// <summary>
    /// Gets or sets the Username.
    /// </summary>
    [ProtoMember(17)]
    public string Username { get; set; }

    /// <summary>
    /// Gets or sets the Password.
    /// </summary>
    [ProtoMember(18)]
    public string Password { get; set; }

    /// <summary>
    /// Gets or sets the Options.
    /// </summary>
    [ProtoMember(19)]
    public global::System.Collections.Generic.IDictionary<string, string> Options { get; set; }
}

/// <summary>
/// Represents the AddExternalServicesRequest message.
/// </summary>
[ProtoContract]
public class AddExternalServicesRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the ExternalServices.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceDefinition> ExternalServices { get; set; }
}

/// <summary>
/// Represents the RemoveExternalServiceRequest message.
/// </summary>
[ProtoContract]
public class RemoveExternalServiceRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the ExternalServiceId.
    /// </summary>
    [ProtoMember(2)]
    public string ExternalServiceId { get; set; }
}

/// <summary>
/// Represents the RemoveExternalServicesRequest message.
/// </summary>
[ProtoContract]
public class RemoveExternalServicesRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the ExternalServices.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<string> ExternalServices { get; set; }
}

/// <summary>
/// Represents the ExternalServiceResponse message.
/// </summary>
[ProtoContract]
public class ExternalServiceResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(2)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the EndpointType.
    /// </summary>
    [ProtoMember(3)]
    public global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceEndpointType EndpointType { get; set; }

    /// <summary>
    /// Gets or sets the Url.
    /// </summary>
    [ProtoMember(4)]
    public string Url { get; set; }

    /// <summary>
    /// Gets or sets the AuthorizationType.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.Security.AuthorizationType AuthorizationType { get; set; }

    /// <summary>
    /// Gets or sets the Headers.
    /// </summary>
    [ProtoMember(6)]
    public global::System.Collections.Generic.IDictionary<string, string> Headers { get; set; }

    /// <summary>
    /// Gets or sets the Host.
    /// </summary>
    [ProtoMember(7)]
    public string Host { get; set; }

    /// <summary>
    /// Gets or sets the Port.
    /// </summary>
    [ProtoMember(8)]
    public int Port { get; set; }

    /// <summary>
    /// Gets or sets the Database.
    /// </summary>
    [ProtoMember(9)]
    public string Database { get; set; }

    /// <summary>
    /// Gets or sets the Username.
    /// </summary>
    [ProtoMember(10)]
    public string Username { get; set; }

    /// <summary>
    /// Gets or sets the Options.
    /// </summary>
    [ProtoMember(11)]
    public global::System.Collections.Generic.IDictionary<string, string> Options { get; set; }
}

/// <summary>
/// Represents the GetExternalServicesRequest message.
/// </summary>
[ProtoContract]
public class GetExternalServicesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}

/// <summary>
/// Represents the ObserveExternalServicesRequest message.
/// </summary>
[ProtoContract]
public class ObserveExternalServicesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}