// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Jobs;
/// <summary>
/// Defines the gRPC service contract for Jobs.
/// </summary>
[Service]
public interface IJobs
{
    /// <summary>
    /// Executes the DeleteJob command.
    /// </summary>
    /// <param name = "request">The DeleteJob request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task DeleteJob(DeleteJobRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ResumeJob command.
    /// </summary>
    /// <param name = "request">The ResumeJob request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task ResumeJob(ResumeJobRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the StopJob command.
    /// </summary>
    /// <param name = "request">The StopJob request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task StopJob(StopJobRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllJobs query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<IEnumerable<JobSummaryResponse>> AllJobs(AllJobsRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the DeleteJobRequest message.
/// </summary>
[ProtoContract]
public class DeleteJobRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the JobId.
    /// </summary>
    [ProtoMember(3)]
    public Guid JobId { get; set; }
}

/// <summary>
/// Represents the ResumeJobRequest message.
/// </summary>
[ProtoContract]
public class ResumeJobRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the JobId.
    /// </summary>
    [ProtoMember(3)]
    public Guid JobId { get; set; }
}

/// <summary>
/// Represents the StopJobRequest message.
/// </summary>
[ProtoContract]
public class StopJobRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the JobId.
    /// </summary>
    [ProtoMember(3)]
    public Guid JobId { get; set; }
}

/// <summary>
/// Represents the JobSummaryResponse message.
/// </summary>
[ProtoContract]
public class JobSummaryResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the Details.
    /// </summary>
    [ProtoMember(2)]
    public string Details { get; set; }

    /// <summary>
    /// Gets or sets the Type.
    /// </summary>
    [ProtoMember(3)]
    public string Type { get; set; }

    /// <summary>
    /// Gets or sets the Status.
    /// </summary>
    [ProtoMember(4)]
    public JobStatus Status { get; set; }

    /// <summary>
    /// Gets or sets the Created.
    /// </summary>
    [ProtoMember(5)]
    public DateTimeOffset Created { get; set; }

    /// <summary>
    /// Gets or sets the StatusChanges.
    /// </summary>
    [ProtoMember(6)]
    public IEnumerable<JobStatusChanged> StatusChanges { get; set; }

    /// <summary>
    /// Gets or sets the Progress.
    /// </summary>
    [ProtoMember(7)]
    public JobProgress Progress { get; set; }
}

/// <summary>
/// Represents the AllJobsRequest message.
/// </summary>
[ProtoContract]
public class AllJobsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}