// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Jobs;
/// <summary>
/// Represents the JobStatus value.
/// </summary>
public enum JobStatus
{
    /// <summary>
    /// Represents the None value.
    /// </summary>
    None = 0,
    /// <summary>
    /// Represents the PreparingJob value.
    /// </summary>
    PreparingJob = 1,
    /// <summary>
    /// Represents the PreparingSteps value.
    /// </summary>
    PreparingSteps = 2,
    /// <summary>
    /// Represents the StartingSteps value.
    /// </summary>
    StartingSteps = 3,
    /// <summary>
    /// Represents the Running value.
    /// </summary>
    Running = 4,
    /// <summary>
    /// Represents the CompletedSuccessfully value.
    /// </summary>
    CompletedSuccessfully = 5,
    /// <summary>
    /// Represents the CompletedWithFailures value.
    /// </summary>
    CompletedWithFailures = 6,
    /// <summary>
    /// Represents the Stopped value.
    /// </summary>
    Stopped = 7,
    /// <summary>
    /// Represents the Failed value.
    /// </summary>
    Failed = 8,
    /// <summary>
    /// Represents the Removing value.
    /// </summary>
    Removing = 9
}