// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.EventSources;
/// <summary>
/// Defines the gRPC service contract for EventSources.
/// </summary>
[Service]
public interface IEventSources
{
    /// <summary>
    /// Executes the RegisterEventSources command.
    /// </summary>
    /// <param name = "request">The RegisterEventSources request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RegisterEventSources(RegisterEventSourcesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllEventSources query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<EventSourceDetailsResponse>>> AllEventSources(AllEventSourcesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ObserveEventSources query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<QueryResult<IEnumerable<EventSourceDetailsResponse>>> ObserveEventSources(ObserveEventSourcesRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the RegisterEventSourcesRequest message.
/// </summary>
[ProtoContract]
public class RegisterEventSourcesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the sources.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.EventSources.EventSourceDefinition> Sources { get; set; } = new List<global::Cratis.Chronicle.Contracts.EventSources.EventSourceDefinition>();
}

/// <summary>
/// Represents the EventSourceDetailsResponse message.
/// </summary>
[ProtoContract]
public class EventSourceDetailsResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(2)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Description.
    /// </summary>
    [ProtoMember(3)]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Owner.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.EventSources.EventSourceOwner Owner { get; set; }

    /// <summary>
    /// Gets or sets the Concurrency.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.EventSources.ConcurrencyDimensions Concurrency { get; set; }

    /// <summary>
    /// Gets or sets the Streams.
    /// </summary>
    [ProtoMember(6)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.EventSources.EventStreamDefinition> Streams { get; set; } = new List<global::Cratis.Chronicle.Contracts.EventSources.EventStreamDefinition>();
}

/// <summary>
/// Represents the AllEventSourcesRequest message.
/// </summary>
[ProtoContract]
public class AllEventSourcesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;
}

/// <summary>
/// Represents the ObserveEventSourcesRequest message.
/// </summary>
[ProtoContract]
public class ObserveEventSourcesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;
}