// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Events;
/// <summary>
/// Represents the EventObservationState value.
/// </summary>
public enum EventObservationState
{
    /// <summary>
    /// Represents the None value.
    /// </summary>
    None = 0,
    /// <summary>
    /// Represents the Initial value.
    /// </summary>
    Initial = 1,
    /// <summary>
    /// Represents the Replay value.
    /// </summary>
    Replay = 2
}