// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.EventTypes;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.EventTypes.IEventTypes"/>.
/// </summary>
internal sealed class EventTypes(
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Cratis.Chronicle.EventTypes.IEventTypesCacheClient eventTypesCacheClient,
    global::Cratis.Chronicle.EventTypes.EventTypeRegistrar eventTypeRegistrar,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.EventTypes.EventTypes> logger) : global::Cratis.Chronicle.Contracts.EventTypes.IEventTypes
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> CreateEventType(global::Cratis.Chronicle.Contracts.EventTypes.CreateEventTypeRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.EventTypes.CreateEventType(request.EventStore, request.Name),
            command => command.Handle(storage, eventTypesCacheClient));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RegisterEventTypes(global::Cratis.Chronicle.Contracts.EventTypes.RegisterEventTypesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.EventTypes.RegisterEventTypes(request.EventStore, request.Types, request.DisableValidation),
            command => command.Handle(storage, eventTypeRegistrar, eventTypesCacheClient));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RegisterSingleEventType(global::Cratis.Chronicle.Contracts.EventTypes.RegisterSingleEventTypeRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.EventTypes.RegisterSingleEventType(request.EventStore, request.Type),
            command => command.Handle(storage, eventTypesCacheClient));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse>>> AllEventTypeGenerations(global::Cratis.Chronicle.Contracts.EventTypes.AllEventTypeGenerationsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.EventTypes.EventTypeDetails.AllEventTypeGenerations(request.EventStore, request.EventTypeId, storage);
                return result.Select(ToEventTypeDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventTypes", "AllEventTypeGenerations"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse>>> AllEventTypes(global::Cratis.Chronicle.Contracts.EventTypes.AllEventTypesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.EventTypes.EventTypeDetails.AllEventTypes(request.EventStore, storage);
                return result.Select(ToEventTypeDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "EventTypes", "AllEventTypes"));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse>>> ObserveEventTypes(global::Cratis.Chronicle.Contracts.EventTypes.ObserveEventTypesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse>>(
            () => global::Cratis.Chronicle.EventTypes.EventTypeDetails.ObserveEventTypes(request.EventStore, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse>)_.Select(ToEventTypeDetailsResponse).ToList()),
            exception => logger.QueryFailed(exception, "EventTypes", "ObserveEventTypes"));

    static global::Cratis.Chronicle.Contracts.EventTypes.EventTypeDetailsResponse ToEventTypeDetailsResponse(global::Cratis.Chronicle.EventTypes.EventTypeDetails source) =>
        new()
        {
            Type = source.Type,
            Owner = source.Owner,
            Source = source.Source,
            Schema = source.Schema
        };
}
