// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Patterns;

namespace Cratis.Chronicle.Services.Patterns;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Patterns.IPatterns"/>.
/// </summary>
internal sealed class Patterns(
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Cratis.Chronicle.Patterns.IFacetVocabulary facetVocabulary,
    global::Cratis.Chronicle.Patterns.IFacetSetGenerator facetSetGenerator,
    global::Cratis.Chronicle.Patterns.IPatternMatcher patternMatcher,
    global::Microsoft.Extensions.Options.IOptions<global::Cratis.Chronicle.Configuration.ChronicleOptions> optionsOfChronicleOptions,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Patterns.Patterns> logger) : global::Cratis.Chronicle.Contracts.Patterns.IPatterns
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>> AllPatterns(global::Cratis.Chronicle.Contracts.Patterns.AllPatternsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Patterns.BehaviorPatternDetails.AllPatterns((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, storage);
                return result.Select(ToBehaviorPatternDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Patterns", "AllPatterns"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>> MatchingPatterns(global::Cratis.Chronicle.Contracts.Patterns.MatchingPatternsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Patterns.BehaviorPatternDetails.MatchingPatterns((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.Patterns.PatternGroupingKey)request.GroupingKey, request.Context, storage, facetVocabulary, facetSetGenerator, patternMatcher, optionsOfChronicleOptions, request.MinimumConfidence, request.MaximumResults);
                return result.Select(ToBehaviorPatternDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Patterns", "MatchingPatterns"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>> PatternsForScope(global::Cratis.Chronicle.Contracts.Patterns.PatternsForScopeRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Patterns.BehaviorPatternDetails.PatternsForScope((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.Patterns.PatternGroupingKey)request.GroupingKey, storage);
                return result.Select(ToBehaviorPatternDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Patterns", "PatternsForScope"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>> UsualActions(global::Cratis.Chronicle.Contracts.Patterns.UsualActionsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Patterns.BehaviorPatternDetails.UsualActions((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.Patterns.PatternGroupingKey)request.GroupingKey, request.Context, storage, facetVocabulary, patternMatcher, optionsOfChronicleOptions, request.MinimumConfidence, request.MaximumResults);
                return result.Select(ToBehaviorPatternDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Patterns", "UsualActions"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.PatternScopeResponse>>> AllPatternScopes(global::Cratis.Chronicle.Contracts.Patterns.AllPatternScopesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Patterns.PatternScopeResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Patterns.PatternScope.AllPatternScopes((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, storage);
                return result.Select(ToPatternScopeResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Patterns", "AllPatternScopes"));

    static global::Cratis.Chronicle.Contracts.Patterns.BehaviorPatternDetailsResponse ToBehaviorPatternDetailsResponse(global::Cratis.Chronicle.Patterns.BehaviorPatternDetails source) =>
        new()
        {
            Id = source.Id,
            GroupingKey = source.GroupingKey,
            Facets = source.Facets,
            Confidence = source.Confidence,
            Support = source.Support,
            Occurrences = source.Occurrences,
            Weight = source.Weight,
            Specificity = source.Specificity,
            FirstSeen = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.FirstSeen,
            LastSeen = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.LastSeen
        };

    static global::Cratis.Chronicle.Contracts.Patterns.PatternScopeResponse ToPatternScopeResponse(global::Cratis.Chronicle.Patterns.PatternScope source) =>
        new()
        {
            Id = source.Id
        };
}
