// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Security;
/// <summary>
/// Defines the gRPC service contract for Applications.
/// </summary>
[Service]
public interface IApplications
{
    /// <summary>
    /// Executes the AddApplication command.
    /// </summary>
    /// <param name = "request">The AddApplication request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task AddApplication(AddApplicationRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ChangeApplicationSecret command.
    /// </summary>
    /// <param name = "request">The ChangeApplicationSecret request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task ChangeApplicationSecret(ChangeApplicationSecretRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RemoveApplication command.
    /// </summary>
    /// <param name = "request">The RemoveApplication request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>A task that represents the asynchronous operation.</returns>
    [Operation]
    Task RemoveApplication(RemoveApplicationRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllApplications query.
    /// </summary>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<IEnumerable<ApplicationResponse>> AllApplications(CallContext callContext = default);
}

/// <summary>
/// Represents the AddApplicationRequest message.
/// </summary>
[ProtoContract]
public class AddApplicationRequest
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the ClientId.
    /// </summary>
    [ProtoMember(2)]
    public string ClientId { get; set; }

    /// <summary>
    /// Gets or sets the ClientSecret.
    /// </summary>
    [ProtoMember(3)]
    public string ClientSecret { get; set; }
}

/// <summary>
/// Represents the ChangeApplicationSecretRequest message.
/// </summary>
[ProtoContract]
public class ChangeApplicationSecretRequest
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the ClientSecret.
    /// </summary>
    [ProtoMember(2)]
    public string ClientSecret { get; set; }
}

/// <summary>
/// Represents the RemoveApplicationRequest message.
/// </summary>
[ProtoContract]
public class RemoveApplicationRequest
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public Guid Id { get; set; }
}

/// <summary>
/// Represents the ApplicationResponse message.
/// </summary>
[ProtoContract]
public class ApplicationResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the ClientId.
    /// </summary>
    [ProtoMember(2)]
    public string ClientId { get; set; }

    /// <summary>
    /// Gets or sets the IsActive.
    /// </summary>
    [ProtoMember(3)]
    public bool IsActive { get; set; }

    /// <summary>
    /// Gets or sets the CreatedAt.
    /// </summary>
    [ProtoMember(4)]
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>
    /// Gets or sets the LastModifiedAt.
    /// </summary>
    [ProtoMember(5)]
    public DateTimeOffset? LastModifiedAt { get; set; }
}