// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.Security;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Security.IApplications"/>.
/// </summary>
internal sealed class Applications(
    global::Orleans.IGrainFactory grainFactory,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Security.Applications> logger) : global::Cratis.Chronicle.Contracts.Security.IApplications
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AddApplication(global::Cratis.Chronicle.Contracts.Security.AddApplicationRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Security.AddApplication(request.Id, request.ClientId, request.ClientSecret),
            command => command.Handle(grainFactory, storage));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> ChangeApplicationSecret(global::Cratis.Chronicle.Contracts.Security.ChangeApplicationSecretRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Security.ChangeApplicationSecret(request.Id, request.ClientSecret),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RemoveApplication(global::Cratis.Chronicle.Contracts.Security.RemoveApplicationRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Security.RemoveApplication(request.Id),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Security.ApplicationResponse>>> AllApplications(global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Security.ApplicationResponse>>(
            () => global::Cratis.Chronicle.Security.Application.AllApplications(storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.Security.ApplicationResponse>)_.Select(ToApplicationResponse).ToList()),
            exception => logger.QueryFailed(exception, "Applications", "AllApplications"));

    static global::Cratis.Chronicle.Contracts.Security.ApplicationResponse ToApplicationResponse(global::Cratis.Chronicle.Security.Application source) =>
        new()
        {
            Id = source.Id,
            ClientId = source.ClientId,
            IsActive = source.IsActive,
            CreatedAt = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.CreatedAt,
            LastModifiedAt = source.LastModifiedAt is null ? null : (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset?)source.LastModifiedAt
        };
}
