// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Identities;
using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.Identities;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Identities.IIdentities"/>.
/// </summary>
internal sealed class Identities(
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Identities.Identities> logger) : global::Cratis.Chronicle.Contracts.Identities.IIdentities
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RenameIdentity(global::Cratis.Chronicle.Contracts.Identities.RenameIdentityRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Identities.RenameIdentity(request.EventStore, request.Namespace, request.Subject, request.Name),
            command => command.Handle(storage));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse>>> AllIdentities(global::Cratis.Chronicle.Contracts.Identities.AllIdentitiesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse>>(
            () => global::Cratis.Chronicle.Identities.IdentityDetails.AllIdentities(request.EventStore, request.Namespace, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse>)_.Select(ToIdentityDetailsResponse).ToList()),
            exception => logger.QueryFailed(exception, "Identities", "AllIdentities"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse>>> GetIdentities(global::Cratis.Chronicle.Contracts.Identities.GetIdentitiesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Identities.IdentityDetails.GetIdentities(request.EventStore, request.Namespace, storage);
                return result.Select(ToIdentityDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Identities", "GetIdentities"));

    static global::Cratis.Chronicle.Contracts.Identities.IdentityDetailsResponse ToIdentityDetailsResponse(global::Cratis.Chronicle.Identities.IdentityDetails source) =>
        new()
        {
            Id = source.Id,
            Subject = source.Subject,
            Name = source.Name,
            UserName = source.UserName,
            OnBehalfOf = source.OnBehalfOf
        };
}
