// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Chronicle.Compatibility.for_WireContractReader.when_reading_the_shipped_descriptor_set;

/// <summary>
/// The descriptor set is generated by the build and embedded in the contracts package, and every client hands the
/// server its own copy on connect. Nothing else in the system would notice if that resource stopped being embedded,
/// stopped parsing, or started describing something other than the contracts - the check would simply pass on an
/// empty contract, which is the failure mode that reads as success.
/// </summary>
public class and_it_is_the_one_embedded_in_the_contracts : Specification
{
    WireContract _result;

    void Because() => _result = WireContractReader.Read(Contracts.WireContractDescriptorSet.Bytes);

    [Fact] void should_describe_the_services() => _result.Services.ShouldNotBeEmpty();
    [Fact] void should_describe_the_messages() => _result.Messages.ShouldNotBeEmpty();

    [Fact]
    void should_carry_the_connection_service_every_client_starts_with() =>
        _result.Services.Keys.ShouldContain(".Cratis.Chronicle.Contracts.Clients.ConnectionService");

    [Fact]
    void should_carry_the_method_the_compatibility_check_itself_calls() =>
        _result.Services[".Cratis.Chronicle.Contracts.Clients.ConnectionService"].Methods.Keys
            .ShouldContain(nameof(Contracts.Clients.IConnectionService.CheckCompatibility));

    [Fact]
    void should_carry_the_request_the_client_sends() =>
        _result.Messages.Keys.ShouldContain(".Cratis.Chronicle.Contracts.Clients.CompatibilityRequest");

    [Fact]
    void should_serve_itself() =>
        WireCompatibilityChecker.Check(_result, _result).IsCompatible.ShouldBeTrue();
}
