// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Seeding;

namespace Cratis.Chronicle.Services.Seeding;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Seeding.IEventSeeding"/>.
/// </summary>
internal sealed class EventSeeding(
    global::Cratis.Arc.Commands.ICommandPipeline commandPipeline,
    global::Orleans.IGrainFactory grainFactory,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Seeding.EventSeeding> logger) : global::Cratis.Chronicle.Contracts.Seeding.IEventSeeding
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AddSeedEntry(global::Cratis.Chronicle.Contracts.Seeding.AddSeedEntryRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Seeding.AddSeedEntry((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.Events.EventSourceId)request.EventSourceId, (global::Cratis.Chronicle.Concepts.Events.EventTypeId)request.EventTypeId, request.Content, request.IsGlobal));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> SeedEvents(global::Cratis.Chronicle.Contracts.Seeding.SeedEventsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Seeding.SeedEvents((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, request.GlobalByEventType, request.GlobalByEventSource, request.NamespacedEntries));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Seeding.SeedDataResponse>> GetGlobalSeedData(global::Cratis.Chronicle.Contracts.Seeding.GetGlobalSeedDataRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Seeding.SeedDataResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Seeding.SeedData.GetGlobalSeedData((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, grainFactory);
                return ToSeedDataResponse(result);
            },
            exception => logger.QueryFailed(exception, "EventSeeding", "GetGlobalSeedData"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Seeding.SeedDataResponse>> GetNamespaceSeedData(global::Cratis.Chronicle.Contracts.Seeding.GetNamespaceSeedDataRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Seeding.SeedDataResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Seeding.SeedData.GetNamespaceSeedData((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, grainFactory);
                return ToSeedDataResponse(result);
            },
            exception => logger.QueryFailed(exception, "EventSeeding", "GetNamespaceSeedData"));

    static global::Cratis.Chronicle.Contracts.Seeding.SeedDataResponse ToSeedDataResponse(global::Cratis.Chronicle.Seeding.SeedData source) =>
        new()
        {
            ByEventType = source.ByEventType,
            ByEventSource = source.ByEventSource
        };
}
