// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Recommendations;
using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.Recommendations;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Recommendations.IRecommendations"/>.
/// </summary>
internal sealed class Recommendations(
    global::Orleans.IGrainFactory grainFactory,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Recommendations.Recommendations> logger) : global::Cratis.Chronicle.Contracts.Recommendations.IRecommendations
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> IgnoreRecommendation(global::Cratis.Chronicle.Contracts.Recommendations.IgnoreRecommendationRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Recommendations.IgnoreRecommendation(request.EventStore, request.Namespace, request.RecommendationId),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> PerformRecommendation(global::Cratis.Chronicle.Contracts.Recommendations.PerformRecommendationRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Recommendations.PerformRecommendation(request.EventStore, request.Namespace, request.RecommendationId),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Recommendations.RecommendationDetailsResponse>>> AllRecommendations(global::Cratis.Chronicle.Contracts.Recommendations.AllRecommendationsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Recommendations.RecommendationDetailsResponse>>(
            () => global::Cratis.Chronicle.Recommendations.RecommendationDetails.AllRecommendations(request.EventStore, request.Namespace, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.Recommendations.RecommendationDetailsResponse>)_.Select(ToRecommendationDetailsResponse).ToList()),
            exception => logger.QueryFailed(exception, "Recommendations", "AllRecommendations"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Recommendations.RecommendationDetailsResponse>>> GetRecommendations(global::Cratis.Chronicle.Contracts.Recommendations.GetRecommendationsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Recommendations.RecommendationDetailsResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Recommendations.RecommendationDetails.GetRecommendations(request.EventStore, request.Namespace, storage);
                return result.Select(ToRecommendationDetailsResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Recommendations", "GetRecommendations"));

    static global::Cratis.Chronicle.Contracts.Recommendations.RecommendationDetailsResponse ToRecommendationDetailsResponse(global::Cratis.Chronicle.Recommendations.RecommendationDetails source) =>
        new()
        {
            Id = source.Id,
            Name = source.Name,
            Description = source.Description,
            Type = source.Type,
            Occurred = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.Occurred
        };
}
