// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Seeding;
/// <summary>
/// Defines the gRPC service contract for EventSeeding.
/// </summary>
[Service]
public interface IEventSeeding
{
    /// <summary>
    /// Executes the AddSeedEntry command.
    /// </summary>
    /// <param name = "request">The AddSeedEntry request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> AddSeedEntry(AddSeedEntryRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the SeedEvents command.
    /// </summary>
    /// <param name = "request">The SeedEvents request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> SeedEvents(SeedEventsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GetGlobalSeedData query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<SeedDataResponse>> GetGlobalSeedData(GetGlobalSeedDataRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GetNamespaceSeedData query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<SeedDataResponse>> GetNamespaceSeedData(GetNamespaceSeedDataRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the AddSeedEntryRequest message.
/// </summary>
[ProtoContract]
public class AddSeedEntryRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the EventTypeId.
    /// </summary>
    [ProtoMember(4)]
    public string EventTypeId { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(5)]
    public string Content { get; set; }

    /// <summary>
    /// Gets or sets the IsGlobal.
    /// </summary>
    [ProtoMember(6)]
    public bool IsGlobal { get; set; }
}

/// <summary>
/// Represents the SeedEventsRequest message.
/// </summary>
[ProtoContract]
public class SeedEventsRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the GlobalByEventType.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Seeding.EventTypeSeedEntries> GlobalByEventType { get; set; } = new List<global::Cratis.Chronicle.Contracts.Seeding.EventTypeSeedEntries>();

    /// <summary>
    /// Gets or sets the GlobalByEventSource.
    /// </summary>
    [ProtoMember(3)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Seeding.EventSourceSeedEntries> GlobalByEventSource { get; set; } = new List<global::Cratis.Chronicle.Contracts.Seeding.EventSourceSeedEntries>();

    /// <summary>
    /// Gets or sets the NamespacedEntries.
    /// </summary>
    [ProtoMember(4)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Seeding.NamespacedSeedEntries> NamespacedEntries { get; set; } = new List<global::Cratis.Chronicle.Contracts.Seeding.NamespacedSeedEntries>();
}

/// <summary>
/// Represents the SeedDataResponse message.
/// </summary>
[ProtoContract]
public class SeedDataResponse
{
    /// <summary>
    /// Gets or sets the ByEventType.
    /// </summary>
    [ProtoMember(1)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Seeding.EventTypeSeedEntries> ByEventType { get; set; } = new List<global::Cratis.Chronicle.Contracts.Seeding.EventTypeSeedEntries>();

    /// <summary>
    /// Gets or sets the ByEventSource.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Seeding.EventSourceSeedEntries> ByEventSource { get; set; } = new List<global::Cratis.Chronicle.Contracts.Seeding.EventSourceSeedEntries>();
}

/// <summary>
/// Represents the GetGlobalSeedDataRequest message.
/// </summary>
[ProtoContract]
public class GetGlobalSeedDataRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}

/// <summary>
/// Represents the GetNamespaceSeedDataRequest message.
/// </summary>
[ProtoContract]
public class GetNamespaceSeedDataRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}