// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Recommendations;
/// <summary>
/// Defines the gRPC service contract for Recommendations.
/// </summary>
[Service]
public interface IRecommendations
{
    /// <summary>
    /// Executes the IgnoreRecommendation command.
    /// </summary>
    /// <param name = "request">The IgnoreRecommendation request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> IgnoreRecommendation(IgnoreRecommendationRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the PerformRecommendation command.
    /// </summary>
    /// <param name = "request">The PerformRecommendation request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> PerformRecommendation(PerformRecommendationRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GetRecommendations query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<RecommendationDetailsResponse>>> GetRecommendations(GetRecommendationsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllRecommendations query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<QueryResult<IEnumerable<RecommendationDetailsResponse>>> AllRecommendations(AllRecommendationsRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the IgnoreRecommendationRequest message.
/// </summary>
[ProtoContract]
public class IgnoreRecommendationRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the RecommendationId.
    /// </summary>
    [ProtoMember(3)]
    public Guid RecommendationId { get; set; }
}

/// <summary>
/// Represents the PerformRecommendationRequest message.
/// </summary>
[ProtoContract]
public class PerformRecommendationRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the RecommendationId.
    /// </summary>
    [ProtoMember(3)]
    public Guid RecommendationId { get; set; }
}

/// <summary>
/// Represents the RecommendationDetailsResponse message.
/// </summary>
[ProtoContract]
public class RecommendationDetailsResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(2)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the Description.
    /// </summary>
    [ProtoMember(3)]
    public string Description { get; set; }

    /// <summary>
    /// Gets or sets the Type.
    /// </summary>
    [ProtoMember(4)]
    public string Type { get; set; }

    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(5)]
    public SerializableDateTimeOffset Occurred { get; set; }
}

/// <summary>
/// Represents the GetRecommendationsRequest message.
/// </summary>
[ProtoContract]
public class GetRecommendationsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}

/// <summary>
/// Represents the AllRecommendationsRequest message.
/// </summary>
[ProtoContract]
public class AllRecommendationsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}