// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Observation.Webhooks;
/// <summary>
/// Defines the gRPC service contract for Webhooks.
/// </summary>
[Service]
public interface IWebhooks
{
    /// <summary>
    /// Executes the AddWebhook command.
    /// </summary>
    /// <param name = "request">The AddWebhook request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> AddWebhook(AddWebhookRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AddWebhooks command.
    /// </summary>
    /// <param name = "request">The AddWebhooks request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> AddWebhooks(AddWebhooksRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RemoveWebhook command.
    /// </summary>
    /// <param name = "request">The RemoveWebhook request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RemoveWebhook(RemoveWebhookRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RemoveWebhooks command.
    /// </summary>
    /// <param name = "request">The RemoveWebhooks request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RemoveWebhooks(RemoveWebhooksRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GetWebhooks query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<WebhookDetailsResponse>>> GetWebhooks(GetWebhooksRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ObserveWebhooks query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<QueryResult<IEnumerable<WebhookDetailsResponse>>> ObserveWebhooks(ObserveWebhooksRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the AddWebhookRequest message.
/// </summary>
[ProtoContract]
public class AddWebhookRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(2)]
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets the Url.
    /// </summary>
    [ProtoMember(3)]
    public string Url { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the EventTypes.
    /// </summary>
    [ProtoMember(5)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Events.EventType> EventTypes { get; set; }

    /// <summary>
    /// Gets or sets the AuthorizationType.
    /// </summary>
    [ProtoMember(6)]
    public global::Cratis.Chronicle.Contracts.Security.AuthorizationType AuthorizationType { get; set; }

    /// <summary>
    /// Gets or sets the BasicUsername.
    /// </summary>
    [ProtoMember(7)]
    public string BasicUsername { get; set; }

    /// <summary>
    /// Gets or sets the BasicPassword.
    /// </summary>
    [ProtoMember(8)]
    public string BasicPassword { get; set; }

    /// <summary>
    /// Gets or sets the BearerToken.
    /// </summary>
    [ProtoMember(9)]
    public string BearerToken { get; set; }

    /// <summary>
    /// Gets or sets the OAuthAuthority.
    /// </summary>
    [ProtoMember(10)]
    public string OAuthAuthority { get; set; }

    /// <summary>
    /// Gets or sets the OAuthClientId.
    /// </summary>
    [ProtoMember(11)]
    public string OAuthClientId { get; set; }

    /// <summary>
    /// Gets or sets the OAuthClientSecret.
    /// </summary>
    [ProtoMember(12)]
    public string OAuthClientSecret { get; set; }

    /// <summary>
    /// Gets or sets the Headers.
    /// </summary>
    [ProtoMember(13)]
    public global::System.Collections.Generic.IDictionary<string, string> Headers { get; set; }

    /// <summary>
    /// Gets or sets the IsReplayable.
    /// </summary>
    [ProtoMember(14)]
    public bool IsReplayable { get; set; }

    /// <summary>
    /// Gets or sets the IsActive.
    /// </summary>
    [ProtoMember(15)]
    public bool IsActive { get; set; }
}

/// <summary>
/// Represents the AddWebhooksRequest message.
/// </summary>
[ProtoContract]
public class AddWebhooksRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Webhooks.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Observation.Webhooks.WebhookDefinition> Webhooks { get; set; }
}

/// <summary>
/// Represents the RemoveWebhookRequest message.
/// </summary>
[ProtoContract]
public class RemoveWebhookRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the WebhookId.
    /// </summary>
    [ProtoMember(2)]
    public string WebhookId { get; set; }
}

/// <summary>
/// Represents the RemoveWebhooksRequest message.
/// </summary>
[ProtoContract]
public class RemoveWebhooksRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Webhooks.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<string> Webhooks { get; set; }
}

/// <summary>
/// Represents the WebhookDetailsResponse message.
/// </summary>
[ProtoContract]
public class WebhookDetailsResponse
{
    /// <summary>
    /// Gets or sets the Identifier.
    /// </summary>
    [ProtoMember(1)]
    public string Identifier { get; set; }

    /// <summary>
    /// Gets or sets the Url.
    /// </summary>
    [ProtoMember(2)]
    public string Url { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the EventTypes.
    /// </summary>
    [ProtoMember(4)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Events.EventType> EventTypes { get; set; }

    /// <summary>
    /// Gets or sets the AuthorizationType.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.Security.AuthorizationType AuthorizationType { get; set; }

    /// <summary>
    /// Gets or sets the Headers.
    /// </summary>
    [ProtoMember(6)]
    public global::System.Collections.Generic.IDictionary<string, string> Headers { get; set; }

    /// <summary>
    /// Gets or sets the IsReplayable.
    /// </summary>
    [ProtoMember(7)]
    public bool IsReplayable { get; set; }

    /// <summary>
    /// Gets or sets the IsActive.
    /// </summary>
    [ProtoMember(8)]
    public bool IsActive { get; set; }
}

/// <summary>
/// Represents the GetWebhooksRequest message.
/// </summary>
[ProtoContract]
public class GetWebhooksRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}

/// <summary>
/// Represents the ObserveWebhooksRequest message.
/// </summary>
[ProtoContract]
public class ObserveWebhooksRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}