// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the CompleteStreamError value.
/// </summary>
public enum CompleteStreamError
{
    /// <summary>
    /// Represents the None value.
    /// </summary>
    None = 0,
    /// <summary>
    /// Represents the AlreadyCompleted value.
    /// </summary>
    AlreadyCompleted = 1,
    /// <summary>
    /// Represents the DefaultStreamCannotBeCompleted value.
    /// </summary>
    DefaultStreamCannotBeCompleted = 2
}