// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the ConcurrencyScope message.
/// </summary>
[ProtoContract]
public class ConcurrencyScope
{
    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(1)]
    public global::System.UInt64 SequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(2)]
    public bool EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamType.
    /// </summary>
    [ProtoMember(3)]
    public string? EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamId.
    /// </summary>
    [ProtoMember(4)]
    public string? EventStreamId { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceType.
    /// </summary>
    [ProtoMember(5)]
    public string? EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the EventTypes.
    /// </summary>
    [ProtoMember(6)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventType>? EventTypes { get; set; }

    /// <summary>
    /// Gets or sets the ExpectsNoMatchingEvent.
    /// </summary>
    [ProtoMember(7)]
    public bool ExpectsNoMatchingEvent { get; set; }
}