// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the ContentVerificationResult value.
/// </summary>
public enum ContentVerificationResult
{
    /// <summary>
    /// Represents the Unavailable value.
    /// </summary>
    Unavailable = 0,
    /// <summary>
    /// Represents the Equal value.
    /// </summary>
    Equal = 1,
    /// <summary>
    /// Represents the Different value.
    /// </summary>
    Different = 2
}