// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the EventToAppend message.
/// </summary>
[ProtoContract]
public class EventToAppend
{
    /// <summary>
    /// Gets or sets the EventType.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Sequences.EventType EventType { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(2)]
    public global::System.Text.Json.Nodes.JsonObject Content { get; set; }

    /// <summary>
    /// Gets or sets the Subject.
    /// </summary>
    [ProtoMember(3)]
    public string? Subject { get; set; }
}