// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the EventForEventSourceId message.
/// </summary>
[ProtoContract]
public class EventForEventSourceId
{
    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(1)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceType.
    /// </summary>
    [ProtoMember(2)]
    public string EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamType.
    /// </summary>
    [ProtoMember(3)]
    public string EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamId.
    /// </summary>
    [ProtoMember(4)]
    public string EventStreamId { get; set; }

    /// <summary>
    /// Gets or sets the EventType.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.Sequences.EventType EventType { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(6)]
    public global::System.Text.Json.Nodes.JsonObject Content { get; set; }

    /// <summary>
    /// Gets or sets the Tags.
    /// </summary>
    [ProtoMember(7)]
    public IEnumerable<string>? Tags { get; set; }

    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(8)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Occurred { get; set; }

    /// <summary>
    /// Gets or sets the Subject.
    /// </summary>
    [ProtoMember(9)]
    public string? Subject { get; set; }
}