// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the EventRevision message.
/// </summary>
[ProtoContract]
public class EventRevision
{
    /// <summary>
    /// Gets or sets the Generation.
    /// </summary>
    [ProtoMember(1)]
    public global::System.UInt32 Generation { get; set; }

    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(2)]
    public string CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(3)]
    public global::Cratis.Chronicle.Contracts.Sequences.Identity CausedBy { get; set; }

    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Occurred { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(5)]
    public string Content { get; set; }
}