// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the EventType message.
/// </summary>
[ProtoContract]
public class EventType
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the Generation.
    /// </summary>
    [ProtoMember(2)]
    public global::System.UInt32 Generation { get; set; }

    /// <summary>
    /// Gets or sets the Tombstone.
    /// </summary>
    [ProtoMember(3)]
    public bool Tombstone { get; set; }
}