// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the EventSourceConcurrencyScope message.
/// </summary>
[ProtoContract]
public class EventSourceConcurrencyScope
{
    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(1)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the Scope.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Sequences.ConcurrencyScope Scope { get; set; }
}