// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Defines the gRPC service contract for EventSequences.
/// </summary>
[Service]
public interface IEventSequences
{
    /// <summary>
    /// Executes the Append command.
    /// </summary>
    /// <param name = "request">The Append request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult<AppendResponse>> Append(AppendRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AppendMany command.
    /// </summary>
    /// <param name = "request">The AppendMany request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult<AppendManyResponse>> AppendMany(AppendManyRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AppendManyForEventSources command.
    /// </summary>
    /// <param name = "request">The AppendManyForEventSources request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult<AppendManyResponse>> AppendManyForEventSources(AppendManyForEventSourcesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the CompleteStream command.
    /// </summary>
    /// <param name = "request">The CompleteStream request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult<CompleteStreamResponse>> CompleteStream(CompleteStreamRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the Redact command.
    /// </summary>
    /// <param name = "request">The Redact request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> Redact(RedactRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RedactForEventSource command.
    /// </summary>
    /// <param name = "request">The RedactForEventSource request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RedactForEventSource(RedactForEventSourceRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the Revise command.
    /// </summary>
    /// <param name = "request">The Revise request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> Revise(ReviseRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the QueryEvents query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<AppendedEventResponse>>> QueryEvents(QueryEventsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AppendedEvents query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<AppendedEventResponse>>> AppendedEvents(AppendedEventsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ForEventSourceIdAndEventTypes query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<AppendedEventResponse>>> ForEventSourceIdAndEventTypes(ForEventSourceIdAndEventTypesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the FromSequenceNumber query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<AppendedEventResponse>>> FromSequenceNumber(FromSequenceNumberRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllEventSequences query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<EventSequenceNamesResponse>>> AllEventSequences(AllEventSequencesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the TailSequenceNumber query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<EventSequenceTailResponse>> TailSequenceNumber(TailSequenceNumberRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the HasEventsForEventSourceId query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<EventSourceEventsResponse>> HasEventsForEventSourceId(HasEventsForEventSourceIdRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ExportEvents query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<ExportedEventResponse>>> ExportEvents(ExportEventsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the SequenceHistogram query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<SequenceHistogramBucketResponse>>> SequenceHistogram(SequenceHistogramRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ParseResolution query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution>> ParseResolution(ParseResolutionRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the EndOf query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset>> EndOf(EndOfRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the AppendRequest message.
/// </summary>
[ProtoContract]
public class AppendRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceType.
    /// </summary>
    [ProtoMember(5)]
    public string EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamType.
    /// </summary>
    [ProtoMember(6)]
    public string EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamId.
    /// </summary>
    [ProtoMember(7)]
    public string EventStreamId { get; set; }

    /// <summary>
    /// Gets or sets the EventType.
    /// </summary>
    [ProtoMember(8)]
    public global::Cratis.Chronicle.Contracts.Sequences.EventType EventType { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(9)]
    public global::System.Text.Json.Nodes.JsonObject Content { get; set; }

    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(10)]
    public Guid? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the Tags.
    /// </summary>
    [ProtoMember(11)]
    public IEnumerable<string>? Tags { get; set; }

    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(12)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Occurred { get; set; }

    /// <summary>
    /// Gets or sets the Subject.
    /// </summary>
    [ProtoMember(13)]
    public string? Subject { get; set; }

    /// <summary>
    /// Gets or sets the Causation.
    /// </summary>
    [ProtoMember(14)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.Causation>? Causation { get; set; }

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(15)]
    public global::Cratis.Chronicle.Contracts.Sequences.Identity? CausedBy { get; set; }

    /// <summary>
    /// Gets or sets the ConcurrencyScope.
    /// </summary>
    [ProtoMember(16)]
    public global::Cratis.Chronicle.Contracts.Sequences.ConcurrencyScope? ConcurrencyScope { get; set; }
}

/// <summary>
/// Represents the AppendResponse message.
/// </summary>
[ProtoContract]
public class AppendResponse
{
    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(1)]
    public Guid CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(2)]
    public global::System.UInt64 SequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the IsSuccess.
    /// </summary>
    [ProtoMember(3)]
    public bool IsSuccess { get; set; }

    /// <summary>
    /// Gets or sets the HasConstraintViolations.
    /// </summary>
    [ProtoMember(4)]
    public bool HasConstraintViolations { get; set; }

    /// <summary>
    /// Gets or sets the HasConcurrencyViolations.
    /// </summary>
    [ProtoMember(5)]
    public bool HasConcurrencyViolations { get; set; }

    /// <summary>
    /// Gets or sets the HasErrors.
    /// </summary>
    [ProtoMember(6)]
    public bool HasErrors { get; set; }

    /// <summary>
    /// Gets or sets the ConcurrencyCheckPerformed.
    /// </summary>
    [ProtoMember(7)]
    public bool ConcurrencyCheckPerformed { get; set; }

    /// <summary>
    /// Gets or sets the ConstraintViolations.
    /// </summary>
    [ProtoMember(8)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Events.Constraints.ConstraintViolation> ConstraintViolations { get; set; } = new List<global::Cratis.Chronicle.Contracts.Events.Constraints.ConstraintViolation>();

    /// <summary>
    /// Gets or sets the Errors.
    /// </summary>
    [ProtoMember(9)]
    public IEnumerable<string> Errors { get; set; } = new List<string>();

    /// <summary>
    /// Gets or sets the ConcurrencyViolation.
    /// </summary>
    [ProtoMember(10)]
    public global::Cratis.Chronicle.Contracts.EventSequences.Concurrency.ConcurrencyViolation? ConcurrencyViolation { get; set; }
}

/// <summary>
/// Represents the AppendManyRequest message.
/// </summary>
[ProtoContract]
public class AppendManyRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the Events.
    /// </summary>
    [ProtoMember(5)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventToAppend> Events { get; set; } = new List<global::Cratis.Chronicle.Contracts.Sequences.EventToAppend>();

    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(6)]
    public Guid? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the Tags.
    /// </summary>
    [ProtoMember(7)]
    public IEnumerable<string>? Tags { get; set; }

    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(11)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Occurred { get; set; }

    /// <summary>
    /// Gets or sets the Causation.
    /// </summary>
    [ProtoMember(8)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.Causation>? Causation { get; set; }

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(9)]
    public global::Cratis.Chronicle.Contracts.Sequences.Identity? CausedBy { get; set; }

    /// <summary>
    /// Gets or sets the ConcurrencyScope.
    /// </summary>
    [ProtoMember(10)]
    public global::Cratis.Chronicle.Contracts.Sequences.ConcurrencyScope? ConcurrencyScope { get; set; }
}

/// <summary>
/// Represents the AppendManyResponse message.
/// </summary>
[ProtoContract]
public class AppendManyResponse
{
    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(1)]
    public Guid CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the SequenceNumbers.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::System.UInt64> SequenceNumbers { get; set; } = new List<global::System.UInt64>();

    /// <summary>
    /// Gets or sets the IsSuccess.
    /// </summary>
    [ProtoMember(3)]
    public bool IsSuccess { get; set; }

    /// <summary>
    /// Gets or sets the HasConstraintViolations.
    /// </summary>
    [ProtoMember(4)]
    public bool HasConstraintViolations { get; set; }

    /// <summary>
    /// Gets or sets the HasConcurrencyViolations.
    /// </summary>
    [ProtoMember(5)]
    public bool HasConcurrencyViolations { get; set; }

    /// <summary>
    /// Gets or sets the HasErrors.
    /// </summary>
    [ProtoMember(6)]
    public bool HasErrors { get; set; }

    /// <summary>
    /// Gets or sets the ConcurrencyCheckPerformed.
    /// </summary>
    [ProtoMember(7)]
    public bool ConcurrencyCheckPerformed { get; set; }

    /// <summary>
    /// Gets or sets the ConstraintViolations.
    /// </summary>
    [ProtoMember(8)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Events.Constraints.ConstraintViolation> ConstraintViolations { get; set; } = new List<global::Cratis.Chronicle.Contracts.Events.Constraints.ConstraintViolation>();

    /// <summary>
    /// Gets or sets the Errors.
    /// </summary>
    [ProtoMember(9)]
    public IEnumerable<string> Errors { get; set; } = new List<string>();

    /// <summary>
    /// Gets or sets the ConcurrencyViolations.
    /// </summary>
    [ProtoMember(10)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.EventSequences.Concurrency.ConcurrencyViolation> ConcurrencyViolations { get; set; } = new List<global::Cratis.Chronicle.Contracts.EventSequences.Concurrency.ConcurrencyViolation>();
}

/// <summary>
/// Represents the AppendManyForEventSourcesRequest message.
/// </summary>
[ProtoContract]
public class AppendManyForEventSourcesRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the Events.
    /// </summary>
    [ProtoMember(4)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventForEventSourceId> Events { get; set; } = new List<global::Cratis.Chronicle.Contracts.Sequences.EventForEventSourceId>();

    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(5)]
    public Guid? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the Tags.
    /// </summary>
    [ProtoMember(6)]
    public IEnumerable<string>? Tags { get; set; }

    /// <summary>
    /// Gets or sets the Causation.
    /// </summary>
    [ProtoMember(7)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.Causation>? Causation { get; set; }

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(8)]
    public global::Cratis.Chronicle.Contracts.Sequences.Identity? CausedBy { get; set; }

    /// <summary>
    /// Gets or sets the ConcurrencyScopes.
    /// </summary>
    [ProtoMember(9)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventSourceConcurrencyScope>? ConcurrencyScopes { get; set; }
}

/// <summary>
/// Represents the CompleteStreamRequest message.
/// </summary>
[ProtoContract]
public class CompleteStreamRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamType.
    /// </summary>
    [ProtoMember(4)]
    public string EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamId.
    /// </summary>
    [ProtoMember(5)]
    public string EventStreamId { get; set; }
}

/// <summary>
/// Represents the CompleteStreamResponse message.
/// </summary>
[ProtoContract]
public class CompleteStreamResponse
{
    /// <summary>
    /// Gets or sets the IsSuccess.
    /// </summary>
    [ProtoMember(1)]
    public bool IsSuccess { get; set; }

    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(2)]
    public global::System.UInt64 SequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the Error.
    /// </summary>
    [ProtoMember(3)]
    public global::Cratis.Chronicle.Contracts.Sequences.CompleteStreamError Error { get; set; }
}

/// <summary>
/// Represents the RedactRequest message.
/// </summary>
[ProtoContract]
public class RedactRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(4)]
    public global::System.UInt64 SequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the Reason.
    /// </summary>
    [ProtoMember(5)]
    public string Reason { get; set; }

    /// <summary>
    /// Gets or sets the Causation.
    /// </summary>
    [ProtoMember(6)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.Causation>? Causation { get; set; }

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(7)]
    public global::Cratis.Chronicle.Contracts.Sequences.Identity? CausedBy { get; set; }
}

/// <summary>
/// Represents the RedactForEventSourceRequest message.
/// </summary>
[ProtoContract]
public class RedactForEventSourceRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the Reason.
    /// </summary>
    [ProtoMember(5)]
    public string Reason { get; set; }

    /// <summary>
    /// Gets or sets the EventTypes.
    /// </summary>
    [ProtoMember(6)]
    public IEnumerable<string> EventTypes { get; set; } = new List<string>();

    /// <summary>
    /// Gets or sets the Causation.
    /// </summary>
    [ProtoMember(7)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.Causation>? Causation { get; set; }

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(8)]
    public global::Cratis.Chronicle.Contracts.Sequences.Identity? CausedBy { get; set; }
}

/// <summary>
/// Represents the ReviseRequest message.
/// </summary>
[ProtoContract]
public class ReviseRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(4)]
    public global::System.UInt64 SequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the EventType.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.Sequences.EventType EventType { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(6)]
    public global::System.Text.Json.Nodes.JsonObject Content { get; set; }

    /// <summary>
    /// Gets or sets the Causation.
    /// </summary>
    [ProtoMember(7)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.Causation>? Causation { get; set; }

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(8)]
    public global::Cratis.Chronicle.Contracts.Sequences.Identity? CausedBy { get; set; }
}

/// <summary>
/// Represents the AppendedEventResponse message.
/// </summary>
[ProtoContract]
public class AppendedEventResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the Context.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Sequences.EventContext Context { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(3)]
    public string Content { get; set; }

    /// <summary>
    /// Gets or sets the OriginalContent.
    /// </summary>
    [ProtoMember(4)]
    public string OriginalContent { get; set; }

    /// <summary>
    /// Gets or sets the Revisions.
    /// </summary>
    [ProtoMember(5)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Sequences.EventRevision>? Revisions { get; set; }

    /// <summary>
    /// Gets or sets the GenerationalContent.
    /// </summary>
    [ProtoMember(6)]
    public IEnumerable<global::System.Collections.Generic.KeyValuePair<int, string>>? GenerationalContent { get; set; }
}

/// <summary>
/// Represents the QueryEventsRequest message.
/// </summary>
[ProtoContract]
public class QueryEventsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(2)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(3)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(5)]
    public string? EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceType.
    /// </summary>
    [ProtoMember(6)]
    public string? EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamType.
    /// </summary>
    [ProtoMember(7)]
    public string? EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the correlationId.
    /// </summary>
    [ProtoMember(8)]
    public string? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the eventTypeIds.
    /// </summary>
    [ProtoMember(9)]
    public string? EventTypeIds { get; set; }

    /// <summary>
    /// Gets or sets the tags.
    /// </summary>
    [ProtoMember(10)]
    public string? Tags { get; set; }

    /// <summary>
    /// Gets or sets the occurredFrom.
    /// </summary>
    [ProtoMember(11)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset OccurredFrom { get; set; }

    /// <summary>
    /// Gets or sets the occurredTo.
    /// </summary>
    [ProtoMember(12)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset OccurredTo { get; set; }
}

/// <summary>
/// Represents the AppendedEventsRequest message.
/// </summary>
[ProtoContract]
public class AppendedEventsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(2)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(3)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(5)]
    public string? EventSourceId { get; set; }
}

/// <summary>
/// Represents the ForEventSourceIdAndEventTypesRequest message.
/// </summary>
[ProtoContract]
public class ForEventSourceIdAndEventTypesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(2)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(3)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(5)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the eventTypeIds.
    /// </summary>
    [ProtoMember(6)]
    public string? EventTypeIds { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamType.
    /// </summary>
    [ProtoMember(7)]
    public string? EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamId.
    /// </summary>
    [ProtoMember(8)]
    public string? EventStreamId { get; set; }
}

/// <summary>
/// Represents the FromSequenceNumberRequest message.
/// </summary>
[ProtoContract]
public class FromSequenceNumberRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(2)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(3)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the fromEventSequenceNumber.
    /// </summary>
    [ProtoMember(5)]
    public global::System.UInt64 FromEventSequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(6)]
    public string? EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the eventTypeIds.
    /// </summary>
    [ProtoMember(7)]
    public string? EventTypeIds { get; set; }
}

/// <summary>
/// Represents the EventSequenceNamesResponse message.
/// </summary>
[ProtoContract]
public class EventSequenceNamesResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(2)]
    public string Name { get; set; }
}

/// <summary>
/// Represents the AllEventSequencesRequest message.
/// </summary>
[ProtoContract]
public class AllEventSequencesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string? Namespace { get; set; }
}

/// <summary>
/// Represents the EventSequenceTailResponse message.
/// </summary>
[ProtoContract]
public class EventSequenceTailResponse
{
    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(1)]
    public global::System.UInt64 SequenceNumber { get; set; }
}

/// <summary>
/// Represents the TailSequenceNumberRequest message.
/// </summary>
[ProtoContract]
public class TailSequenceNumberRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the eventTypeIds.
    /// </summary>
    [ProtoMember(4)]
    public string? EventTypeIds { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(5)]
    public string? EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceType.
    /// </summary>
    [ProtoMember(6)]
    public string? EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamId.
    /// </summary>
    [ProtoMember(7)]
    public string? EventStreamId { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamType.
    /// </summary>
    [ProtoMember(8)]
    public string? EventStreamType { get; set; }
}

/// <summary>
/// Represents the EventSourceEventsResponse message.
/// </summary>
[ProtoContract]
public class EventSourceEventsResponse
{
    /// <summary>
    /// Gets or sets the HasEvents.
    /// </summary>
    [ProtoMember(1)]
    public bool HasEvents { get; set; }
}

/// <summary>
/// Represents the HasEventsForEventSourceIdRequest message.
/// </summary>
[ProtoContract]
public class HasEventsForEventSourceIdRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSourceId { get; set; }
}

/// <summary>
/// Represents the ExportedEventResponse message.
/// </summary>
[ProtoContract]
public class ExportedEventResponse
{
    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(1)]
    public global::System.UInt64 SequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the EventType.
    /// </summary>
    [ProtoMember(2)]
    public string EventType { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceType.
    /// </summary>
    [ProtoMember(3)]
    public string EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the EventStreamType.
    /// </summary>
    [ProtoMember(5)]
    public string EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(6)]
    public string CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(7)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Occurred { get; set; }

    /// <summary>
    /// Gets or sets the Tags.
    /// </summary>
    [ProtoMember(8)]
    public IEnumerable<string> Tags { get; set; } = new List<string>();

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(9)]
    public string Content { get; set; }
}

/// <summary>
/// Represents the ExportEventsRequest message.
/// </summary>
[ProtoContract]
public class ExportEventsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(2)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(3)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(5)]
    public string? EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceType.
    /// </summary>
    [ProtoMember(6)]
    public string? EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamType.
    /// </summary>
    [ProtoMember(7)]
    public string? EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the correlationId.
    /// </summary>
    [ProtoMember(8)]
    public string? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the eventTypeIds.
    /// </summary>
    [ProtoMember(9)]
    public string? EventTypeIds { get; set; }

    /// <summary>
    /// Gets or sets the tags.
    /// </summary>
    [ProtoMember(10)]
    public string? Tags { get; set; }

    /// <summary>
    /// Gets or sets the occurredFrom.
    /// </summary>
    [ProtoMember(11)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset OccurredFrom { get; set; }

    /// <summary>
    /// Gets or sets the occurredTo.
    /// </summary>
    [ProtoMember(12)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset OccurredTo { get; set; }
}

/// <summary>
/// Represents the SequenceHistogramBucketResponse message.
/// </summary>
[ProtoContract]
public class SequenceHistogramBucketResponse
{
    /// <summary>
    /// Gets or sets the From.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset From { get; set; }

    /// <summary>
    /// Gets or sets the To.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset To { get; set; }

    /// <summary>
    /// Gets or sets the Count.
    /// </summary>
    [ProtoMember(3)]
    public long Count { get; set; }
}

/// <summary>
/// Represents the SequenceHistogramRequest message.
/// </summary>
[ProtoContract]
public class SequenceHistogramRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventSequenceId.
    /// </summary>
    [ProtoMember(3)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the resolution.
    /// </summary>
    [ProtoMember(4)]
    public string? Resolution { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceId.
    /// </summary>
    [ProtoMember(5)]
    public string? EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the eventSourceType.
    /// </summary>
    [ProtoMember(6)]
    public string? EventSourceType { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamType.
    /// </summary>
    [ProtoMember(7)]
    public string? EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the correlationId.
    /// </summary>
    [ProtoMember(8)]
    public string? CorrelationId { get; set; }

    /// <summary>
    /// Gets or sets the eventTypeIds.
    /// </summary>
    [ProtoMember(9)]
    public string? EventTypeIds { get; set; }

    /// <summary>
    /// Gets or sets the tags.
    /// </summary>
    [ProtoMember(10)]
    public string? Tags { get; set; }

    /// <summary>
    /// Gets or sets the occurredFrom.
    /// </summary>
    [ProtoMember(11)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset OccurredFrom { get; set; }

    /// <summary>
    /// Gets or sets the occurredTo.
    /// </summary>
    [ProtoMember(12)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset OccurredTo { get; set; }
}

/// <summary>
/// Represents the ParseResolutionRequest message.
/// </summary>
[ProtoContract]
public class ParseResolutionRequest
{
    /// <summary>
    /// Gets or sets the resolution.
    /// </summary>
    [ProtoMember(1)]
    public string? Resolution { get; set; }
}

/// <summary>
/// Represents the EndOfRequest message.
/// </summary>
[ProtoContract]
public class EndOfRequest
{
    /// <summary>
    /// Gets or sets the start.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Start { get; set; }

    /// <summary>
    /// Gets or sets the resolution.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Storage.EventSequences.HistogramResolution Resolution { get; set; }
}