// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the NamedTagQueryCriterion message.
/// </summary>
[ProtoContract]
public class NamedTagQueryCriterion
{
    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(1)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Values.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<string>? Values { get; set; }

    /// <summary>
    /// Gets or sets the AnyValue.
    /// </summary>
    [ProtoMember(3)]
    public bool AnyValue { get; set; }
}