// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Sequences;
/// <summary>
/// Represents the ResolvedIdentity message.
/// </summary>
[ProtoContract]
public class ResolvedIdentity
{
    /// <summary>
    /// Gets or sets the Subject.
    /// </summary>
    [ProtoMember(1)]
    public string Subject { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(2)]
    public string? Name { get; set; }

    /// <summary>
    /// Gets or sets the UserName.
    /// </summary>
    [ProtoMember(3)]
    public string UserName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Resolution.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.Sequences.IdentityResolution Resolution { get; set; }

    /// <summary>
    /// Gets or sets the OnBehalfOf.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.Sequences.ResolvedIdentity? OnBehalfOf { get; set; }
}