// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Namespaces;
/// <summary>
/// Defines the gRPC service contract for Namespaces.
/// </summary>
[Service]
public interface INamespaces
{
    /// <summary>
    /// Executes the EnsureNamespace command.
    /// </summary>
    /// <param name = "request">The EnsureNamespace request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> EnsureNamespace(EnsureNamespaceRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllNamespaces query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<string>>> AllNamespaces(AllNamespacesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ObserveNamespaces query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<QueryResult<IEnumerable<string>>> ObserveNamespaces(ObserveNamespacesRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the EnsureNamespaceRequest message.
/// </summary>
[ProtoContract]
public class EnsureNamespaceRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}

/// <summary>
/// Represents the AllNamespacesRequest message.
/// </summary>
[ProtoContract]
public class AllNamespacesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}

/// <summary>
/// Represents the ObserveNamespacesRequest message.
/// </summary>
[ProtoContract]
public class ObserveNamespacesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}