// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Chronicle.Contracts;

/// <summary>
/// Provides the canonical descriptor set describing every contract in this version of Chronicle.
/// </summary>
/// <remarks>
/// This is the same artifact - byte for byte - that the Kotlin, TypeScript and Elixir contracts packages ship, so
/// that whichever client connects, the kernel compares like with like and owns the only compatibility check there is.
/// </remarks>
public static class WireContractDescriptorSet
{
    const string ResourceName = "Cratis.Chronicle.Contracts.chronicle.desc";

    /// <summary>
    /// Gets the serialized <c>FileDescriptorSet</c> for this version of the contracts.
    /// </summary>
    public static ReadOnlyMemory<byte> Bytes { get; } = Read();

    static ReadOnlyMemory<byte> Read()
    {
        using var stream = typeof(WireContractDescriptorSet).Assembly.GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"'{ResourceName}' is not embedded in {typeof(WireContractDescriptorSet).Assembly.GetName().Name}. It is generated by Source/Kernel/Protobuf/generate-protos.sh and has to be committed alongside the proto files.");

        using var buffer = new MemoryStream();
        stream.CopyTo(buffer);
        return buffer.ToArray();
    }
}
