// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.ReadModelExplorer;
/// <summary>
/// Represents the Event message.
/// </summary>
[ProtoContract]
public class Event
{
    /// <summary>
    /// Gets or sets the Context.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Sequences.EventContext Context { get; set; }

    /// <summary>
    /// Gets or sets the Content.
    /// </summary>
    [ProtoMember(2)]
    public string Content { get; set; }
}