// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.ProjectionEditor;
/// <summary>
/// Represents the DraftReadModel message.
/// </summary>
[ProtoContract]
public class DraftReadModel
{
    /// <summary>
    /// Gets or sets the Identifier.
    /// </summary>
    [ProtoMember(1)]
    public string Identifier { get; set; }

    /// <summary>
    /// Gets or sets the DisplayName.
    /// </summary>
    [ProtoMember(2)]
    public string DisplayName { get; set; }

    /// <summary>
    /// Gets or sets the ContainerName.
    /// </summary>
    [ProtoMember(3)]
    public string ContainerName { get; set; }

    /// <summary>
    /// Gets or sets the Schema.
    /// </summary>
    [ProtoMember(4)]
    public string Schema { get; set; }
}