// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.ProjectionEditor;
/// <summary>
/// Defines the gRPC service contract for ProjectionEditor.
/// </summary>
[Service]
public interface IProjectionEditor
{
    /// <summary>
    /// Executes the GenerateDeclarativeCode command.
    /// </summary>
    /// <param name = "request">The GenerateDeclarativeCode request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult<GenerateDeclarativeCodeResponse>> GenerateDeclarativeCode(GenerateDeclarativeCodeRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GenerateModelBoundCode command.
    /// </summary>
    /// <param name = "request">The GenerateModelBoundCode request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult<GenerateDeclarativeCodeResponse>> GenerateModelBoundCode(GenerateModelBoundCodeRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the GenerateDeclarativeCodeRequest message.
/// </summary>
[ProtoContract]
public class GenerateDeclarativeCodeRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the Declaration.
    /// </summary>
    [ProtoMember(3)]
    public string Declaration { get; set; }

    /// <summary>
    /// Gets or sets the DraftReadModel.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.ProjectionEditor.DraftReadModel? DraftReadModel { get; set; }

    /// <summary>
    /// Gets or sets the Language.
    /// </summary>
    [ProtoMember(5)]
    public string Language { get; set; }
}

/// <summary>
/// Represents the GenerateDeclarativeCodeResponse message.
/// </summary>
[ProtoContract]
public class GenerateDeclarativeCodeResponse
{
    /// <summary>
    /// Gets or sets the Code.
    /// </summary>
    [ProtoMember(1)]
    public string Code { get; set; }

    /// <summary>
    /// Gets or sets the Errors.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.ProjectionEditor.ProjectionDeclarationSyntaxError> Errors { get; set; } = new List<global::Cratis.Chronicle.Contracts.ProjectionEditor.ProjectionDeclarationSyntaxError>();
}

/// <summary>
/// Represents the GenerateModelBoundCodeRequest message.
/// </summary>
[ProtoContract]
public class GenerateModelBoundCodeRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the Declaration.
    /// </summary>
    [ProtoMember(3)]
    public string Declaration { get; set; }

    /// <summary>
    /// Gets or sets the DraftReadModel.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.ProjectionEditor.DraftReadModel? DraftReadModel { get; set; }

    /// <summary>
    /// Gets or sets the Language.
    /// </summary>
    [ProtoMember(5)]
    public string Language { get; set; }
}