// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.ProjectionEditor;
/// <summary>
/// Represents the ProjectionDeclarationSyntaxError message.
/// </summary>
[ProtoContract]
public class ProjectionDeclarationSyntaxError
{
    /// <summary>
    /// Gets or sets the Message.
    /// </summary>
    [ProtoMember(1)]
    public string Message { get; set; }

    /// <summary>
    /// Gets or sets the Line.
    /// </summary>
    [ProtoMember(2)]
    public int Line { get; set; }

    /// <summary>
    /// Gets or sets the Column.
    /// </summary>
    [ProtoMember(3)]
    public int Column { get; set; }
}