version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none

  cratis:
    image: einari/cratis
    volumes:
      - ./storage.json:/app/storage.json
    ports:
      - 8080:80
      - 11111:11111
      - 30000:30000
