// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Events.Constraints;
/// <summary>
/// Represents the ConstraintType value.
/// </summary>
public enum ConstraintType
{
    /// <summary>
    /// Represents the Unknown value.
    /// </summary>
    Unknown = 0,
    /// <summary>
    /// Represents the Unique value.
    /// </summary>
    Unique = 1,
    /// <summary>
    /// Represents the UniqueEventType value.
    /// </summary>
    UniqueEventType = 2,
    /// <summary>
    /// Represents the Schema value.
    /// </summary>
    Schema = 3,
    /// <summary>
    /// Represents the StreamClosed value.
    /// </summary>
    StreamClosed = 4
}