// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Events.Constraints;
/// <summary>
/// Represents the ConstraintViolation message.
/// </summary>
[ProtoContract]
public class ConstraintViolation
{
    /// <summary>
    /// Gets or sets the EventTypeId.
    /// </summary>
    [ProtoMember(1)]
    public string EventTypeId { get; set; }

    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(2)]
    public global::System.UInt64 SequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the ConstraintType.
    /// </summary>
    [ProtoMember(3)]
    public global::Cratis.Chronicle.Contracts.Events.Constraints.ConstraintType ConstraintType { get; set; }

    /// <summary>
    /// Gets or sets the ConstraintName.
    /// </summary>
    [ProtoMember(4)]
    public string ConstraintName { get; set; }

    /// <summary>
    /// Gets or sets the Message.
    /// </summary>
    [ProtoMember(5)]
    public string Message { get; set; }

    /// <summary>
    /// Gets or sets the Details.
    /// </summary>
    [ProtoMember(6)]
    public IDictionary<string, string> Details { get; set; }
}