// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.EventSequences;
/// <summary>
/// Represents the AppendReceipt message.
/// </summary>
[ProtoContract]
public class AppendReceipt
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the SequenceNumber.
    /// </summary>
    [ProtoMember(3)]
    public global::System.UInt64 SequenceNumber { get; set; } = new();

    /// <summary>
    /// Gets or sets the EventTypeId.
    /// </summary>
    [ProtoMember(4)]
    public string EventTypeId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Generation.
    /// </summary>
    [ProtoMember(5)]
    public global::System.UInt32 Generation { get; set; } = new();

    /// <summary>
    /// Gets or sets the Tombstone.
    /// </summary>
    [ProtoMember(6)]
    public bool Tombstone { get; set; }

    /// <summary>
    /// Gets or sets the EventSourceType.
    /// </summary>
    [ProtoMember(7)]
    public string EventSourceType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(8)]
    public string EventSourceId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the EventStreamType.
    /// </summary>
    [ProtoMember(9)]
    public string EventStreamType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the EventStreamId.
    /// </summary>
    [ProtoMember(10)]
    public string EventStreamId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(11)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Occurred { get; set; } = new();

    /// <summary>
    /// Gets or sets the CorrelationId.
    /// </summary>
    [ProtoMember(12)]
    public Guid CorrelationId { get; set; } = new();

    /// <summary>
    /// Gets or sets the Subject.
    /// </summary>
    [ProtoMember(13)]
    public string Subject { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Tags.
    /// </summary>
    [ProtoMember(14)]
    public IEnumerable<string> Tags { get; set; } = new List<string>();

    /// <summary>
    /// Gets or sets the Hash.
    /// </summary>
    [ProtoMember(15)]
    public string Hash { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Causation.
    /// </summary>
    [ProtoMember(16)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.EventSequences.AppendCausation> Causation { get; set; } = new List<global::Cratis.Chronicle.Contracts.EventSequences.AppendCausation>();

    /// <summary>
    /// Gets or sets the CausedBy.
    /// </summary>
    [ProtoMember(17)]
    public global::Cratis.Chronicle.Contracts.EventSequences.AppendIdentity CausedBy { get; set; } = new();

    /// <summary>
    /// Gets or sets the ObservationState.
    /// </summary>
    [ProtoMember(18)]
    public global::Cratis.Chronicle.Contracts.Events.EventObservationState ObservationState { get; set; }
}