// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.EventSequences;
/// <summary>
/// Represents the AppendCausation message.
/// </summary>
[ProtoContract]
public class AppendCausation
{
    /// <summary>
    /// Gets or sets the Occurred.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset Occurred { get; set; } = new();

    /// <summary>
    /// Gets or sets the Type.
    /// </summary>
    [ProtoMember(2)]
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Properties.
    /// </summary>
    [ProtoMember(3)]
    public global::System.Collections.Generic.IDictionary<string, string> Properties { get; set; } = new global::System.Collections.Generic.Dictionary<string, string>();
}