// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.EventSequences;
/// <summary>
/// Defines the gRPC service contract for EventSequenceQueries.
/// </summary>
[Service]
public interface IEventSequenceQueries
{
    /// <summary>
    /// Executes the IsStreamCompleted query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<bool>> IsStreamCompleted(IsStreamCompletedRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the IsStreamCompletedRequest message.
/// </summary>
[ProtoContract]
public class IsStreamCompletedRequest
{
    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(1)]
    public string EventSequenceId { get; set; }

    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(2)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(3)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamType.
    /// </summary>
    [ProtoMember(4)]
    public string EventStreamType { get; set; }

    /// <summary>
    /// Gets or sets the eventStreamId.
    /// </summary>
    [ProtoMember(5)]
    public string EventStreamId { get; set; }
}