// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Cratis.Chronicle.Storage.Sql.EventStores.Namespaces;

/// <summary>
/// Defines a service for handling dynamic table migrations.
/// </summary>
/// <typeparam name="TContext">The type of <see cref="DbContext"/>.</typeparam>
public interface ITableMigrator<TContext>
    where TContext : DbContext
{
    /// <summary>
    /// Ensures that the table has been migrated for the given context.
    /// </summary>
    /// <param name="tableName">The name of the table to ensure is migrated.</param>
    /// <param name="context">The <typeparamref name="TContext"/> instance.</param>
    /// <param name="createTableAction">The action to create the table schema.</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    Task EnsureTableMigrated(string tableName, TContext context, Func<TContext, string, Task> createTableAction);

    /// <summary>
    /// Executes the migration operations generated by the <see cref="MigrationBuilder"/>.
    /// </summary>
    /// <param name="context">The <typeparamref name="TContext"/> instance.</param>
    /// <param name="migrationBuilder">The <see cref="MigrationBuilder"/> containing the operations.</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    Task ExecuteMigrationOperations(TContext context, MigrationBuilder migrationBuilder);
}
