// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Cratis.Chronicle.Storage.Sql.EventStores.Namespaces;

/// <summary>
/// Defines a service for handling dynamic table migrations.
/// </summary>
/// <typeparam name="TContext">The type of <see cref="DbContext"/>.</typeparam>
public interface ITableMigrator<TContext>
    where TContext : DbContext
{
    /// <summary>
    /// Ensures that the table has been migrated for the given context.
    /// </summary>
    /// <param name="tableName">The name of the table to ensure is migrated.</param>
    /// <param name="context">The <typeparamref name="TContext"/> instance.</param>
    /// <param name="createTableAction">The action to create the table schema.</param>
    /// <param name="upgradeTableAction">Optional action invoked when the table already exists, for bringing an existing schema up to date.</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    Task EnsureTableMigrated(string tableName, TContext context, Func<TContext, string, Task> createTableAction, Func<TContext, string, Task>? upgradeTableAction = null);

    /// <summary>
    /// Check whether a column exists on a table.
    /// </summary>
    /// <param name="context">The <typeparamref name="TContext"/> instance.</param>
    /// <param name="tableName">The name of the table to check.</param>
    /// <param name="columnName">The name of the column to check for.</param>
    /// <returns>True if the column exists, false if not.</returns>
    Task<bool> ColumnExists(TContext context, string tableName, string columnName);

    /// <summary>
    /// Executes the migration operations generated by the <see cref="MigrationBuilder"/>.
    /// </summary>
    /// <param name="context">The <typeparamref name="TContext"/> instance.</param>
    /// <param name="migrationBuilder">The <see cref="MigrationBuilder"/> containing the operations.</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous operation.</returns>
    Task ExecuteMigrationOperations(TContext context, MigrationBuilder migrationBuilder);

    /// <summary>
    /// Clears all cached migration state for the given connection string prefix.
    /// Use this when SQLite database files have been deleted and recreated so that
    /// subsequent calls to <see cref="EnsureTableMigrated"/> re-create tables from scratch.
    /// </summary>
    /// <param name="connectionStringPrefix">
    /// Connection string prefix to match. All cached entries whose key starts with this
    /// prefix will be evicted. Pass an empty string to clear all cached entries.
    /// </param>
    void ClearMigrationCacheForConnectionString(string connectionStringPrefix);
}
