// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Patterns;
/// <summary>
/// Defines the gRPC service contract for Patterns.
/// </summary>
[Service]
public interface IPatterns
{
    /// <summary>
    /// Executes the MatchingPatterns query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<BehaviorPatternDetailsResponse>>> MatchingPatterns(MatchingPatternsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the UsualActions query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<BehaviorPatternDetailsResponse>>> UsualActions(UsualActionsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the PatternsForScope query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<BehaviorPatternDetailsResponse>>> PatternsForScope(PatternsForScopeRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllPatterns query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<BehaviorPatternDetailsResponse>>> AllPatterns(AllPatternsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllPatternScopes query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<PatternScopeResponse>>> AllPatternScopes(AllPatternScopesRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the BehaviorPatternDetailsResponse message.
/// </summary>
[ProtoContract]
public class BehaviorPatternDetailsResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the GroupingKey.
    /// </summary>
    [ProtoMember(2)]
    public string GroupingKey { get; set; }

    /// <summary>
    /// Gets or sets the Facets.
    /// </summary>
    [ProtoMember(3)]
    public global::System.Collections.Generic.IDictionary<string, string> Facets { get; set; } = new global::System.Collections.Generic.Dictionary<string, string>();

    /// <summary>
    /// Gets or sets the Confidence.
    /// </summary>
    [ProtoMember(4)]
    public double Confidence { get; set; }

    /// <summary>
    /// Gets or sets the Support.
    /// </summary>
    [ProtoMember(5)]
    public double Support { get; set; }

    /// <summary>
    /// Gets or sets the Occurrences.
    /// </summary>
    [ProtoMember(6)]
    public long Occurrences { get; set; }

    /// <summary>
    /// Gets or sets the Weight.
    /// </summary>
    [ProtoMember(7)]
    public double Weight { get; set; }

    /// <summary>
    /// Gets or sets the Specificity.
    /// </summary>
    [ProtoMember(8)]
    public int Specificity { get; set; }

    /// <summary>
    /// Gets or sets the FirstSeen.
    /// </summary>
    [ProtoMember(9)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset FirstSeen { get; set; }

    /// <summary>
    /// Gets or sets the LastSeen.
    /// </summary>
    [ProtoMember(10)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset LastSeen { get; set; }
}

/// <summary>
/// Represents the MatchingPatternsRequest message.
/// </summary>
[ProtoContract]
public class MatchingPatternsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the groupingKey.
    /// </summary>
    [ProtoMember(3)]
    public string GroupingKey { get; set; }

    /// <summary>
    /// Gets or sets the context.
    /// </summary>
    [ProtoMember(4)]
    public global::System.Collections.Generic.IDictionary<string, string> Context { get; set; } = new global::System.Collections.Generic.Dictionary<string, string>();

    /// <summary>
    /// Gets or sets the minimumConfidence.
    /// </summary>
    [ProtoMember(5)]
    public double MinimumConfidence { get; set; }

    /// <summary>
    /// Gets or sets the maximumResults.
    /// </summary>
    [ProtoMember(6)]
    public int MaximumResults { get; set; }
}

/// <summary>
/// Represents the UsualActionsRequest message.
/// </summary>
[ProtoContract]
public class UsualActionsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the groupingKey.
    /// </summary>
    [ProtoMember(3)]
    public string GroupingKey { get; set; }

    /// <summary>
    /// Gets or sets the context.
    /// </summary>
    [ProtoMember(4)]
    public global::System.Collections.Generic.IDictionary<string, string> Context { get; set; } = new global::System.Collections.Generic.Dictionary<string, string>();

    /// <summary>
    /// Gets or sets the minimumConfidence.
    /// </summary>
    [ProtoMember(5)]
    public double MinimumConfidence { get; set; }

    /// <summary>
    /// Gets or sets the maximumResults.
    /// </summary>
    [ProtoMember(6)]
    public int MaximumResults { get; set; }
}

/// <summary>
/// Represents the PatternsForScopeRequest message.
/// </summary>
[ProtoContract]
public class PatternsForScopeRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }

    /// <summary>
    /// Gets or sets the groupingKey.
    /// </summary>
    [ProtoMember(3)]
    public string GroupingKey { get; set; }
}

/// <summary>
/// Represents the AllPatternsRequest message.
/// </summary>
[ProtoContract]
public class AllPatternsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}

/// <summary>
/// Represents the PatternScopeResponse message.
/// </summary>
[ProtoContract]
public class PatternScopeResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public string Id { get; set; }
}

/// <summary>
/// Represents the AllPatternScopesRequest message.
/// </summary>
[ProtoContract]
public class AllPatternScopesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; }
}