// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Reflection;
using Microsoft.CodeAnalysis;

namespace Cratis.Chronicle.Tools.GrpcCodeGenerator.for_ServiceImplementationGenerator.when_generating_for_a_service_with_commands_and_queries;

/// <summary>
/// The interface and the class are written by two generators from one set of artifacts. If they disagree about
/// any signature - a mapped response type, a nullable result, whether a parameter travels on the wire - the
/// class does not implement the interface, and this is where that shows up.
/// </summary>
public class and_compiling_it_with_its_contract : given.a_generated_service
{
    GeneratedService _generated = null!;
    string _code = null!;
    IReadOnlyList<Diagnostic> _errors = null!;
    Assembly? _assembly;

    void Because()
    {
        _generated = new ServiceImplementationGenerator(skipNamespaceSegments: 0, ContractsNamespace, ImplementationsNamespace)
            .Generate(_serviceDefinition, _outputDirectory);

        _code = File.ReadAllText(_generated.Path);
        (_errors, _assembly) = given.GeneratedSourceCompiler.Compile(_contractCode, _code);
    }

    [Fact] void should_compile_without_errors() => _errors.ShouldBeEmpty();
    [Fact] void should_implement_the_generated_contract() => Resolve(_generated.ContractTypeName).IsAssignableFrom(Resolve(_generated.TypeName)).ShouldBeTrue();
    [Fact] void should_name_the_file_after_the_service() => Path.GetFileName(_generated.Path).ShouldEqual("Products.cs");
    [Fact] void should_mark_the_implementation_as_generated() => _code.ShouldContain("// <auto-generated />");
    [Fact] void should_dispatch_the_command_to_the_artifact() => _code.ShouldContain("new global::TestAssembly.Catalog.RegisterProduct(");
    [Fact] void should_convert_the_wire_value_to_the_concept_the_command_declares() => _code.ShouldContain("(global::TestAssembly.Catalog.ProductId)request.Id");
    [Fact] void should_map_the_read_model_onto_its_response_message() => _code.ShouldContain("static global::Generated.TestAssembly.Catalog.ProductResponse ToProductResponse(");
    [Fact] void should_let_a_query_that_can_answer_with_nothing_do_so() => _code.ShouldContain("result is null ? null : ToProductResponse(result)");
    [Fact] void should_complete_an_observable_query_with_the_call_context() => _code.ShouldContain(".CompletedBy(callContext.CancellationToken)");

    Type Resolve(string name) =>
        _assembly!.GetType(name.Replace("global::", string.Empty, StringComparison.Ordinal))!;
}
