<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>Cratis.Chronicle.Server.Specs</AssemblyName>
        <RootNamespace>Cratis.Chronicle.Server</RootNamespace>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Server/Server.csproj" />
        <ProjectReference Include="../Storage.InMemory/Storage.InMemory.csproj" />
        <ProjectReference Include="../Storage/Storage.csproj" />
    </ItemGroup>
</Project>
