// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.EventSequences.Concurrency;
/// <summary>
/// Represents the ConcurrencyViolation message.
/// </summary>
[ProtoContract]
public class ConcurrencyViolation
{
    /// <summary>
    /// Gets or sets the EventSourceId.
    /// </summary>
    [ProtoMember(1)]
    public string EventSourceId { get; set; }

    /// <summary>
    /// Gets or sets the ExpectedSequenceNumber.
    /// </summary>
    [ProtoMember(2)]
    public global::System.UInt64 ExpectedSequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the ActualSequenceNumber.
    /// </summary>
    [ProtoMember(3)]
    public global::System.UInt64 ActualSequenceNumber { get; set; }
}