version: '3.1'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/www:ro
    ports:
      - 8090:80
    extra_hosts:
      - host.docker.internal:host-gateway

  ingress-middleware:
    image: aksioinsurtech/ingressmiddleware:3.3.11-development
    ports:
      - 8091:80
    volumes:
      - ./ingress-middleware-config.json:/app/config/config.json:ro
      - ./cratis.json:/app/wwwroot/cratis.json
      - ./identities.json:/app/wwwroot/identities.json
    extra_hosts:
      - host.docker.internal:host-gateway

  cratis-kernel:
    image: aksioinsurtech/cratis:latest-development
    ports:
      - 27017:27017
      - 8080:80
      - 8081:81
      - 11111:11111
      - 30000:30000
    extra_hosts:
      - host.docker.internal:host-gateway
