// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Alerts;
/// <summary>
/// Represents the AlertIncidentDetails message.
/// </summary>
[ProtoContract]
public class AlertIncidentDetails
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(1)]
    public Guid Id { get; set; } = new();

    /// <summary>
    /// Gets or sets the Target.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertTarget Target { get; set; } = new();

    /// <summary>
    /// Gets or sets the Condition.
    /// </summary>
    [ProtoMember(3)]
    public string Condition { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Severity.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertSeverity Severity { get; set; }

    /// <summary>
    /// Gets or sets the Evidence.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertEvidence Evidence { get; set; } = new();

    /// <summary>
    /// Gets or sets the RaisedAt.
    /// </summary>
    [ProtoMember(6)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset RaisedAt { get; set; } = new();

    /// <summary>
    /// Gets or sets the LastChangedAt.
    /// </summary>
    [ProtoMember(7)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset LastChangedAt { get; set; } = new();

    /// <summary>
    /// Gets or sets the RaisedSequenceNumber.
    /// </summary>
    [ProtoMember(8)]
    public global::System.UInt64 RaisedSequenceNumber { get; set; } = new();

    /// <summary>
    /// Gets or sets the LastTransitionSequenceNumber.
    /// </summary>
    [ProtoMember(9)]
    public global::System.UInt64 LastTransitionSequenceNumber { get; set; } = new();
}