// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Alerts;
/// <summary>
/// Represents the AlertIncidentsReadinessState value.
/// </summary>
public enum AlertIncidentsReadinessState
{
    /// <summary>
    /// Represents the CatchingUp value.
    /// </summary>
    CatchingUp = 0,
    /// <summary>
    /// Represents the Ready value.
    /// </summary>
    Ready = 1,
    /// <summary>
    /// Represents the Degraded value.
    /// </summary>
    Degraded = 2
}