// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Alerts;
/// <summary>
/// Represents the AlertTarget message.
/// </summary>
[ProtoContract]
public class AlertTarget
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Namespace.
    /// </summary>
    [ProtoMember(2)]
    public string Namespace { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the ObserverId.
    /// </summary>
    [ProtoMember(3)]
    public string ObserverId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the EventSequenceId.
    /// </summary>
    [ProtoMember(4)]
    public string EventSequenceId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the Partition.
    /// </summary>
    [ProtoMember(5)]
    public string Partition { get; set; } = string.Empty;
}