// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using ProtoBuf;

namespace Cratis.Chronicle.Contracts.Alerts;
/// <summary>
/// Represents the AlertEvidence message.
/// </summary>
[ProtoContract]
public class AlertEvidence
{
    /// <summary>
    /// Gets or sets the AttemptCount.
    /// </summary>
    [ProtoMember(1)]
    public int AttemptCount { get; set; }

    /// <summary>
    /// Gets or sets the FirstFailure.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset FirstFailure { get; set; } = new();

    /// <summary>
    /// Gets or sets the LastFailure.
    /// </summary>
    [ProtoMember(3)]
    public global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset LastFailure { get; set; } = new();

    /// <summary>
    /// Gets or sets the FailureKind.
    /// </summary>
    [ProtoMember(4)]
    public global::Cratis.Chronicle.Contracts.Observation.FailureKind FailureKind { get; set; }

    /// <summary>
    /// Gets or sets the Message.
    /// </summary>
    [ProtoMember(5)]
    public string Message { get; set; } = string.Empty;
}