// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Alerts;
/// <summary>
/// Represents the AlertSeverity value.
/// </summary>
public enum AlertSeverity
{
    /// <summary>
    /// Represents the Warning value.
    /// </summary>
    Warning = 0,
    /// <summary>
    /// Represents the Critical value.
    /// </summary>
    Critical = 1
}