// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

namespace Cratis.Chronicle.Contracts.Alerts;
/// <summary>
/// Represents sampled materialization health, not a contiguous checkpoint.
/// </summary>
public enum AlertIncidentsReadinessState
{
    /// <summary>
    /// The reactor has outstanding catch-up or is not active.
    /// </summary>
    CatchingUp = 0,
    /// <summary>
    /// The active reactor is past the sampled tail and has no catch-up, replay, or failures.
    /// </summary>
    Ready = 1,
    /// <summary>
    /// The reactor has failed or quarantined partitions.
    /// </summary>
    Degraded = 2
}