// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.Alerts;
/// <summary>
/// Defines the gRPC service contract for Alerts.
/// </summary>
[Service]
public interface IAlerts
{
    /// <summary>
    /// Executes the GetOpenIncident query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<AlertIncidentLookupResponse>> GetOpenIncident(GetOpenIncidentRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GetOpenIncidents query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<AlertIncidentPageResponse>> GetOpenIncidents(GetOpenIncidentsRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the GetOpenIncidentCounts query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<AlertIncidentSummaryResponse>> GetOpenIncidentCounts(GetOpenIncidentCountsRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the AlertIncidentLookupResponse message.
/// </summary>
[ProtoContract]
public class AlertIncidentLookupResponse
{
    /// <summary>
    /// Gets or sets the Status.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState Status { get; set; }

    /// <summary>
    /// Gets or sets the Incident.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails? Incident { get; set; }
}

/// <summary>
/// Represents the GetOpenIncidentRequest message.
/// </summary>
[ProtoContract]
public class GetOpenIncidentRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the incidentId.
    /// </summary>
    [ProtoMember(2)]
    public Guid IncidentId { get; set; } = new();

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(3)]
    public string? Namespace { get; set; }
}

/// <summary>
/// Represents the AlertIncidentPageResponse message.
/// </summary>
[ProtoContract]
public class AlertIncidentPageResponse
{
    /// <summary>
    /// Gets or sets the Status.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState Status { get; set; }

    /// <summary>
    /// Gets or sets the Items.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails> Items { get; set; } = new List<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentDetails>();

    /// <summary>
    /// Gets or sets the Next.
    /// </summary>
    [ProtoMember(3)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentContinuation? Next { get; set; }
}

/// <summary>
/// Represents the GetOpenIncidentsRequest message.
/// </summary>
[ProtoContract]
public class GetOpenIncidentsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string? Namespace { get; set; }

    /// <summary>
    /// Gets or sets the observerId.
    /// </summary>
    [ProtoMember(3)]
    public string? ObserverId { get; set; }

    /// <summary>
    /// Gets or sets the condition.
    /// </summary>
    [ProtoMember(4)]
    public string? Condition { get; set; }

    /// <summary>
    /// Gets or sets the minimumSeverity.
    /// </summary>
    [ProtoMember(5)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertSeverity? MinimumSeverity { get; set; }

    /// <summary>
    /// Gets or sets the limit.
    /// </summary>
    [ProtoMember(6)]
    public int Limit { get; set; }

    /// <summary>
    /// Gets or sets the afterRaisedSequenceNumber.
    /// </summary>
    [ProtoMember(7)]
    public global::System.UInt64 AfterRaisedSequenceNumber { get; set; }

    /// <summary>
    /// Gets or sets the afterIncidentId.
    /// </summary>
    [ProtoMember(8)]
    public Guid? AfterIncidentId { get; set; }
}

/// <summary>
/// Represents the AlertIncidentSummaryResponse message.
/// </summary>
[ProtoContract]
public class AlertIncidentSummaryResponse
{
    /// <summary>
    /// Gets or sets the Status.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState Status { get; set; }

    /// <summary>
    /// Gets or sets the Counts.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentCountDetails> Counts { get; set; } = new List<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentCountDetails>();
}

/// <summary>
/// Represents the GetOpenIncidentCountsRequest message.
/// </summary>
[ProtoContract]
public class GetOpenIncidentCountsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the namespace.
    /// </summary>
    [ProtoMember(2)]
    public string? Namespace { get; set; }
}