// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Chronicle.CodeAnalysis.Specs.Analyzers.for_FluentCrossSubjectPiiJoinAnalyzer.given;

public class a_fluent_cross_subject_pii_join_analyzer : Specification
{
    protected static string CreateSource(string usage)
    {
        return string.Join(Environment.NewLine,
        [
            "using System;",
            "using System.Collections.Generic;",
            "using System.Linq.Expressions;",
            "using Cratis.Chronicle;",
            "using Cratis.Chronicle.Compliance.GDPR;",
            "using Cratis.Chronicle.Events;",
            "using Cratis.Chronicle.Keys;",
            "using Cratis.Chronicle.Properties;",
            "using Cratis.Chronicle.Projections;",
            "",
            "namespace System.Runtime.CompilerServices",
            "{",
            "    public sealed class IsExternalInit { }",
            "}",
            "",
            "namespace Cratis.Chronicle",
            "{",
            "    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]",
            "    public sealed class SubjectAttribute : Attribute { }",
            "}",
            "",
            "namespace Cratis.Chronicle.Compliance.GDPR",
            "{",
            "    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Parameter)]",
            "    public sealed class PIIAttribute : Attribute { }",
            "}",
            "",
            "namespace Cratis.Chronicle.Events",
            "{",
            "    public sealed class EventContext",
            "    {",
            "        public string EventSourceId { get; set; } = string.Empty;",
            "        public string Subject { get; set; } = string.Empty;",
            "    }",
            "}",
            "",
            "namespace Cratis.Chronicle.Keys",
            "{",
            "    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]",
            "    public sealed class KeyAttribute : Attribute { }",
            "}",
            "",
            "namespace Cratis.Chronicle.Properties",
            "{",
            "    public sealed record PropertyPath(string Path)",
            "    {",
            "        public static implicit operator PropertyPath(string path) => new(path);",
            "    }",
            "}",
            "",
            "namespace Cratis.Chronicle.Projections",
            "{",
            "    public interface ISetBuilder<TReadModel, TEvent, TParentBuilder>",
            "    {",
            "        TParentBuilder To(PropertyPath path);",
            "    }",
            "",
            "    public interface ISetBuilder<TReadModel, TEvent, TProperty, TParentBuilder> : ISetBuilder<TReadModel, TEvent, TParentBuilder>",
            "    {",
            "        TParentBuilder To(Expression<Func<TEvent, TProperty>> accessor);",
            "    }",
            "",
            "    public interface IAddBuilder<TReadModel, TEvent, TProperty, TParentBuilder>",
            "    {",
            "        TParentBuilder With(Expression<Func<TEvent, TProperty>> accessor);",
            "    }",
            "",
            "    public interface ISubtractBuilder<TReadModel, TEvent, TProperty, TParentBuilder>",
            "    {",
            "        TParentBuilder With(Expression<Func<TEvent, TProperty>> accessor);",
            "    }",
            "",
            "    public interface IReadModelPropertiesBuilder<TReadModel, TEvent, TBuilder>",
            "    {",
            "        TBuilder UsingKey<TProperty>(Expression<Func<TEvent, TProperty>> accessor);",
            "        TBuilder UsingKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> accessor);",
            "        TBuilder UsingParentKey<TProperty>(Expression<Func<TEvent, TProperty>> accessor);",
            "        TBuilder UsingParentKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> accessor);",
            "        TBuilder UsingCompositeKey<TKey>(Action<object> callback);",
            "        TBuilder UsingParentCompositeKey<TKey>(Action<object> callback);",
            "        TBuilder UsingConstantKey(string value);",
            "        TBuilder UsingConstantParentKey(string value);",
            "        IAddBuilder<TReadModel, TEvent, TProperty, TBuilder> Add<TProperty>(Expression<Func<TReadModel, TProperty>> accessor);",
            "        ISubtractBuilder<TReadModel, TEvent, TProperty, TBuilder> Subtract<TProperty>(Expression<Func<TReadModel, TProperty>> accessor);",
            "        TBuilder AddChild<TChild>(Expression<Func<TReadModel, IEnumerable<TChild>>> target, Expression<Func<TEvent, TChild>> source);",
            "        TBuilder AddChild<TChild>(Expression<Func<TReadModel, IEnumerable<TChild>>> target, Action<IAddChildBuilder<TChild, TEvent>> callback);",
            "        ISetBuilder<TReadModel, TEvent, TBuilder> Set(PropertyPath path);",
            "        ISetBuilder<TReadModel, TEvent, TProperty, TBuilder> Set<TProperty>(Expression<Func<TReadModel, TProperty>> accessor);",
            "        ISetBuilder<TReadModel, TEvent, TBuilder> SetThisValue();",
            "    }",
            "",
            "    public interface IAddChildBuilder<TChildModel, TEvent>",
            "    {",
            "        IAddChildBuilder<TChildModel, TEvent> UsingKey<TProperty>(Expression<Func<TEvent, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> UsingKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> UsingParentKey<TProperty>(Expression<Func<TEvent, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> UsingParentKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> FromObject(Expression<Func<TEvent, TChildModel>> accessor);",
            "    }",
            "",
            "    public interface IJoinBuilder<TReadModel, TEvent> : IReadModelPropertiesBuilder<TReadModel, TEvent, IJoinBuilder<TReadModel, TEvent>>",
            "    {",
            "        IJoinBuilder<TReadModel, TEvent> On<TProperty>(Expression<Func<TReadModel, TProperty>> keyAccessor);",
            "    }",
            "",
            "    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Property | AttributeTargets.Parameter, Inherited = true)]",
            "    public sealed class NoAutoMapAttribute : Attribute { }",
            "",
            "    public interface IProjectionBuilder<TReadModel, TBuilder>",
            "    {",
            "        TBuilder From<TEvent>();",
            "        TBuilder AutoMap();",
            "        TBuilder NoAutoMap();",
            "        TBuilder Join<TEvent>(Action<IJoinBuilder<TReadModel, TEvent>>? builderCallback = default);",
            "        TBuilder Children<TChild>(Expression<Func<TReadModel, IEnumerable<TChild>>> target, Action<IChildrenBuilder<TReadModel, TChild>> callback);",
            "        TBuilder Nested<TNested>(Expression<Func<TReadModel, TNested?>> target, Action<INestedBuilder<TReadModel, TNested>> callback);",
            "    }",
            "",
            "    public interface IChildrenBuilder<TParent, TChild> : IProjectionBuilder<TChild, IChildrenBuilder<TParent, TChild>>",
            "    {",
            "        IChildrenBuilder<TParent, TChild> IdentifiedBy<TProperty>(Expression<Func<TChild, TProperty>> accessor);",
            "    }",
            "",
            "    public interface INestedBuilder<TParent, TNested> : IProjectionBuilder<TNested, INestedBuilder<TParent, TNested>>",
            "    {",
            "    }",
            "",
            "    public interface IProjectionBuilderFor<TReadModel> : IProjectionBuilder<TReadModel, IProjectionBuilderFor<TReadModel>>",
            "    {",
            "    }",
            "",
            "    public interface IProjectionFor<TReadModel>",
            "    {",
            "        void Define(IProjectionBuilderFor<TReadModel> builder);",
            "    }",
            "}",
            "",
            "namespace Sample",
            "{",
            usage,
            "}"
        ]);
    }
}
