version: '3.1'
services:
  cratis-kernel:
    image: aksioinsurtech/cratis:latest-development
    ports:
      - 27017:27017
      - 8080:80
      - 8081:81
      - 11111:11111
      - 30000:30000
    extra_hosts:
      - host.docker.internal:host-gateway
