// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Jobs;
using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.Jobs;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Jobs.IJobs"/>.
/// </summary>
internal sealed class Jobs(
    global::Orleans.IGrainFactory grainFactory,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Jobs.Jobs> logger) : global::Cratis.Chronicle.Contracts.Jobs.IJobs
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> DeleteJob(global::Cratis.Chronicle.Contracts.Jobs.DeleteJobRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Jobs.DeleteJob(request.EventStore, request.Namespace, request.JobId),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> ResumeJob(global::Cratis.Chronicle.Contracts.Jobs.ResumeJobRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Jobs.ResumeJob(request.EventStore, request.Namespace, request.JobId),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> StopJob(global::Cratis.Chronicle.Contracts.Jobs.StopJobRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.Jobs.StopJob(request.EventStore, request.Namespace, request.JobId),
            command => command.Handle(grainFactory));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Jobs.JobStepSummaryResponse>>> GetJobSteps(global::Cratis.Chronicle.Contracts.Jobs.GetJobStepsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Jobs.JobStepSummaryResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Jobs.JobStepSummary.GetJobSteps(request.EventStore, request.Namespace, request.JobId, storage);
                return result.Select(ToJobStepSummaryResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Jobs", "GetJobSteps"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Jobs.JobSummaryResponse>>> AllJobs(global::Cratis.Chronicle.Contracts.Jobs.AllJobsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Jobs.JobSummaryResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Jobs.JobSummary.AllJobs(request.EventStore, request.Namespace, grainFactory);
                return result.Select(ToJobSummaryResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "Jobs", "AllJobs"));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Jobs.JobSummaryResponse>>> ObserveJobs(global::Cratis.Chronicle.Contracts.Jobs.ObserveJobsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Jobs.JobSummaryResponse>>(
            () => global::Cratis.Chronicle.Jobs.JobSummary.ObserveJobs(request.EventStore, request.Namespace, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.Jobs.JobSummaryResponse>)_.Select(ToJobSummaryResponse).ToList()),
            exception => logger.QueryFailed(exception, "Jobs", "ObserveJobs"));

    static global::Cratis.Chronicle.Contracts.Jobs.JobStepSummaryResponse ToJobStepSummaryResponse(global::Cratis.Chronicle.Jobs.JobStepSummary source) =>
        new()
        {
            Id = source.Id,
            Type = source.Type,
            Name = source.Name,
            Status = source.Status,
            StatusChanges = source.StatusChanges,
            Progress = source.Progress
        };

    static global::Cratis.Chronicle.Contracts.Jobs.JobSummaryResponse ToJobSummaryResponse(global::Cratis.Chronicle.Jobs.JobSummary source) =>
        new()
        {
            Id = source.Id,
            Details = source.Details,
            Type = source.Type,
            Status = (global::Cratis.Chronicle.Contracts.Jobs.JobStatus)source.Status,
            Created = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.Created,
            StatusChanges = source.StatusChanges,
            Progress = source.Progress
        };
}
