// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cratis.Chronicle.Tools.GrpcCodeGenerator;

/// <summary>
/// Generates C# gRPC service interface files from service definitions using Roslyn SyntaxFactory.
/// </summary>
/// <param name="skipNamespaceSegments">The number of leading namespace segments to skip.</param>
/// <param name="baseNamespace">The base namespace to prepend to generated types.</param>
public class ServiceInterfaceGenerator(int skipNamespaceSegments, string baseNamespace)
{
    const string CopyrightHeader =
        "// Copyright (c) Cratis. All rights reserved.\n" +
        "// Licensed under the MIT license. See LICENSE file in the project root for full license information.\n\n" +
        "// <auto-generated />\n\n" +

        // An auto-generated file sits outside the nullable annotation context unless it opts back in, and a
        // stand-in for a nullable value type (SerializableDateTimeOffset? for DateTimeOffset?) is exactly the
        // annotation that then warns. See TransportTypes.
        "#nullable enable\n\n";

    /// <summary>
    /// Generates a C# interface file for the given service definition.
    /// </summary>
    /// <param name="serviceDefinition">The service definition.</param>
    /// <param name="outputDirectory">The output directory.</param>
    /// <returns>The generated C# source code.</returns>
    public string Generate(ServiceDefinition serviceDefinition, string outputDirectory)
    {
        var targetNamespace = BuildTargetNamespace(serviceDefinition.Namespace);
        var folderPath = BuildFolderPath(serviceDefinition.Namespace, outputDirectory);

        Directory.CreateDirectory(folderPath);

        var requestResponseTypes = new List<(string TypeName, List<(string PropName, string PropType)> Properties)>();
        var responseTypeNamesByClrType = new Dictionary<Type, string>();

        var interfaceMembers = new List<MemberDeclarationSyntax>();
        foreach (var command in serviceDefinition.Commands)
        {
            var requestTypeName = GenerateCommandRequestType(command, targetNamespace, requestResponseTypes);
            var responseTypeName = GenerateCommandResponseType(command, targetNamespace, requestResponseTypes, responseTypeNamesByClrType);
            interfaceMembers.Add(BuildCommandMethod(command, requestTypeName, responseTypeName));
        }

        foreach (var query in serviceDefinition.Queries)
        {
            foreach (var method in query.Methods)
            {
                interfaceMembers.Add(BuildQueryMethod(method, query.ReadModelType, targetNamespace, requestResponseTypes));
            }
        }

        foreach (var keyedQuery in serviceDefinition.KeyedQueries)
        {
            interfaceMembers.Add(BuildKeyedQueryMethod(keyedQuery, targetNamespace, requestResponseTypes));
        }

        var interfaceDecl = SyntaxFactory.InterfaceDeclaration($"I{serviceDefinition.ServiceName}")
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("Service")))))
            .WithLeadingTrivia(BuildXmlDoc($"Defines the gRPC service contract for {serviceDefinition.ServiceName}."))
            .AddMembers([.. interfaceMembers]);

        // All DTOs for a service are written to the same I{ServiceName}.cs file.
        // The path is computed once here so each DTO class can read the existing
        // [ProtoMember] indexes from the previous generation before we overwrite it.
        var fileName = GetSafeFileName($"I{serviceDefinition.ServiceName}.cs");
        var interfaceFilePath = Path.Combine(folderPath, fileName);

        var dtoClasses = requestResponseTypes
            .Select(rt =>
            {
                var existingIndexes = ProtoMemberIndexReader.ReadExistingIndexes(interfaceFilePath, rt.TypeName);
                return BuildDtoClass(rt.TypeName, rt.Properties, existingIndexes);
            })
            .Cast<MemberDeclarationSyntax>()
            .ToArray();

        MemberDeclarationSyntax[] allMembers = [interfaceDecl, .. dtoClasses];

        var namespaceDecl = SyntaxFactory.FileScopedNamespaceDeclaration(
                SyntaxFactory.ParseName(targetNamespace))
            .AddMembers(allMembers);

        UsingDirectiveSyntax[] usings =
        [
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Cratis.Chronicle.Contracts.Commands")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Cratis.Chronicle.Contracts.Primitives")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Cratis.Chronicle.Contracts.Queries")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("ProtoBuf")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("ProtoBuf.Grpc")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("ProtoBuf.Grpc.Configuration")),
        ];

        // Normalize with an explicit LF end-of-line; Roslyn would otherwise emit CRLF, which makes the
        // generated contracts churn against the repository's LF-normalized working tree on every run.
        var compilationUnit = SyntaxFactory.CompilationUnit()
            .AddUsings(usings)
            .AddMembers(namespaceDecl)
            .NormalizeWhitespace(indentation: "    ", eol: "\n");

        var code = CopyrightHeader + compilationUnit.ToFullString();

        File.WriteAllText(interfaceFilePath, code);

        return code;
    }

    /// <summary>
    /// Generates the contract mirror of a Core-owned shared type - an enum, or a plain record/class referenced
    /// by more than one command or read model, discovered via <see cref="SharedTypeRegistry"/> while generating
    /// the services that reference it.
    /// </summary>
    /// <param name="type">The Core-owned type to mirror.</param>
    /// <param name="outputDirectory">The output directory contracts are written under.</param>
    /// <returns>The generated C# source code.</returns>
    public string GenerateSharedType(Type type, string outputDirectory)
    {
        // Namespace mapping goes through the registry, not BuildTargetNamespace/BuildFolderPath below - a shared
        // type reused from a project Core depends on (Concepts.Jobs.JobStatus, say) does not necessarily sit at
        // the same relative namespace depth a service's own artifacts do, and the registry is what already
        // resolved that once, when this type was first referenced. Deriving the folder from anything else risks
        // the two disagreeing about where the file belongs.
        var targetNamespace = SharedTypeRegistry.MapNamespace(type.Namespace ?? string.Empty);
        var relativeNamespace = targetNamespace.StartsWith($"{baseNamespace}.", StringComparison.Ordinal)
            ? targetNamespace[(baseNamespace.Length + 1)..]
            : targetNamespace;
        var folderPath = Path.Combine([outputDirectory, .. relativeNamespace.Split('.')]);

        Directory.CreateDirectory(folderPath);

        var fileName = GetSafeFileName($"{type.Name}.cs");
        var filePath = Path.Combine(folderPath, fileName);

        MemberDeclarationSyntax typeDecl;
        UsingDirectiveSyntax[] usings;

        if (type.IsEnum)
        {
            typeDecl = BuildSharedEnum(type);
            usings = [];
        }
        else
        {
            // The file being read here is whatever is already on disk at this path - the first time a type is
            // mirrored, that is the hand-written contract this move is replacing, so the very first generation
            // reproduces its exact [ProtoMember] numbers with no extra bookkeeping. See ProtoMemberIndexReader.
            var existingIndexes = ProtoMemberIndexReader.ReadExistingIndexes(filePath, type.Name);
            var properties = type.GetProperties()
                .Where(p => p.CanRead && p.GetIndexParameters().Length == 0)
                .Select(p => (p.Name, NullableAnnotations.For(MemberTypeName(p.PropertyType, targetNamespace), p)))
                .ToList();

            typeDecl = BuildDtoClass(type.Name, properties, existingIndexes);
            usings = [SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("ProtoBuf"))];
        }

        var namespaceDecl = SyntaxFactory.FileScopedNamespaceDeclaration(SyntaxFactory.ParseName(targetNamespace))
            .AddMembers(typeDecl);

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .AddUsings(usings)
            .AddMembers(namespaceDecl)
            .NormalizeWhitespace(indentation: "    ", eol: "\n");

        var code = CopyrightHeader + compilationUnit.ToFullString();

        File.WriteAllText(filePath, code);

        return code;
    }

    static EnumDeclarationSyntax BuildSharedEnum(Type type)
    {
        // protobuf-net serializes an enum by its declared numeric value, so copying every member's existing
        // value verbatim - not renumbering by declaration order - is the entire wire-stability story for a
        // shared enum. Rendered as an int literal to match every hand-written enum in this codebase (the
        // underlying type of a C# enum defaults to int, and nothing here declares otherwise); Convert.ToInt64
        // would compile too, but as a spurious "0L" no hand-written enum in the codebase ever writes.
        var members = Enum.GetValues(type)
            .Cast<object>()
            .Select(value =>
            {
                var name = Enum.GetName(type, value) ?? throw new UnsupportedServiceShape(type.Name, "an enum value has no name.");
                return SyntaxFactory.EnumMemberDeclaration(SyntaxFactory.Identifier(name))
                    .WithEqualsValue(SyntaxFactory.EqualsValueClause(
                        SyntaxFactory.LiteralExpression(
                            SyntaxKind.NumericLiteralExpression,
                            SyntaxFactory.Literal(Convert.ToInt32(value)))))
                    .WithLeadingTrivia(BuildXmlDoc($"Represents the {name} value."));
            });

        return SyntaxFactory.EnumDeclaration(type.Name)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithLeadingTrivia(BuildXmlDoc($"Represents the {type.Name} value."))
            .AddMembers([.. members]);
    }

    static MethodDeclarationSyntax BuildCommandMethod(CommandDefinition command, string? requestTypeName, string? responseTypeName)
    {
        var parameters = new List<ParameterSyntax>();
        var paramDocs = new List<(string Name, string Text)>();

        if (requestTypeName is not null)
        {
            parameters.Add(
                SyntaxFactory.Parameter(SyntaxFactory.Identifier("request"))
                    .WithType(SyntaxFactory.ParseTypeName(requestTypeName)));
            paramDocs.Add(("request", $"The {command.Name} request."));
        }

        parameters.Add(BuildCallContextParameter());
        paramDocs.Add(("callContext", "The gRPC call context."));

        var resultType = responseTypeName is null ? "Task<CommandResult>" : $"Task<CommandResult<{responseTypeName}>>";

        return SyntaxFactory.MethodDeclaration(
                SyntaxFactory.ParseTypeName(resultType),
                SyntaxFactory.Identifier(command.Name))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("Operation")))))
            .AddParameterListParameters([.. parameters])
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(BuildXmlDoc(
                $"Executes the {command.Name} command.",
                [.. paramDocs],
                "The command result."));
    }

    static MethodDeclarationSyntax BuildQueryMethod(
        QueryMethodDefinition method,
        Type readModelType,
        string targetNamespace,
        List<(string TypeName, List<(string PropName, string PropType)> Properties)> requestResponseTypes)
    {
        var returnType = method.ReturnType;
        var isObservable = TypeHelper.IsObservableType(returnType);
        var responseTypeName = $"{readModelType.Name}Response";

        var readModelProperties = GetReadModelProperties(readModelType, targetNamespace);
        if (readModelProperties.Count > 0 && !requestResponseTypes.Exists(r => r.TypeName == responseTypeName))
        {
            requestResponseTypes.Add((responseTypeName, readModelProperties));
        }

        string returnTypeStr;
        if (isObservable)
        {
            var innerType = GetObservableInnerType(returnType);
            var observed = innerType is not null ? MapToResponseType(innerType, responseTypeName) : responseTypeName;
            returnTypeStr = $"IObservable<QueryResult<{Optional(observed, method.Method)}>>";
        }
        else
        {
            var queryReturnType = TypeHelper.GetQueryReturnType(returnType);
            if (TypeHelper.IsOneOfType(queryReturnType))
            {
                queryReturnType = TypeHelper.GetOneOfSuccessType(queryReturnType);
            }

            var mapped = Optional(MapToResponseType(queryReturnType, responseTypeName), method.Method);
            returnTypeStr = TypeHelper.IsVoidTask(returnType) ? "Task" : $"Task<QueryResult<{mapped}>>";
        }

        var parameters = new List<ParameterSyntax>();
        var paramDocs = new List<(string Name, string Text)>();

        if (method.Parameters.Count > 0)
        {
            var requestTypeName = $"{method.Name}Request";

            // Filter out DI-injected parameters - they are resolved from the service container and must not
            // appear as gRPC wire-level request properties. See ParameterClassification for the rule, which the
            // implementation generator has to apply identically.
            var props = method.Parameters
                .Where(p => !ParameterClassification.IsDependency(p.ParameterType))
                .Select(p => (p.Name ?? "value", NullableAnnotations.For(MemberTypeName(p.ParameterType, targetNamespace), p)))
                .ToList();

            if (props.Count > 0 && !requestResponseTypes.Exists(r => r.TypeName == requestTypeName))
            {
                requestResponseTypes.Add((requestTypeName, props));
            }

            if (props.Count > 0)
            {
                parameters.Add(
                    SyntaxFactory.Parameter(SyntaxFactory.Identifier("request"))
                        .WithType(SyntaxFactory.ParseTypeName(requestTypeName)));
                paramDocs.Add(("request", "The query request parameters."));
            }
        }

        parameters.Add(BuildCallContextParameter());
        paramDocs.Add(("callContext", "The gRPC call context."));

        return SyntaxFactory.MethodDeclaration(
                SyntaxFactory.ParseTypeName(returnTypeStr),
                SyntaxFactory.Identifier(method.Name))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("Operation")))))
            .AddParameterListParameters([.. parameters])
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(BuildXmlDoc(
                $"Executes the {method.Name} query.",
                [.. paramDocs],
                "The query result."));
    }

    /// <summary>
    /// Builds the interface method for a <c>[Query]</c>-marked method on a <c>[KeyedBy&lt;TKey&gt;]</c> grain
    /// interface - a query with no read model of its own, so its request carries the grain key's fields ahead of
    /// its own parameters and its response type is named after the method, not a read model.
    /// </summary>
    /// <param name="method">The keyed query to build.</param>
    /// <param name="targetNamespace">The namespace the generated messages live in.</param>
    /// <param name="requestResponseTypes">The request/response DTOs accumulated for the service.</param>
    /// <returns>The interface method declaration.</returns>
    static MethodDeclarationSyntax BuildKeyedQueryMethod(
        KeyedQueryDefinition method,
        string targetNamespace,
        List<(string TypeName, List<(string PropName, string PropType)> Properties)> requestResponseTypes)
    {
        var returnType = method.ReturnType;
        var isObservable = TypeHelper.IsObservableType(returnType);
        var responseTypeName = $"{method.Name}Response";

        string returnTypeStr;
        if (isObservable)
        {
            var innerType = GetObservableInnerType(returnType);
            var observed = innerType is not null ? MapToResponseType(innerType, responseTypeName) : responseTypeName;
            returnTypeStr = $"IObservable<QueryResult<{Optional(observed, method.Method)}>>";
        }
        else
        {
            var queryReturnType = TypeHelper.GetQueryReturnType(returnType);
            if (TypeHelper.IsOneOfType(queryReturnType))
            {
                queryReturnType = TypeHelper.GetOneOfSuccessType(queryReturnType);
            }

            var mapped = Optional(MapToResponseType(queryReturnType, responseTypeName), method.Method);
            returnTypeStr = TypeHelper.IsVoidTask(returnType) ? "Task" : $"Task<QueryResult<{mapped}>>";
        }

        var parameters = new List<ParameterSyntax>();
        var paramDocs = new List<(string Name, string Text)>();

        // The grain key's fields come first, then the method's own parameters - the implementation generator
        // reads the same two groups in the same order to reconstruct the key and call the method.
        var keyProps = method.KeyParameters
            .Select(p => (p.Name ?? "value", NullableAnnotations.For(MemberTypeName(p.ParameterType, targetNamespace), p)));
        var methodProps = method.Parameters
            .Where(p => !ParameterClassification.IsDependency(p.ParameterType))
            .Select(p => (p.Name ?? "value", NullableAnnotations.For(MemberTypeName(p.ParameterType, targetNamespace), p)));
        var props = keyProps.Concat(methodProps).ToList();

        if (props.Count > 0)
        {
            var requestTypeName = $"{method.Name}Request";
            if (!requestResponseTypes.Exists(r => r.TypeName == requestTypeName))
            {
                requestResponseTypes.Add((requestTypeName, props));
            }

            parameters.Add(
                SyntaxFactory.Parameter(SyntaxFactory.Identifier("request"))
                    .WithType(SyntaxFactory.ParseTypeName(requestTypeName)));
            paramDocs.Add(("request", "The query request parameters."));
        }

        parameters.Add(BuildCallContextParameter());
        paramDocs.Add(("callContext", "The gRPC call context."));

        return SyntaxFactory.MethodDeclaration(
                SyntaxFactory.ParseTypeName(returnTypeStr),
                SyntaxFactory.Identifier(method.Name))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("Operation")))))
            .AddParameterListParameters([.. parameters])
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(BuildXmlDoc(
                $"Executes the {method.Name} query.",
                [.. paramDocs],
                "The query result."));
    }

    /// <summary>
    /// Annotates a query's mapped result with the absence the query declares.
    /// </summary>
    /// <param name="typeName">The mapped result type name.</param>
    /// <param name="method">The query method.</param>
    /// <returns>The annotated type name.</returns>
    /// <remarks>
    /// A query that can answer with nothing has to say so on the contract, or the implementation generated
    /// against that contract has nowhere to put the absence. See <see cref="QueryNullability"/>.
    /// </remarks>
    static string Optional(string typeName, MethodInfo method) =>
        typeName.EndsWith('?') || !QueryNullability.ResultIsNullable(method) ? typeName : $"{typeName}?";

    /// <summary>
    /// Renders the type a message member carries.
    /// </summary>
    /// <param name="type">The member's declared type.</param>
    /// <param name="targetNamespace">The namespace the generated messages live in.</param>
    /// <returns>The rendered type name.</returns>
    /// <remarks>
    /// A member typed as a read model carries that read model's generated message, not the Core record - which
    /// the contracts cannot see at all. A save that answers with what it saved is exactly that shape.
    /// </remarks>
    static string MemberTypeName(Type type, string targetNamespace)
    {
        var unwrapped = TypeHelper.UnwrapConceptType(type);

        if (TypeHelper.IsReadModelType(unwrapped))
        {
            return $"global::{targetNamespace}.{unwrapped.Name}Response";
        }

        if (unwrapped.IsGenericType &&
            unwrapped.GetGenericTypeDefinition().FullName?.StartsWith("System.Collections.Generic.IEnumerable`", StringComparison.Ordinal) == true)
        {
            var element = unwrapped.GetGenericArguments()[0];
            if (TypeHelper.IsReadModelType(TypeHelper.UnwrapConceptType(element)))
            {
                return $"IEnumerable<{MemberTypeName(element, targetNamespace)}>";
            }
        }

        return TypeHelper.GetTypeName(unwrapped);
    }

    /// <summary>
    /// Renders the type a message member carries.
    /// </summary>
    /// <param name="type">The member's declared type.</param>
    /// <param name="targetNamespace">The namespace the generated messages live in.</param>
    /// <returns>The rendered type name.</returns>
    /// <remarks>
    /// A member typed as a read model carries that read model's generated message, not the Core record - which
    /// the contracts cannot see at all. A save that answers with what it saved is exactly that shape.
    /// </remarks>
    static string MemberTypeName(Type type, string targetNamespace)
    {
        var unwrapped = TypeHelper.UnwrapConceptType(type);

        if (TypeHelper.IsReadModelType(unwrapped))
        {
            return $"global::{targetNamespace}.{unwrapped.Name}Response";
        }

        if (unwrapped.IsGenericType &&
            unwrapped.GetGenericTypeDefinition().FullName?.StartsWith("System.Collections.Generic.IEnumerable`", StringComparison.Ordinal) == true)
        {
            var element = unwrapped.GetGenericArguments()[0];
            if (TypeHelper.IsReadModelType(TypeHelper.UnwrapConceptType(element)))
            {
                return $"IEnumerable<{MemberTypeName(element, targetNamespace)}>";
            }
        }

        return TypeHelper.GetTypeName(unwrapped);
    }

    static ClassDeclarationSyntax BuildDtoClass(
        string typeName,
        List<(string PropName, string PropType)> properties,
        IReadOnlyDictionary<string, int> existingIndexes)
    {
        var nextIndex = existingIndexes.Values.DefaultIfEmpty(0).Max() + 1;

        var propertyMembers = new List<MemberDeclarationSyntax>();
        foreach (var (propName, propType) in properties)
        {
            var pascalName = ToPascalCase(propName);
            var index = existingIndexes.TryGetValue(pascalName, out var existing) ? existing : nextIndex++;
            propertyMembers.Add(BuildDtoProperty(propName, propType, index));
        }

        return SyntaxFactory.ClassDeclaration(typeName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("ProtoContract")))))
            .WithLeadingTrivia(BuildXmlDoc($"Represents the {typeName} message."))
            .AddMembers([.. propertyMembers]);
    }

    static PropertyDeclarationSyntax BuildDtoProperty(string propName, string propType, int protoMemberIndex)
    {
        var property = SyntaxFactory.PropertyDeclaration(
                SyntaxFactory.ParseTypeName(propType),
                SyntaxFactory.Identifier(ToPascalCase(propName)))
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(
                        SyntaxFactory.ParseName("ProtoMember"),
                        SyntaxFactory.AttributeArgumentList(
                            SyntaxFactory.SingletonSeparatedList(
                                SyntaxFactory.AttributeArgument(
                                    SyntaxFactory.LiteralExpression(
                                        SyntaxKind.NumericLiteralExpression,
                                        SyntaxFactory.Literal(protoMemberIndex)))))))))
            .AddAccessorListAccessors(
                SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                    .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                    .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)))
            .WithLeadingTrivia(BuildXmlDoc($"Gets or sets the {propName}."));

        // A non-nullable IEnumerable<T>/IDictionary<TKey,TValue> property left unset by a caller - or carrying zero
        // elements on the wire - deserializes as null rather than empty, because protobuf-net only ever assigns
        // through the setter when elements are actually present. Defaulting it matches what Core's own non-nullable
        // annotation promises callers: always present, never null.
        var initializer = BuildDtoPropertyInitializer(propType);
        return initializer is null
            ? property
            : property.WithInitializer(initializer).WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));
    }

    static EqualsValueClauseSyntax? BuildDtoPropertyInitializer(string propType)
    {
        if (IsNonNullableCollection(propType))
        {
            return SyntaxFactory.EqualsValueClause(SyntaxFactory.CollectionExpression());
        }

        if (IsNonNullableDictionary(propType))
        {
            // IDictionary<TKey,TValue> has no natural collection-expression target type, so the concrete
            // Dictionary<TKey,TValue> is spelled out instead. The interface can render either short ("IDictionary<...>")
            // or fully qualified ("global::System.Collections.Generic.IDictionary<...>") depending on how GetTypeName
            // reached it - swapping just the "IDictionary<" token keeps whichever prefix and the (possibly
            // nested-generic) key/value arguments intact without having to parse them apart.
            var concreteType = propType.Replace("IDictionary<", "Dictionary<", StringComparison.Ordinal);
            return SyntaxFactory.EqualsValueClause(
                SyntaxFactory.ObjectCreationExpression(SyntaxFactory.ParseTypeName(concreteType))
                    .WithArgumentList(SyntaxFactory.ArgumentList()));
        }

        return null;
    }

    static bool IsNonNullableCollection(string propType) =>
        propType.StartsWith("IEnumerable<", StringComparison.Ordinal) && !propType.EndsWith('?');

    static bool IsNonNullableDictionary(string propType) =>
        propType.Contains("IDictionary<", StringComparison.Ordinal) && !propType.EndsWith('?');

    static ParameterSyntax BuildCallContextParameter() =>
        SyntaxFactory.Parameter(SyntaxFactory.Identifier("callContext"))
            .WithType(SyntaxFactory.ParseTypeName("CallContext"))
            .WithDefault(SyntaxFactory.EqualsValueClause(
                SyntaxFactory.LiteralExpression(SyntaxKind.DefaultLiteralExpression)));

    static SyntaxTriviaList BuildXmlDoc(
        string summary,
        IEnumerable<(string Name, string Text)>? paramDocs = null,
        string? returns = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {summary}");
        sb.AppendLine("/// </summary>");

        if (paramDocs is not null)
        {
            foreach (var (name, text) in paramDocs)
            {
                sb.AppendLine($"/// <param name=\"{name}\">{text}</param>");
            }
        }

        if (returns is not null)
        {
            sb.AppendLine($"/// <returns>{returns}</returns>");
        }

        return SyntaxFactory.ParseLeadingTrivia(sb.ToString());
    }

    static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    static string GetSafeFileName(string fileName)
    {
        if (string.IsNullOrEmpty(fileName))
        {
            return fileName;
        }

        fileName = Path.GetFileName(fileName);

        var invalidChars = Path.GetInvalidFileNameChars();
        var builder = new StringBuilder(fileName.Length);
        foreach (var ch in fileName)
        {
            builder.Append(Array.IndexOf(invalidChars, ch) >= 0 ? '_' : ch);
        }

        return builder.ToString();
    }

    static string? GenerateCommandRequestType(
        CommandDefinition command,
        string targetNamespace,
        List<(string TypeName, List<(string PropName, string PropType)> Properties)> requestResponseTypes)
    {
        var parameters = command.Parameters;
        if (parameters.Count == 0)
        {
            return null;
        }

        var requestTypeName = $"{command.Name}Request";
        var properties = parameters
            .Select(p => (p.Name ?? "value", NullableAnnotations.For(MemberTypeName(p.ParameterType, targetNamespace), p)))
            .ToList();

        requestResponseTypes.Add((requestTypeName, properties));
        return requestTypeName;
    }

    static string? GenerateCommandResponseType(
        CommandDefinition command,
        string targetNamespace,
        List<(string TypeName, List<(string PropName, string PropType)> Properties)> requestResponseTypes,
        Dictionary<Type, string> responseTypeNamesByClrType)
    {
        if (command.ResponseType is not { } responseType)
        {
            return null;
        }

        // A concept or primitive response travels as its underlying value; only a composite response
        // needs a generated message type to carry its properties.
        var unwrapped = TypeHelper.UnwrapConceptType(responseType);
        if (unwrapped != responseType || unwrapped.IsPrimitive || unwrapped == typeof(string) || unwrapped == typeof(Guid))
        {
            return TypeHelper.GetTypeName(unwrapped);
        }

        // Two commands can share one CLR response type (AppendMany / AppendManyForEventSources both answer with
        // AppendManyResult) - the implementation generator's ImplementationContext.MappingForCommandResponse
        // dedupes by that CLR type, reusing whichever name it saw first, so the interface has to agree on the same
        // name or the two generators emit a mismatched contract the implementation cannot satisfy.
        if (responseTypeNamesByClrType.TryGetValue(responseType, out var existingResponseTypeName))
        {
            return existingResponseTypeName;
        }

        var responseTypeName = $"{command.Name}Response";
        if (!requestResponseTypes.Exists(_ => _.TypeName == responseTypeName))
        {
            var properties = responseType.GetProperties()
                .Where(_ => _.CanRead && _.GetIndexParameters().Length == 0)
                .Select(_ => (_.Name, NullableAnnotations.For(MemberTypeName(_.PropertyType, targetNamespace), _)))
                .ToList();

            requestResponseTypes.Add((responseTypeName, properties));
        }

        responseTypeNamesByClrType[responseType] = responseTypeName;
        return responseTypeName;
    }

    static string MapToResponseType(Type type, string responseTypeName)
    {
        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition();
            var args = type.GetGenericArguments();

            if (genericDef.FullName?.StartsWith("System.Collections.Generic.IEnumerable`", StringComparison.Ordinal) == true)
            {
                var innerMapped = MapToResponseType(args[0], responseTypeName);
                return $"IEnumerable<{innerMapped}>";
            }

            if (genericDef.Name.StartsWith("Nullable`", StringComparison.Ordinal))
            {
                return $"{MapToResponseType(args[0], responseTypeName)}?";
            }
        }

        if (TypeHelper.IsReadModelType(type))
        {
            return responseTypeName;
        }

        if (TypeHelper.IsConceptType(type))
        {
            return TypeHelper.GetTypeName(TypeHelper.UnwrapConceptType(type));
        }

        return TypeHelper.GetTypeName(type);
    }

    static Type? GetObservableInnerType(Type type)
    {
        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition();
            if (genericDef.Name.StartsWith("ISubject`", StringComparison.Ordinal) ||
                genericDef.Name.StartsWith("IObservable`", StringComparison.Ordinal) ||
                genericDef.Name.StartsWith("BehaviorSubject`", StringComparison.Ordinal))
            {
                return type.GetGenericArguments()[0];
            }
        }

        var observableInterface = type.GetInterfaces()
            .FirstOrDefault(i => i.IsGenericType &&
                (i.GetGenericTypeDefinition().Name.StartsWith("ISubject`", StringComparison.Ordinal) ||
                 i.GetGenericTypeDefinition().Name.StartsWith("IObservable`", StringComparison.Ordinal)));

        return observableInterface?.GetGenericArguments()[0];
    }

    static List<(string PropName, string PropType)> GetReadModelProperties(Type readModelType, string targetNamespace)
    {
        var constructor = readModelType.GetConstructors().FirstOrDefault();
        if (constructor is null)
        {
            return [];
        }

        return constructor.GetParameters()
            .Select(p => (p.Name ?? "value", NullableAnnotations.For(MemberTypeName(p.ParameterType, targetNamespace), p)))
            .ToList();
    }

    string BuildTargetNamespace(string sourceNamespace)
    {
        var segments = sourceNamespace.Split('.');
        var skipped = segments.Skip(skipNamespaceSegments).ToArray();

        if (!string.IsNullOrEmpty(baseNamespace))
        {
            return $"{baseNamespace}.{string.Join('.', skipped)}";
        }

        return string.Join('.', skipped);
    }

    string BuildFolderPath(string sourceNamespace, string outputDirectory)
    {
        var segments = sourceNamespace.Split('.');
        var skipped = segments.Skip(skipNamespaceSegments).ToArray();
        var safeSegments = skipped
            .Select(s => s.TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar))
            .ToArray();

        return Path.Combine([outputDirectory, .. safeSegments]);
    }
}
