// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Cratis.Chronicle.Tools.GrpcCodeGenerator;

/// <summary>
/// Generates the class that implements a generated gRPC service contract by dispatching to Arc artifacts.
/// </summary>
/// <param name="skipNamespaceSegments">The number of leading namespace segments to skip.</param>
/// <param name="contractsBaseNamespace">The base namespace the generated contracts live in.</param>
/// <param name="implementationsBaseNamespace">The base namespace the generated implementations live in.</param>
/// <remarks>
/// Generating the interface without the class is what left 7,000 lines of hand-written services behind: the
/// contract was derived, the thing serving it was not, and every artifact still needed a hand-written method
/// wiring the two together. This closes that gap - the implementation is derived from the same artifacts the
/// interface is, so an artifact is the only thing anybody writes.
/// </remarks>
public class ServiceImplementationGenerator(int skipNamespaceSegments, string contractsBaseNamespace, string implementationsBaseNamespace)
{
    const string Header =
        "// Copyright (c) Cratis. All rights reserved.\n" +
        "// Licensed under the MIT license. See LICENSE file in the project root for full license information.\n\n" +
        "// <auto-generated />\n\n" +
        "#nullable enable\n\n";

    /// <summary>
    /// Generates the implementation for a service.
    /// </summary>
    /// <param name="serviceDefinition">The service to implement.</param>
    /// <param name="outputDirectory">The directory to write the implementation under.</param>
    /// <returns>What was generated, for the registrations to refer to.</returns>
    public GeneratedService Generate(ServiceDefinition serviceDefinition, string outputDirectory)
    {
        var segments = serviceDefinition.Namespace.Split('.').Skip(skipNamespaceSegments).ToArray();
        var contractsNamespace = Join(contractsBaseNamespace, segments);
        var implementationNamespace = Join(implementationsBaseNamespace, segments);
        var context = new ImplementationContext(contractsNamespace);

        var members = new List<string>();
        foreach (var command in serviceDefinition.Commands.OrderBy(_ => _.Name, StringComparer.Ordinal))
        {
            members.Add(ImplementationMethods.ForCommand(command, context));
        }

        var hasQueries = false;
        foreach (var query in serviceDefinition.Queries)
        {
            foreach (var method in query.Methods.OrderBy(_ => _.Name, StringComparer.Ordinal))
            {
                members.Add(ImplementationMethods.ForQuery(method, query.ReadModelType, serviceDefinition.ServiceName, context));
                hasQueries |= !TypeHelper.IsVoidTask(method.ReturnType);
            }
        }

        members.AddRange(context.Mappings.Select(mapping => ImplementationMethods.ForMapping(mapping, context)));

        var typeName = $"global::{implementationNamespace}.{serviceDefinition.ServiceName}";
        var contractTypeName = $"global::{contractsNamespace}.I{serviceDefinition.ServiceName}";
        var observes = serviceDefinition.Queries.SelectMany(_ => _.Methods).Any(_ => _.IsObservable);

        var code = Header
            + Usings(serviceDefinition.Namespace, observes)
            + $"namespace {implementationNamespace};\n\n"
            + "/// <summary>\n"
            + $"/// Represents the generated implementation of <see cref=\"{contractTypeName}\"/>.\n"
            + "/// </summary>\n"
            + Declaration(serviceDefinition.ServiceName, typeName, contractTypeName, context, hasQueries)
            + "{\n"
            + string.Join('\n', members)
            + "}\n";

        var folder = Path.Combine([outputDirectory, .. segments]);
        Directory.CreateDirectory(folder);
        var path = Path.Combine(folder, $"{serviceDefinition.ServiceName}.cs");
        File.WriteAllText(path, code);

        return new(serviceDefinition.ServiceName, contractTypeName, typeName, path);
    }

    static string Usings(string artifactsNamespace, bool observes)
    {
        // The artifact namespace is always imported so hand-written converters (ToApi/ToContract) sitting
        // alongside the Arc artifacts resolve as extension methods - the generated code below calls them by
        // fluent syntax, and a fully-qualified call site does not bring extension methods into scope.
        var usings = $"using {artifactsNamespace};\n";

        if (observes)
        {
            usings += "using System.Reactive.Linq;\nusing Cratis.Reactive;\n";
        }

        return usings + "\n";
    }

    static string Declaration(string serviceName, string typeName, string contractTypeName, ImplementationContext context, bool hasQueries)
    {
        var parameters = context.Dependencies.All
            .Select(dependency => $"    {QualifiedTypeName.For(dependency.Type)} {dependency.Name}")
            .ToList();

        // The logger only appears when something can actually fail through QueryExecutor; an unused primary
        // constructor parameter is a warning, and this file is not one anybody can suppress it in.
        if (hasQueries)
        {
            parameters.Add($"    global::Microsoft.Extensions.Logging.ILogger<{typeName}> logger");
        }

        var builder = new StringBuilder($"internal sealed class {serviceName}(\n");
        builder.AppendJoin(",\n", parameters);
        builder.AppendLine($") : {contractTypeName}");
        return builder.ToString();
    }

    static string Join(string baseNamespace, IEnumerable<string> segments)
    {
        var joined = string.Join('.', segments);
        return string.IsNullOrEmpty(baseNamespace) ? joined : $"{baseNamespace}.{joined}";
    }
}
