// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cratis.Chronicle.Tools.GrpcCodeGenerator;

/// <summary>
/// Generates C# gRPC service interface files from service definitions using Roslyn SyntaxFactory.
/// </summary>
/// <param name="skipNamespaceSegments">The number of leading namespace segments to skip.</param>
/// <param name="baseNamespace">The base namespace to prepend to generated types.</param>
public class ServiceInterfaceGenerator(int skipNamespaceSegments, string baseNamespace)
{
    const string CopyrightHeader =
        "// Copyright (c) Cratis. All rights reserved.\n" +
        "// Licensed under the MIT license. See LICENSE file in the project root for full license information.\n\n" +
        "// <auto-generated />\n\n";

    /// <summary>
    /// Generates a C# interface file for the given service definition.
    /// </summary>
    /// <param name="serviceDefinition">The service definition.</param>
    /// <param name="outputDirectory">The output directory.</param>
    /// <returns>The generated C# source code.</returns>
    public string Generate(ServiceDefinition serviceDefinition, string outputDirectory)
    {
        var targetNamespace = BuildTargetNamespace(serviceDefinition.Namespace);
        var folderPath = BuildFolderPath(serviceDefinition.Namespace, outputDirectory);

        Directory.CreateDirectory(folderPath);

        var requestResponseTypes = new List<(string TypeName, List<(string PropName, string PropType)> Properties)>();

        var interfaceMembers = new List<MemberDeclarationSyntax>();
        foreach (var command in serviceDefinition.Commands)
        {
            var requestTypeName = GenerateCommandRequestType(command, requestResponseTypes);
            interfaceMembers.Add(BuildCommandMethod(command, requestTypeName));
        }

        foreach (var query in serviceDefinition.Queries)
        {
            foreach (var method in query.Methods)
            {
                interfaceMembers.Add(BuildQueryMethod(method, query.ReadModelType, requestResponseTypes));
            }
        }

        var interfaceDecl = SyntaxFactory.InterfaceDeclaration($"I{serviceDefinition.ServiceName}")
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("Service")))))
            .WithLeadingTrivia(BuildXmlDoc($"Defines the gRPC service contract for {serviceDefinition.ServiceName}."))
            .AddMembers([.. interfaceMembers]);

        // All DTOs for a service are written to the same I{ServiceName}.cs file.
        // The path is computed once here so each DTO class can read the existing
        // [ProtoMember] indexes from the previous generation before we overwrite it.
        var fileName = GetSafeFileName($"I{serviceDefinition.ServiceName}.cs");
        var interfaceFilePath = Path.Combine(folderPath, fileName);

        var dtoClasses = requestResponseTypes
            .Select(rt =>
            {
                var existingIndexes = ProtoMemberIndexReader.ReadExistingIndexes(interfaceFilePath, rt.TypeName);
                return BuildDtoClass(rt.TypeName, rt.Properties, existingIndexes);
            })
            .Cast<MemberDeclarationSyntax>()
            .ToArray();

        MemberDeclarationSyntax[] allMembers = [interfaceDecl, .. dtoClasses];

        var namespaceDecl = SyntaxFactory.FileScopedNamespaceDeclaration(
                SyntaxFactory.ParseName(targetNamespace))
            .AddMembers(allMembers);

        UsingDirectiveSyntax[] usings =
        [
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("ProtoBuf")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("ProtoBuf.Grpc")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("ProtoBuf.Grpc.Configuration")),
        ];

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .AddUsings(usings)
            .AddMembers(namespaceDecl)
            .NormalizeWhitespace();

        var code = CopyrightHeader + compilationUnit.ToFullString();

        File.WriteAllText(interfaceFilePath, code);

        return code;
    }

    static MethodDeclarationSyntax BuildCommandMethod(CommandDefinition command, string? requestTypeName)
    {
        var parameters = new List<ParameterSyntax>();
        var paramDocs = new List<(string Name, string Text)>();

        if (requestTypeName is not null)
        {
            parameters.Add(
                SyntaxFactory.Parameter(SyntaxFactory.Identifier("request"))
                    .WithType(SyntaxFactory.ParseTypeName(requestTypeName)));
            paramDocs.Add(("request", $"The {command.Name} request."));
        }

        parameters.Add(BuildCallContextParameter());
        paramDocs.Add(("callContext", "The gRPC call context."));

        return SyntaxFactory.MethodDeclaration(
                SyntaxFactory.ParseTypeName("Task"),
                SyntaxFactory.Identifier(command.Name))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("Operation")))))
            .AddParameterListParameters([.. parameters])
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(BuildXmlDoc(
                $"Executes the {command.Name} command.",
                [.. paramDocs],
                "A task that represents the asynchronous operation."));
    }

    static MethodDeclarationSyntax BuildQueryMethod(
        QueryMethodDefinition method,
        Type readModelType,
        List<(string TypeName, List<(string PropName, string PropType)> Properties)> requestResponseTypes)
    {
        var returnType = method.ReturnType;
        var isObservable = TypeHelper.IsObservableType(returnType);
        var responseTypeName = $"{readModelType.Name}Response";

        var readModelProperties = GetReadModelProperties(readModelType);
        if (readModelProperties.Count > 0 && !requestResponseTypes.Exists(r => r.TypeName == responseTypeName))
        {
            requestResponseTypes.Add((responseTypeName, readModelProperties));
        }

        string returnTypeStr;
        if (isObservable)
        {
            var innerType = GetObservableInnerType(returnType);
            returnTypeStr = innerType is not null
                ? $"IObservable<{MapToResponseType(innerType, responseTypeName)}>"
                : $"IObservable<{responseTypeName}>";
        }
        else
        {
            var queryReturnType = TypeHelper.GetQueryReturnType(returnType);
            if (TypeHelper.IsOneOfType(queryReturnType))
            {
                queryReturnType = TypeHelper.GetOneOfSuccessType(queryReturnType);
            }

            var mapped = MapToResponseType(queryReturnType, responseTypeName);
            returnTypeStr = TypeHelper.IsVoidTask(returnType) ? "Task" : $"Task<{mapped}>";
        }

        var parameters = new List<ParameterSyntax>();
        var paramDocs = new List<(string Name, string Text)>();

        if (method.Parameters.Count > 0)
        {
            var requestTypeName = $"{method.Name}Request";
            var props = method.Parameters.Select(p =>
            {
                var unwrapped = TypeHelper.UnwrapConceptType(p.ParameterType);
                return (p.Name ?? "value", TypeHelper.GetTypeName(unwrapped));
            }).ToList();

            if (!requestResponseTypes.Exists(r => r.TypeName == requestTypeName))
            {
                requestResponseTypes.Add((requestTypeName, props!));
            }

            parameters.Add(
                SyntaxFactory.Parameter(SyntaxFactory.Identifier("request"))
                    .WithType(SyntaxFactory.ParseTypeName(requestTypeName)));
            paramDocs.Add(("request", "The query request parameters."));
        }

        parameters.Add(BuildCallContextParameter());
        paramDocs.Add(("callContext", "The gRPC call context."));

        return SyntaxFactory.MethodDeclaration(
                SyntaxFactory.ParseTypeName(returnTypeStr),
                SyntaxFactory.Identifier(method.Name))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("Operation")))))
            .AddParameterListParameters([.. parameters])
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken))
            .WithLeadingTrivia(BuildXmlDoc(
                $"Executes the {method.Name} query.",
                [.. paramDocs],
                "The query result."));
    }

    static ClassDeclarationSyntax BuildDtoClass(
        string typeName,
        List<(string PropName, string PropType)> properties,
        IReadOnlyDictionary<string, int> existingIndexes)
    {
        var nextIndex = existingIndexes.Count > 0 ? existingIndexes.Values.Max() + 1 : 1;

        var propertyMembers = new List<MemberDeclarationSyntax>();
        foreach (var (propName, propType) in properties)
        {
            var pascalName = ToPascalCase(propName);
            var index = existingIndexes.TryGetValue(pascalName, out var existing) ? existing : nextIndex++;
            propertyMembers.Add(BuildDtoProperty(propName, propType, index));
        }

        return SyntaxFactory.ClassDeclaration(typeName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(SyntaxFactory.ParseName("ProtoContract")))))
            .WithLeadingTrivia(BuildXmlDoc($"Represents the {typeName} message."))
            .AddMembers([.. propertyMembers]);
    }

    static PropertyDeclarationSyntax BuildDtoProperty(string propName, string propType, int protoMemberIndex) =>
        SyntaxFactory.PropertyDeclaration(
                SyntaxFactory.ParseTypeName(propType),
                SyntaxFactory.Identifier(ToPascalCase(propName)))
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddAttributeLists(
                SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                    SyntaxFactory.Attribute(
                        SyntaxFactory.ParseName("ProtoMember"),
                        SyntaxFactory.AttributeArgumentList(
                            SyntaxFactory.SingletonSeparatedList(
                                SyntaxFactory.AttributeArgument(
                                    SyntaxFactory.LiteralExpression(
                                        SyntaxKind.NumericLiteralExpression,
                                        SyntaxFactory.Literal(protoMemberIndex)))))))))
            .AddAccessorListAccessors(
                SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                    .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)),
                SyntaxFactory.AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                    .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)))
            .WithLeadingTrivia(BuildXmlDoc($"Gets or sets the {propName}."));

    static ParameterSyntax BuildCallContextParameter() =>
        SyntaxFactory.Parameter(SyntaxFactory.Identifier("callContext"))
            .WithType(SyntaxFactory.ParseTypeName("CallContext"))
            .WithDefault(SyntaxFactory.EqualsValueClause(
                SyntaxFactory.LiteralExpression(SyntaxKind.DefaultLiteralExpression)));

    static SyntaxTriviaList BuildXmlDoc(
        string summary,
        IEnumerable<(string Name, string Text)>? paramDocs = null,
        string? returns = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {summary}");
        sb.AppendLine("/// </summary>");

        if (paramDocs is not null)
        {
            foreach (var (name, text) in paramDocs)
            {
                sb.AppendLine($"/// <param name=\"{name}\">{text}</param>");
            }
        }

        if (returns is not null)
        {
            sb.AppendLine($"/// <returns>{returns}</returns>");
        }

        return SyntaxFactory.ParseLeadingTrivia(sb.ToString());
    }

    static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    static string GetSafeFileName(string fileName)
    {
        if (string.IsNullOrEmpty(fileName))
        {
            return fileName;
        }

        fileName = Path.GetFileName(fileName);

        var invalidChars = Path.GetInvalidFileNameChars();
        var builder = new StringBuilder(fileName.Length);
        foreach (var ch in fileName)
        {
            builder.Append(Array.IndexOf(invalidChars, ch) >= 0 ? '_' : ch);
        }

        return builder.ToString();
    }

    static string? GenerateCommandRequestType(
        CommandDefinition command,
        List<(string TypeName, List<(string PropName, string PropType)> Properties)> requestResponseTypes)
    {
        var parameters = command.Parameters;
        if (parameters.Count == 0)
        {
            return null;
        }

        var requestTypeName = $"{command.Name}Request";
        var properties = parameters.Select(p =>
        {
            var unwrapped = TypeHelper.UnwrapConceptType(p.ParameterType);
            return (p.Name ?? "value", TypeHelper.GetTypeName(unwrapped));
        }).ToList();

        requestResponseTypes.Add((requestTypeName, properties!));
        return requestTypeName;
    }

    static string MapToResponseType(Type type, string responseTypeName)
    {
        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition();
            var args = type.GetGenericArguments();

            if (genericDef.FullName?.StartsWith("System.Collections.Generic.IEnumerable`", StringComparison.Ordinal) == true)
            {
                var innerMapped = MapToResponseType(args[0], responseTypeName);
                return $"IEnumerable<{innerMapped}>";
            }

            if (genericDef.Name.StartsWith("Nullable`", StringComparison.Ordinal))
            {
                return $"{MapToResponseType(args[0], responseTypeName)}?";
            }
        }

        if (TypeHelper.IsReadModelType(type))
        {
            return responseTypeName;
        }

        if (TypeHelper.IsConceptType(type))
        {
            return TypeHelper.GetTypeName(TypeHelper.UnwrapConceptType(type));
        }

        return TypeHelper.GetTypeName(type);
    }

    static Type? GetObservableInnerType(Type type)
    {
        if (type.IsGenericType)
        {
            var genericDef = type.GetGenericTypeDefinition();
            if (genericDef.Name.StartsWith("ISubject`", StringComparison.Ordinal) ||
                genericDef.Name.StartsWith("IObservable`", StringComparison.Ordinal) ||
                genericDef.Name.StartsWith("BehaviorSubject`", StringComparison.Ordinal))
            {
                return type.GetGenericArguments()[0];
            }
        }

        var observableInterface = type.GetInterfaces()
            .FirstOrDefault(i => i.IsGenericType &&
                (i.GetGenericTypeDefinition().Name.StartsWith("ISubject`", StringComparison.Ordinal) ||
                 i.GetGenericTypeDefinition().Name.StartsWith("IObservable`", StringComparison.Ordinal)));

        return observableInterface?.GetGenericArguments()[0];
    }

    static List<(string PropName, string PropType)> GetReadModelProperties(Type readModelType)
    {
        var constructor = readModelType.GetConstructors().FirstOrDefault();
        if (constructor is null)
        {
            return [];
        }

        return constructor.GetParameters()
            .Select(p =>
            {
                var unwrapped = TypeHelper.UnwrapConceptType(p.ParameterType);
                return (p.Name ?? "value", TypeHelper.GetTypeName(unwrapped));
            })
            .ToList()!;
    }

    string BuildTargetNamespace(string sourceNamespace)
    {
        var segments = sourceNamespace.Split('.');
        var skipped = segments.Skip(skipNamespaceSegments).ToArray();

        if (!string.IsNullOrEmpty(baseNamespace))
        {
            return $"{baseNamespace}.{string.Join('.', skipped)}";
        }

        return string.Join('.', skipped);
    }

    string BuildFolderPath(string sourceNamespace, string outputDirectory)
    {
        var segments = sourceNamespace.Split('.');
        var skipped = segments.Skip(skipNamespaceSegments).ToArray();
        var safeSegments = skipped
            .Select(s => s.TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar))
            .ToArray();

        return Path.Combine([outputDirectory, .. safeSegments]);
    }
}
