// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Security;
using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.Security;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Security.IUsers"/>.
/// </summary>
internal sealed class Users(
    global::Cratis.Arc.Commands.ICommandPipeline commandPipeline,
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Security.Users> logger) : global::Cratis.Chronicle.Contracts.Security.IUsers
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AddUser(global::Cratis.Chronicle.Contracts.Security.AddUserRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Security.AddUser((global::Cratis.Chronicle.Concepts.Security.UserId)request.UserId, (global::Cratis.Chronicle.Concepts.Security.Username)request.Username, (global::Cratis.Chronicle.Concepts.Security.UserEmail)request.Email, (global::Cratis.Chronicle.Concepts.Security.Password)request.Password));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> ChangeUserPassword(global::Cratis.Chronicle.Contracts.Security.ChangeUserPasswordRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Security.ChangeUserPassword((global::Cratis.Chronicle.Concepts.Security.UserId)request.UserId, (global::Cratis.Chronicle.Concepts.Security.Password)request.OldPassword, (global::Cratis.Chronicle.Concepts.Security.Password)request.Password, (global::Cratis.Chronicle.Concepts.Security.Password)request.ConfirmedPassword));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RemoveUser(global::Cratis.Chronicle.Contracts.Security.RemoveUserRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Security.RemoveUser((global::Cratis.Chronicle.Concepts.Security.UserId)request.UserId));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RequirePasswordChange(global::Cratis.Chronicle.Contracts.Security.RequirePasswordChangeRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Security.RequirePasswordChange((global::Cratis.Chronicle.Concepts.Security.UserId)request.UserId));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> SetInitialAdminPassword(global::Cratis.Chronicle.Contracts.Security.SetInitialAdminPasswordRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            commandPipeline,
            new global::Cratis.Chronicle.Security.SetInitialAdminPassword((global::Cratis.Chronicle.Concepts.Security.UserId)request.UserId, (global::Cratis.Chronicle.Concepts.Security.Password)request.Password, (global::Cratis.Chronicle.Concepts.Security.Password)request.ConfirmedPassword));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Security.AdminPasswordStatusResponse>> GetStatus(global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Security.AdminPasswordStatusResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Security.AdminPasswordStatus.GetStatus(storage);
                return ToAdminPasswordStatusResponse(result);
            },
            exception => logger.QueryFailed(exception, "Users", "GetStatus"));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.Security.UserResponse>>> AllUsers(global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.Security.UserResponse>>(
            () => global::Cratis.Chronicle.Security.User.AllUsers(storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.Security.UserResponse>)_.Select(ToUserResponse).ToList()),
            exception => logger.QueryFailed(exception, "Users", "AllUsers"));

    static global::Cratis.Chronicle.Contracts.Security.AdminPasswordStatusResponse ToAdminPasswordStatusResponse(global::Cratis.Chronicle.Security.AdminPasswordStatus source) =>
        new()
        {
            IsRequired = source.IsRequired,
            AdminUserId = source.AdminUserId
        };

    static global::Cratis.Chronicle.Contracts.Security.UserResponse ToUserResponse(global::Cratis.Chronicle.Security.User source) =>
        new()
        {
            Id = source.Id,
            Username = source.Username,
            Email = source.Email,
            IsActive = source.IsActive,
            CreatedAt = (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset)source.CreatedAt,
            LastModifiedAt = source.LastModifiedAt is null ? null : (global::Cratis.Chronicle.Contracts.Primitives.SerializableDateTimeOffset?)source.LastModifiedAt,
            HasLoggedIn = source.HasLoggedIn
        };
}
