// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Contracts.Commands;
using Cratis.Chronicle.Contracts.Primitives;
using Cratis.Chronicle.Contracts.Queries;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;

namespace Cratis.Chronicle.Contracts.EventTypes;
/// <summary>
/// Defines the gRPC service contract for EventTypes.
/// </summary>
[Service]
public interface IEventTypes
{
    /// <summary>
    /// Executes the CreateEventType command.
    /// </summary>
    /// <param name = "request">The CreateEventType request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> CreateEventType(CreateEventTypeRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RegisterEventTypes command.
    /// </summary>
    /// <param name = "request">The RegisterEventTypes request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RegisterEventTypes(RegisterEventTypesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the RegisterSingleEventType command.
    /// </summary>
    /// <param name = "request">The RegisterSingleEventType request.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The command result.</returns>
    [Operation]
    Task<CommandResult> RegisterSingleEventType(RegisterSingleEventTypeRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllEventTypes query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<EventTypeDetailsResponse>>> AllEventTypes(AllEventTypesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the ObserveEventTypes query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    IObservable<QueryResult<IEnumerable<EventTypeDetailsResponse>>> ObserveEventTypes(ObserveEventTypesRequest request, CallContext callContext = default);
    /// <summary>
    /// Executes the AllEventTypeGenerations query.
    /// </summary>
    /// <param name = "request">The query request parameters.</param>
    /// <param name = "callContext">The gRPC call context.</param>
    /// <returns>The query result.</returns>
    [Operation]
    Task<QueryResult<IEnumerable<EventTypeDetailsResponse>>> AllEventTypeGenerations(AllEventTypeGenerationsRequest request, CallContext callContext = default);
}

/// <summary>
/// Represents the CreateEventTypeRequest message.
/// </summary>
[ProtoContract]
public class CreateEventTypeRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Name.
    /// </summary>
    [ProtoMember(2)]
    public string Name { get; set; }
}

/// <summary>
/// Represents the RegisterEventTypesRequest message.
/// </summary>
[ProtoContract]
public class RegisterEventTypesRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Types.
    /// </summary>
    [ProtoMember(2)]
    public IEnumerable<global::Cratis.Chronicle.Contracts.Events.EventTypeRegistration> Types { get; set; } = new List<global::Cratis.Chronicle.Contracts.Events.EventTypeRegistration>();

    /// <summary>
    /// Gets or sets the DisableValidation.
    /// </summary>
    [ProtoMember(3)]
    public bool DisableValidation { get; set; }
}

/// <summary>
/// Represents the RegisterSingleEventTypeRequest message.
/// </summary>
[ProtoContract]
public class RegisterSingleEventTypeRequest
{
    /// <summary>
    /// Gets or sets the EventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the Type.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Events.EventTypeRegistration Type { get; set; }
}

/// <summary>
/// Represents the EventTypeDetailsResponse message.
/// </summary>
[ProtoContract]
public class EventTypeDetailsResponse
{
    /// <summary>
    /// Gets or sets the Id.
    /// </summary>
    [ProtoMember(5)]
    public string Id { get; set; }

    /// <summary>
    /// Gets or sets the Type.
    /// </summary>
    [ProtoMember(1)]
    public global::Cratis.Chronicle.Contracts.Events.EventType Type { get; set; }

    /// <summary>
    /// Gets or sets the Owner.
    /// </summary>
    [ProtoMember(2)]
    public global::Cratis.Chronicle.Contracts.Events.EventTypeOwner Owner { get; set; }

    /// <summary>
    /// Gets or sets the Source.
    /// </summary>
    [ProtoMember(3)]
    public global::Cratis.Chronicle.Contracts.Events.EventTypeSource Source { get; set; }

    /// <summary>
    /// Gets or sets the Schema.
    /// </summary>
    [ProtoMember(4)]
    public string Schema { get; set; }
}

/// <summary>
/// Represents the AllEventTypesRequest message.
/// </summary>
[ProtoContract]
public class AllEventTypesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}

/// <summary>
/// Represents the ObserveEventTypesRequest message.
/// </summary>
[ProtoContract]
public class ObserveEventTypesRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }
}

/// <summary>
/// Represents the AllEventTypeGenerationsRequest message.
/// </summary>
[ProtoContract]
public class AllEventTypeGenerationsRequest
{
    /// <summary>
    /// Gets or sets the eventStore.
    /// </summary>
    [ProtoMember(1)]
    public string EventStore { get; set; }

    /// <summary>
    /// Gets or sets the eventTypeId.
    /// </summary>
    [ProtoMember(2)]
    public string EventTypeId { get; set; }
}