// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.Chronicle.CodeAnalysis.Specs.Analyzers.for_FluentPassiveProjectionKeyRedirectionAnalyzer.given;

public class a_fluent_passive_projection_key_redirection_analyzer : Specification
{
    protected static string CreateSource(string usage)
    {
        return string.Join(Environment.NewLine,
        [
            "using System;",
            "using System.Collections.Generic;",
            "using System.Linq.Expressions;",
            "using Cratis.Chronicle;",
            "using Cratis.Chronicle.Compliance.GDPR;",
            "using Cratis.Chronicle.Events;",
            "using Cratis.Chronicle.Keys;",
            "using Cratis.Chronicle.Properties;",
            "using Cratis.Chronicle.Projections;",
            "using Cratis.Chronicle.ReadModels;",
            "",
            "namespace System.Runtime.CompilerServices",
            "{",
            "    public sealed class IsExternalInit { }",
            "}",
            "",
            "namespace Cratis.Chronicle",
            "{",
            "    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]",
            "    public sealed class SubjectAttribute : Attribute { }",
            "}",
            "",
            "namespace Cratis.Chronicle.Compliance.GDPR",
            "{",
            "    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Parameter)]",
            "    public sealed class PIIAttribute : Attribute { }",
            "}",
            "",
            "namespace Cratis.Chronicle.Events",
            "{",
            "    public sealed class EventContext",
            "    {",
            "        public string EventSourceId { get; set; } = string.Empty;",
            "        public string Subject { get; set; } = string.Empty;",
            "        public string CorrelationId { get; set; } = string.Empty;",
            "    }",
            "}",
            "",
            "namespace Cratis.Chronicle.ReadModels",
            "{",
            "    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]",
            "    public sealed class PassiveAttribute : Attribute { }",
            "",
            "    public interface IReducerFor<TReadModel> { }",
            "}",
            "",
            "namespace Cratis.Chronicle.Keys",
            "{",
            "    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter)]",
            "    public sealed class KeyAttribute : Attribute { }",
            "}",
            "",
            "namespace Cratis.Chronicle.Properties",
            "{",
            "    public sealed record PropertyPath(string Path)",
            "    {",
            "        public static implicit operator PropertyPath(string path) => new(path);",
            "    }",
            "}",
            "",
            "namespace Cratis.Chronicle.Projections",
            "{",
            "    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Property | AttributeTargets.Parameter, Inherited = true)]",
            "    public sealed class NoAutoMapAttribute : Attribute { }",
            "",
            "    public interface ISetBuilder<TReadModel, TEvent, TParentBuilder>",
            "    {",
            "        TParentBuilder To(PropertyPath path);",
            "    }",
            "",
            "    public interface ISetBuilder<TReadModel, TEvent, TProperty, TParentBuilder> : ISetBuilder<TReadModel, TEvent, TParentBuilder>",
            "    {",
            "        TParentBuilder To(Expression<Func<TEvent, TProperty>> accessor);",
            "    }",
            "",
            "    public interface IAddBuilder<TReadModel, TEvent, TProperty, TParentBuilder>",
            "    {",
            "        TParentBuilder With(Expression<Func<TEvent, TProperty>> accessor);",
            "    }",
            "",
            "    public interface ISubtractBuilder<TReadModel, TEvent, TProperty, TParentBuilder>",
            "    {",
            "        TParentBuilder With(Expression<Func<TEvent, TProperty>> accessor);",
            "    }",
            "",
            "    public interface ICompositeKeyBuilder<TKeyType, TEvent>",
            "    {",
            "        ISetBuilder<TKeyType, TEvent, TProperty, ICompositeKeyBuilder<TKeyType, TEvent>> Set<TProperty>(Expression<Func<TKeyType, TProperty>> accessor);",
            "    }",
            "",
            "    public interface IReadModelPropertiesBuilder<TReadModel, TEvent, TBuilder>",
            "    {",
            "        TBuilder UsingKey<TProperty>(Expression<Func<TEvent, TProperty>> keyAccessor);",
            "        TBuilder UsingKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> keyAccessor);",
            "        TBuilder UsingParentKey<TProperty>(Expression<Func<TEvent, TProperty>> keyAccessor);",
            "        TBuilder UsingParentKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> keyAccessor);",
            "        TBuilder UsingCompositeKey<TKeyType>(Action<ICompositeKeyBuilder<TKeyType, TEvent>> builderCallback);",
            "        TBuilder UsingParentCompositeKey<TKeyType>(Action<ICompositeKeyBuilder<TKeyType, TEvent>> builderCallback);",
            "        TBuilder UsingConstantKey(string value);",
            "        TBuilder UsingConstantParentKey(string value);",
            "        IAddBuilder<TReadModel, TEvent, TProperty, TBuilder> Add<TProperty>(Expression<Func<TReadModel, TProperty>> accessor);",
            "        ISubtractBuilder<TReadModel, TEvent, TProperty, TBuilder> Subtract<TProperty>(Expression<Func<TReadModel, TProperty>> accessor);",
            "        TBuilder AddChild<TChildModel>(Expression<Func<TReadModel, IEnumerable<TChildModel>>> target, Expression<Func<TEvent, TChildModel>> source);",
            "        TBuilder AddChild<TChildModel>(Expression<Func<TReadModel, IEnumerable<TChildModel>>> target, Action<IAddChildBuilder<TChildModel, TEvent>> callback);",
            "        ISetBuilder<TReadModel, TEvent, TBuilder> Set(PropertyPath path);",
            "        ISetBuilder<TReadModel, TEvent, TProperty, TBuilder> Set<TProperty>(Expression<Func<TReadModel, TProperty>> accessor);",
            "        ISetBuilder<TReadModel, TEvent, TBuilder> SetThisValue();",
            "    }",
            "",
            "    public interface IAddChildBuilder<TChildModel, TEvent>",
            "    {",
            "        IAddChildBuilder<TChildModel, TEvent> UsingKey<TProperty>(Expression<Func<TEvent, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> UsingKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> UsingParentKey<TProperty>(Expression<Func<TEvent, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> UsingParentKeyFromContext<TProperty>(Expression<Func<EventContext, TProperty>> accessor);",
            "        IAddChildBuilder<TChildModel, TEvent> FromObject(Expression<Func<TEvent, TChildModel>> accessor);",
            "    }",
            "",
            "    public interface IFromBuilder<TReadModel, TEvent> : IReadModelPropertiesBuilder<TReadModel, TEvent, IFromBuilder<TReadModel, TEvent>>",
            "    {",
            "    }",
            "",
            "    public interface IJoinBuilder<TReadModel, TEvent> : IReadModelPropertiesBuilder<TReadModel, TEvent, IJoinBuilder<TReadModel, TEvent>>",
            "    {",
            "        IJoinBuilder<TReadModel, TEvent> On<TProperty>(Expression<Func<TReadModel, TProperty>> keyAccessor);",
            "    }",
            "",
            "    public interface IProjectionBuilder<TReadModel, TBuilder>",
            "    {",
            "        TBuilder AutoMap();",
            "        TBuilder NoAutoMap();",
            "        TBuilder From<TEvent>(Action<IFromBuilder<TReadModel, TEvent>>? builderCallback = default);",
            "        TBuilder Join<TEvent>(Action<IJoinBuilder<TReadModel, TEvent>>? builderCallback = default);",
            "        TBuilder Children<TChildModel>(Expression<Func<TReadModel, IEnumerable<TChildModel>>> targetProperty, Action<IChildrenBuilder<TReadModel, TChildModel>> builderCallback);",
            "        TBuilder Nested<TNestedModel>(Expression<Func<TReadModel, TNestedModel?>> targetProperty, Action<INestedBuilder<TReadModel, TNestedModel>> builderCallback);",
            "    }",
            "",
            "    public interface IChildrenBuilder<TParentReadModel, TChildReadModel> : IProjectionBuilder<TChildReadModel, IChildrenBuilder<TParentReadModel, TChildReadModel>>",
            "    {",
            "        IChildrenBuilder<TParentReadModel, TChildReadModel> IdentifiedBy<TProperty>(Expression<Func<TChildReadModel, TProperty>> accessor);",
            "    }",
            "",
            "    public interface INestedBuilder<TParentReadModel, TNestedReadModel> : IProjectionBuilder<TNestedReadModel, INestedBuilder<TParentReadModel, TNestedReadModel>>",
            "    {",
            "    }",
            "",
            "    public interface IProjectionBuilderFor<TReadModel> : IProjectionBuilder<TReadModel, IProjectionBuilderFor<TReadModel>>",
            "    {",
            "        IProjectionBuilderFor<TReadModel> Passive();",
            "    }",
            "",
            "    public interface IProjectionFor<TReadModel>",
            "    {",
            "        void Define(IProjectionBuilderFor<TReadModel> builder);",
            "    }",
            "}",
            "",
            "namespace Sample",
            "{",
            usage,
            "}"
        ]);
    }
}
