// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.EventSequences;

namespace Cratis.Chronicle.Services.EventSequences;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.EventSequences.IEventSequenceQueries"/>.
/// </summary>
internal sealed class EventSequenceQueries(
    global::Orleans.IGrainFactory grainFactory,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.EventSequences.EventSequenceQueries> logger) : global::Cratis.Chronicle.Contracts.EventSequences.IEventSequenceQueries
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<bool>> IsStreamCompleted(global::Cratis.Chronicle.Contracts.EventSequences.IsStreamCompletedRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<bool>(
            () => grainFactory.GetGrain<global::Cratis.Chronicle.EventSequences.IEventSequence>(global::Cratis.Chronicle.KeyHelper.Combine((global::Cratis.Chronicle.Concepts.EventSequences.EventSequenceId)request.EventSequenceId, (global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace)).IsStreamCompleted((global::Cratis.Chronicle.Concepts.Events.EventStreamType)request.EventStreamType, (global::Cratis.Chronicle.Concepts.Events.EventStreamId)request.EventStreamId),
            exception => logger.QueryFailed(exception, "EventSequenceQueries", "IsStreamCompleted"));
}
