// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Alerts;

namespace Cratis.Chronicle.Services.Alerts;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Alerts.IAlerts"/>.
/// </summary>
internal sealed class Alerts(
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Cratis.Chronicle.Alerts.IAlertIncidentsReadiness alertIncidentsReadiness,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Alerts.Alerts> logger) : global::Cratis.Chronicle.Contracts.Alerts.IAlerts
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponse>> GetOpenIncident(global::Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Alerts.AlertIncidentLookup.GetOpenIncident((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.Alerts.IncidentId)request.IncidentId, storage, alertIncidentsReadiness, (request.Namespace is null ? null : (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace));
                return ToAlertIncidentLookupResponse(result);
            },
            exception => logger.QueryFailed(exception, "Alerts", "GetOpenIncident"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse>> GetOpenIncidents(global::Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Alerts.AlertIncidentPage.GetOpenIncidents((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, storage, alertIncidentsReadiness, (request.Namespace is null ? null : (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace), (request.ObserverId is null ? null : (global::Cratis.Chronicle.Concepts.Observation.ObserverId)request.ObserverId), (request.Condition is null ? null : (global::Cratis.Chronicle.Concepts.Alerts.AlertConditionKind)request.Condition), (global::Cratis.Chronicle.Concepts.Alerts.AlertSeverity?)request.MinimumSeverity, request.Limit, request.AfterRaisedSequenceNumber, (request.AfterIncidentId is null ? null : (global::Cratis.Chronicle.Concepts.Alerts.IncidentId)request.AfterIncidentId));
                return ToAlertIncidentPageResponse(result);
            },
            exception => logger.QueryFailed(exception, "Alerts", "GetOpenIncidents"));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponse>> GetOpenIncidentCounts(global::Cratis.Chronicle.Contracts.Alerts.GetOpenIncidentCountsRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Alerts.AlertIncidentSummary.GetOpenIncidentCounts((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, storage, alertIncidentsReadiness, (request.Namespace is null ? null : (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace));
                return ToAlertIncidentSummaryResponse(result);
            },
            exception => logger.QueryFailed(exception, "Alerts", "GetOpenIncidentCounts"));

    static global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentLookupResponse ToAlertIncidentLookupResponse(global::Cratis.Chronicle.Alerts.AlertIncidentLookup source) =>
        new()
        {
            Status = (global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState)source.Status,
            Incident = source.Incident is null ? null : source.Incident.ToContract()
        };

    static global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentPageResponse ToAlertIncidentPageResponse(global::Cratis.Chronicle.Alerts.AlertIncidentPage source) =>
        new()
        {
            Status = (global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState)source.Status,
            Items = source.Items.Select(element0 => element0.ToContract()).ToList(),
            Next = source.Next is null ? null : source.Next.ToContract()
        };

    static global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentSummaryResponse ToAlertIncidentSummaryResponse(global::Cratis.Chronicle.Alerts.AlertIncidentSummary source) =>
        new()
        {
            Status = (global::Cratis.Chronicle.Contracts.Alerts.AlertIncidentsReadinessState)source.Status,
            Counts = source.Counts.Select(element0 => element0.ToContract()).ToList()
        };
}
