// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using Cratis.Chronicle.Decisions;

namespace Cratis.Chronicle.Services.Decisions;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.Decisions.IDecisionReadModels"/>.
/// </summary>
internal sealed class DecisionReadModels(
    global::Orleans.IGrainFactory grainFactory,
    global::Cratis.Chronicle.ReadModels.IReadModelsCompliance readModelsCompliance,
    global::System.Text.Json.JsonSerializerOptions jsonSerializerOptions,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.Decisions.DecisionReadModels> logger) : global::Cratis.Chronicle.Contracts.Decisions.IDecisionReadModels
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<global::Cratis.Chronicle.Contracts.Decisions.DecisionReadModelResponse>> GetInstanceForDecision(global::Cratis.Chronicle.Contracts.Decisions.GetInstanceForDecisionRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<global::Cratis.Chronicle.Contracts.Decisions.DecisionReadModelResponse>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.Decisions.DecisionReadModel.GetInstanceForDecision((global::Cratis.Chronicle.Concepts.EventStoreName)request.EventStore, (global::Cratis.Chronicle.Concepts.EventStoreNamespaceName)request.Namespace, (global::Cratis.Chronicle.Concepts.ReadModels.ReadModelIdentifier)request.ReadModelIdentifier, (global::Cratis.Chronicle.Concepts.ReadModels.ReadModelKey)request.Key, grainFactory, readModelsCompliance, jsonSerializerOptions);
                return ToDecisionReadModelResponse(result);
            },
            exception => logger.QueryFailed(exception, "DecisionReadModels", "GetInstanceForDecision"));

    static global::Cratis.Chronicle.Contracts.Decisions.DecisionReadModelResponse ToDecisionReadModelResponse(global::Cratis.Chronicle.Decisions.DecisionReadModel source) =>
        new()
        {
            Instance = source.Instance,
            SequenceNumber = source.SequenceNumber,
            EventTypes = source.EventTypes,
            Refusal = (global::Cratis.Chronicle.Contracts.Decisions.DecisionReadRefusal)source.Refusal
        };
}
