// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated />

#nullable enable

using System.Reactive.Linq;
using Cratis.Reactive;

namespace Cratis.Chronicle.Services.ExternalServices;

/// <summary>
/// Represents the generated implementation of <see cref="global::Cratis.Chronicle.Contracts.ExternalServices.IExternalServices"/>.
/// </summary>
internal sealed class ExternalServices(
    global::Cratis.Chronicle.Storage.IStorage storage,
    global::Microsoft.Extensions.Logging.ILogger<global::Cratis.Chronicle.Services.ExternalServices.ExternalServices> logger) : global::Cratis.Chronicle.Contracts.ExternalServices.IExternalServices
{
    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AddExternalService(global::Cratis.Chronicle.Contracts.ExternalServices.AddExternalServiceRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.ExternalServices.AddExternalService(request.EventStore, request.Id, request.Name, request.EndpointType, request.Url, request.AuthorizationType, request.BasicUsername, request.BasicPassword, request.BearerToken, request.OAuthAuthority, request.OAuthClientId, request.OAuthClientSecret, request.Headers, request.Host, request.Port, request.Database, request.Username, request.Password, request.Options),
            command => command.Handle(storage));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> AddExternalServices(global::Cratis.Chronicle.Contracts.ExternalServices.AddExternalServicesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.ExternalServices.AddExternalServices(request.EventStore, request.ExternalServices),
            command => command.Handle(storage));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RemoveExternalService(global::Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServiceRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.ExternalServices.RemoveExternalService(request.EventStore, request.ExternalServiceId),
            command => command.Handle(storage));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Commands.CommandResult> RemoveExternalServices(global::Cratis.Chronicle.Contracts.ExternalServices.RemoveExternalServicesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        CommandExecutor.Execute(
            new global::Cratis.Chronicle.ExternalServices.RemoveExternalServices(request.EventStore, request.ExternalServices),
            command => command.Handle(storage));

    /// <inheritdoc/>
    public Task<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse>>> GetExternalServices(global::Cratis.Chronicle.Contracts.ExternalServices.GetExternalServicesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse>>(
            async () =>
            {
                var result = await global::Cratis.Chronicle.ExternalServices.ExternalService.GetExternalServices(request.EventStore, storage);
                return result.Select(ToExternalServiceResponse).ToList();
            },
            exception => logger.QueryFailed(exception, "ExternalServices", "GetExternalServices"));

    /// <inheritdoc/>
    public IObservable<global::Cratis.Chronicle.Contracts.Queries.QueryResult<IEnumerable<global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse>>> ObserveExternalServices(global::Cratis.Chronicle.Contracts.ExternalServices.ObserveExternalServicesRequest request, global::ProtoBuf.Grpc.CallContext callContext = default) =>
        QueryExecutor.Execute<IEnumerable<global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse>>(
            () => global::Cratis.Chronicle.ExternalServices.ExternalService.ObserveExternalServices(request.EventStore, storage)
                .CompletedBy(callContext.CancellationToken)
                .Select(_ => (IEnumerable<global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse>)_.Select(ToExternalServiceResponse).ToList()),
            exception => logger.QueryFailed(exception, "ExternalServices", "ObserveExternalServices"));

    static global::Cratis.Chronicle.Contracts.ExternalServices.ExternalServiceResponse ToExternalServiceResponse(global::Cratis.Chronicle.ExternalServices.ExternalService source) =>
        new()
        {
            Id = source.Id,
            Name = source.Name,
            EndpointType = source.EndpointType,
            Url = source.Url,
            AuthorizationType = source.AuthorizationType,
            Headers = source.Headers,
            Host = source.Host,
            Port = source.Port,
            Database = source.Database,
            Username = source.Username,
            Options = source.Options
        };
}
