name: Base Development Image

on:
  pull_request:
    types: [closed]
    branches:
      - "**"
    paths:
      - "Docker/BaseDevelopment/**"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      publish: ${{ steps.release.outputs.should-publish }}
      prerelease: ${{ steps.release.outputs.prerelease }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release
        id: release
        uses: aksio-insurtech/release-action@v1
        with:
          user-name: "Aksio Build"
          user-email: "build@aksio.no"

  publish-docker:
    if: needs.release.outputs.publish == 'true'
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Development Docker Image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Docker/BaseDevelopment/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            aksioinsurtech/cratis-base:${{ needs.release.outputs.version }}-development
            aksioinsurtech/cratis-base:latest-development
          build-args: |
            VERSION=${{ needs.release.outputs.version }}
