
name: Build

on:
  push:
    branches:
      - "**"
    paths:
      - "**/*.cs"

jobs:
  build:
    name: "Build .NET"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.7.21379.14'
      - name: Build .NET
        run: dotnet build --configuration Release
      - name: Test .NET
        run: dotnet test --configuration Release --no-build
