name: Issue Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 * * *"

permissions:
  contents: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: read
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run issue-metrics tool
        uses: github/issue-metrics@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'repo:cratis/chronicle is:issue -reason:"not planned"'

      - name: Commit and push report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add issue_metrics.md
          git commit -m "Update issue metrics report" || echo "No changes to commit"
          git push
