name: Update Packages

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    uses: Cratis/Workflows/.github/workflows/update-packages.yml@main
    with:
      package_types: 'NuGet, NPM'
    secrets:
      PAT_WORKFLOWS: ${{ secrets.PAT_WORKFLOWS }}
